//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.ReportSettingMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportSettingMasterService.IReportSettingMaster")]
    public interface IReportSettingMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportSettingMaster/GetItems", ReplyAction="http://tempuri.org/IReportSettingMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.ReportSettingsResult GetItems(string SessionKey, int CompanyId, string ReportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportSettingMaster/GetItems", ReplyAction="http://tempuri.org/IReportSettingMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReportSettingsResult> GetItemsAsync(string SessionKey, int CompanyId, string ReportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportSettingMaster/Save", ReplyAction="http://tempuri.org/IReportSettingMaster/SaveResponse")]
        Rac.VOne.Web.Models.ReportSettingsResult Save(string SessionKey, Rac.VOne.Web.Models.ReportSetting[] ReportSetting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportSettingMaster/Save", ReplyAction="http://tempuri.org/IReportSettingMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReportSettingsResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.ReportSetting[] ReportSetting);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportSettingMasterChannel : Rac.VOne.Client.Screen.ReportSettingMasterService.IReportSettingMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportSettingMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.ReportSettingMasterService.IReportSettingMaster>, Rac.VOne.Client.Screen.ReportSettingMasterService.IReportSettingMaster {
        
        public ReportSettingMasterClient() {
        }
        
        public ReportSettingMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportSettingMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportSettingMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportSettingMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.ReportSettingsResult GetItems(string SessionKey, int CompanyId, string ReportId) {
            return base.Channel.GetItems(SessionKey, CompanyId, ReportId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReportSettingsResult> GetItemsAsync(string SessionKey, int CompanyId, string ReportId) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId, ReportId);
        }
        
        public Rac.VOne.Web.Models.ReportSettingsResult Save(string SessionKey, Rac.VOne.Web.Models.ReportSetting[] ReportSetting) {
            return base.Channel.Save(SessionKey, ReportSetting);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReportSettingsResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.ReportSetting[] ReportSetting) {
            return base.Channel.SaveAsync(SessionKey, ReportSetting);
        }
    }
}
