//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.PeriodicBillingSettingMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeriodicBillingSettingMasterService.IPeriodicBillingSettingMaster")]
    public interface IPeriodicBillingSettingMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodicBillingSettingMaster/GetItems", ReplyAction="http://tempuri.org/IPeriodicBillingSettingMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.PeriodicBillingSettingsResult GetItems(string sessionKey, Rac.VOne.Web.Models.PeriodicBillingSettingSearch option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodicBillingSettingMaster/GetItems", ReplyAction="http://tempuri.org/IPeriodicBillingSettingMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.PeriodicBillingSettingsResult> GetItemsAsync(string sessionKey, Rac.VOne.Web.Models.PeriodicBillingSettingSearch option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodicBillingSettingMaster/Save", ReplyAction="http://tempuri.org/IPeriodicBillingSettingMaster/SaveResponse")]
        Rac.VOne.Web.Models.PeriodicBillingSettingResult Save(string sessionKey, Rac.VOne.Web.Models.PeriodicBillingSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodicBillingSettingMaster/Save", ReplyAction="http://tempuri.org/IPeriodicBillingSettingMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.PeriodicBillingSettingResult> SaveAsync(string sessionKey, Rac.VOne.Web.Models.PeriodicBillingSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodicBillingSettingMaster/Delete", ReplyAction="http://tempuri.org/IPeriodicBillingSettingMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string sessionKey, long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodicBillingSettingMaster/Delete", ReplyAction="http://tempuri.org/IPeriodicBillingSettingMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string sessionKey, long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPeriodicBillingSettingMasterChannel : Rac.VOne.Client.Screen.PeriodicBillingSettingMasterService.IPeriodicBillingSettingMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeriodicBillingSettingMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.PeriodicBillingSettingMasterService.IPeriodicBillingSettingMaster>, Rac.VOne.Client.Screen.PeriodicBillingSettingMasterService.IPeriodicBillingSettingMaster {
        
        public PeriodicBillingSettingMasterClient() {
        }
        
        public PeriodicBillingSettingMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeriodicBillingSettingMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeriodicBillingSettingMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeriodicBillingSettingMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.PeriodicBillingSettingsResult GetItems(string sessionKey, Rac.VOne.Web.Models.PeriodicBillingSettingSearch option) {
            return base.Channel.GetItems(sessionKey, option);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.PeriodicBillingSettingsResult> GetItemsAsync(string sessionKey, Rac.VOne.Web.Models.PeriodicBillingSettingSearch option) {
            return base.Channel.GetItemsAsync(sessionKey, option);
        }
        
        public Rac.VOne.Web.Models.PeriodicBillingSettingResult Save(string sessionKey, Rac.VOne.Web.Models.PeriodicBillingSetting setting) {
            return base.Channel.Save(sessionKey, setting);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.PeriodicBillingSettingResult> SaveAsync(string sessionKey, Rac.VOne.Web.Models.PeriodicBillingSetting setting) {
            return base.Channel.SaveAsync(sessionKey, setting);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string sessionKey, long id) {
            return base.Channel.Delete(sessionKey, id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string sessionKey, long id) {
            return base.Channel.DeleteAsync(sessionKey, id);
        }
    }
}
