namespace Rac.VOne.Common.Importer.Receipt
{
    public enum Fields
    {
        ///<summary>得意先コード</summary>
        CustomerCode = 1,
        ///<summary>入金日</summary>
        RecordedAt,
        ///<summary>入金区分</summary>
        ReceiptCategoryCode,
        ///<summary>入金額</summary>
        ReceiptAmount,
        ///<summary>期日</summary>
        DueAt,
        ///<summary>備考</summary>
        Note1,
        ///<summary>入金部門コード</summary>
        SectionCode,
        ///<summary>通貨コード</summary>
        CurrencyCode,
        ///<summary>備考2</summary>
        Note2,
        ///<summary>備考3</summary>
        Note3,
        ///<summary>備考4</summary>
        Note4,
        ///<summary>振込依頼人名</summary>
        PayerName,
        ///<summary>銀行コード</summary>
        BankCode,
        ///<summary>銀行名</summary>
        BankName,
        ///<summary>支店コード</summary>
        BranchCode,
        ///<summary>支店名</summary>
        BranchName,
        ///<summary>預金種別</summary>
        AccountTypeId,
        ///<summary>口座番号</summary>
        AccountNumber,
        ///<summary>口座名</summary>
        AccountName,
        ///<summary>仕向銀行</summary>
        SourceBankName,
        ///<summary>仕向支店</summary>
        SourceBranchName,
        ///<summary>手形番号</summary>
        BillNumber,
        ///<summary>券面銀行コード</summary>
        BillBankCode,
        ///<summary>券面支店コード</summary>
        BillBranchCode,
        ///<summary>振出日</summary>
        BillDrawAt,
        ///<summary>振出人</summary>
        BillDrawer,
    }
}