//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.ClosingSettingMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClosingSettingMasterService.IClosingSettingMaster")]
    public interface IClosingSettingMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClosingSettingMaster/Get", ReplyAction="http://tempuri.org/IClosingSettingMaster/GetResponse")]
        Rac.VOne.Web.Models.ClosingSettingResult Get(string sessionKey, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClosingSettingMaster/Get", ReplyAction="http://tempuri.org/IClosingSettingMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ClosingSettingResult> GetAsync(string sessionKey, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClosingSettingMaster/Save", ReplyAction="http://tempuri.org/IClosingSettingMaster/SaveResponse")]
        Rac.VOne.Web.Models.ClosingSettingResult Save(string sessionKey, Rac.VOne.Web.Models.ClosingSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClosingSettingMaster/Save", ReplyAction="http://tempuri.org/IClosingSettingMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ClosingSettingResult> SaveAsync(string sessionKey, Rac.VOne.Web.Models.ClosingSetting setting);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClosingSettingMasterChannel : Rac.VOne.Client.Screen.ClosingSettingMasterService.IClosingSettingMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClosingSettingMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.ClosingSettingMasterService.IClosingSettingMaster>, Rac.VOne.Client.Screen.ClosingSettingMasterService.IClosingSettingMaster {
        
        public ClosingSettingMasterClient() {
        }
        
        public ClosingSettingMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClosingSettingMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClosingSettingMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClosingSettingMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.ClosingSettingResult Get(string sessionKey, int companyId) {
            return base.Channel.Get(sessionKey, companyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ClosingSettingResult> GetAsync(string sessionKey, int companyId) {
            return base.Channel.GetAsync(sessionKey, companyId);
        }
        
        public Rac.VOne.Web.Models.ClosingSettingResult Save(string sessionKey, Rac.VOne.Web.Models.ClosingSetting setting) {
            return base.Channel.Save(sessionKey, setting);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ClosingSettingResult> SaveAsync(string sessionKey, Rac.VOne.Web.Models.ClosingSetting setting) {
            return base.Channel.SaveAsync(sessionKey, setting);
        }
    }
}
