namespace Rac.VOne.Common.Importer.Billing
{
    public enum Fields
    {
        ///<summary>会社コード</summary>
        CompanyCode = 1,
        ///<summary>得意先コード</summary>
        CustomerCode,
        ///<summary>請求日</summary>
        BilledAt,
        ///<summary>請求金額</summary>
        BillingAmount,
        ///<summary>消費税</summary>
        TaxAmount,
        ///<summary>入金予定日</summary>
        DueAt,
        ///<summary>請求部門</summary>
        DepartmentCode,
        ///<summary>債権科目</summary>
        DebitAccountTitleCode,
        ///<summary>売上日</summary>
        SalesAt,
        ///<summary>請求書番号</summary>
        InvoiceCode,
        ///<summary>請求締日</summary>
        ClosingAt,
        ///<summary>担当者</summary>
        StaffCode,
        ///<summary>備考</summary>
        Note1,
        ///<summary>請求区分</summary>
        BillingCategoryCode,
        ///<summary>回収区分</summary>
        CollectCategoryCode,
        ///<summary>数量</summary>
        Quantity,
        ///<summary>単位</summary>
        UnitSymbol,
        ///<summary>単価</summary>
        UnitPrice,
        ///<summary>契約番号</summary>
        ContractNumber,
        ///<summary>金額（抜）</summary>
        Price,
        ///<summary>税区</summary>
        TaxClassId,
        ///<summary>備考2</summary>
        Note2,
        ///<summary>備考3</summary>
        Note3,
        ///<summary>備考4</summary>
        Note4,
        ///<summary>備考5</summary>
        Note5,
        ///<summary>備考6</summary>
        Note6,
        ///<summary>備考7</summary>
        Note7,
        ///<summary>備考8</summary>
        Note8,
        ///<summary>得意先名称</summary>
        CustomerName,
        ///<summary>得意先カナ</summary>
        CustomerKana,
        /// <summary>照合番号</summary>
        CollationKey,
        ///<summary>歩引利用</summary>
        UseDiscount,
        ///<summary>通貨コード</summary>
        CurrencyCode,
        ///<summary>銀行コード</summary>
        ExclusiveBankCode,
        ///<summary>支店コード</summary>
        ExclusiveBranchCode,
        ///<summary>仮想支店コード</summary>
        ExclusiveVirtualBranchCode,
        ///<summary>仮想口座番号</summary>
        ExclusiveAccountNumber,
        ///<summary>消費税率</summary>
        TaxRate,
    }
}