//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.ControlColorMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControlColorMasterService.IControlColorMaster")]
    public interface IControlColorMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlColorMaster/Get", ReplyAction="http://tempuri.org/IControlColorMaster/GetResponse")]
        Rac.VOne.Web.Models.ControlColorResult Get(string SessionKey, int CompanyId, int LoginuserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlColorMaster/Get", ReplyAction="http://tempuri.org/IControlColorMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ControlColorResult> GetAsync(string SessionKey, int CompanyId, int LoginuserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlColorMaster/GetItems", ReplyAction="http://tempuri.org/IControlColorMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.ControlColorsResult GetItems(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlColorMaster/GetItems", ReplyAction="http://tempuri.org/IControlColorMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ControlColorsResult> GetItemsAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlColorMaster/Save", ReplyAction="http://tempuri.org/IControlColorMaster/SaveResponse")]
        Rac.VOne.Web.Models.ControlColorResult Save(string SessionKey, Rac.VOne.Web.Models.ControlColor ControlColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlColorMaster/Save", ReplyAction="http://tempuri.org/IControlColorMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ControlColorResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.ControlColor ControlColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlColorMaster/Delete", ReplyAction="http://tempuri.org/IControlColorMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CompanyId, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlColorMaster/Delete", ReplyAction="http://tempuri.org/IControlColorMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CompanyId, int LoginUserId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlColorMasterChannel : Rac.VOne.Client.Screen.ControlColorMasterService.IControlColorMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlColorMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.ControlColorMasterService.IControlColorMaster>, Rac.VOne.Client.Screen.ControlColorMasterService.IControlColorMaster {
        
        public ControlColorMasterClient() {
        }
        
        public ControlColorMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlColorMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlColorMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlColorMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.ControlColorResult Get(string SessionKey, int CompanyId, int LoginuserId) {
            return base.Channel.Get(SessionKey, CompanyId, LoginuserId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ControlColorResult> GetAsync(string SessionKey, int CompanyId, int LoginuserId) {
            return base.Channel.GetAsync(SessionKey, CompanyId, LoginuserId);
        }
        
        public Rac.VOne.Web.Models.ControlColorsResult GetItems(string SessionKey, int CompanyId) {
            return base.Channel.GetItems(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ControlColorsResult> GetItemsAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.ControlColorResult Save(string SessionKey, Rac.VOne.Web.Models.ControlColor ControlColor) {
            return base.Channel.Save(SessionKey, ControlColor);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ControlColorResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.ControlColor ControlColor) {
            return base.Channel.SaveAsync(SessionKey, ControlColor);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CompanyId, int LoginUserId) {
            return base.Channel.Delete(SessionKey, CompanyId, LoginUserId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CompanyId, int LoginUserId) {
            return base.Channel.DeleteAsync(SessionKey, CompanyId, LoginUserId);
        }
    }
}
