//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.InputControlMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InputControlMasterService.IInputControlMaster")]
    public interface IInputControlMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInputControlMaster/Get", ReplyAction="http://tempuri.org/IInputControlMaster/GetResponse")]
        Rac.VOne.Web.Models.InputControlsResult Get(string SessionKey, int CompanyId, int LoginUserId, int InputGridTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInputControlMaster/Get", ReplyAction="http://tempuri.org/IInputControlMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.InputControlsResult> GetAsync(string SessionKey, int CompanyId, int LoginUserId, int InputGridTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInputControlMaster/Save", ReplyAction="http://tempuri.org/IInputControlMaster/SaveResponse")]
        Rac.VOne.Web.Models.InputControlsResult Save(string SessionKey, int CompanyId, int LoginUserId, int InputGridTypeId, Rac.VOne.Web.Models.InputControl[] InputControl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInputControlMaster/Save", ReplyAction="http://tempuri.org/IInputControlMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.InputControlsResult> SaveAsync(string SessionKey, int CompanyId, int LoginUserId, int InputGridTypeId, Rac.VOne.Web.Models.InputControl[] InputControl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInputControlMasterChannel : Rac.VOne.Client.Screen.InputControlMasterService.IInputControlMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InputControlMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.InputControlMasterService.IInputControlMaster>, Rac.VOne.Client.Screen.InputControlMasterService.IInputControlMaster {
        
        public InputControlMasterClient() {
        }
        
        public InputControlMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InputControlMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InputControlMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InputControlMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.InputControlsResult Get(string SessionKey, int CompanyId, int LoginUserId, int InputGridTypeId) {
            return base.Channel.Get(SessionKey, CompanyId, LoginUserId, InputGridTypeId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.InputControlsResult> GetAsync(string SessionKey, int CompanyId, int LoginUserId, int InputGridTypeId) {
            return base.Channel.GetAsync(SessionKey, CompanyId, LoginUserId, InputGridTypeId);
        }
        
        public Rac.VOne.Web.Models.InputControlsResult Save(string SessionKey, int CompanyId, int LoginUserId, int InputGridTypeId, Rac.VOne.Web.Models.InputControl[] InputControl) {
            return base.Channel.Save(SessionKey, CompanyId, LoginUserId, InputGridTypeId, InputControl);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.InputControlsResult> SaveAsync(string SessionKey, int CompanyId, int LoginUserId, int InputGridTypeId, Rac.VOne.Web.Models.InputControl[] InputControl) {
            return base.Channel.SaveAsync(SessionKey, CompanyId, LoginUserId, InputGridTypeId, InputControl);
        }
    }
}
