//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.ImporterSettingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImporterSettingService.IImporterSettingService")]
    public interface IImporterSettingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/GetHeader", ReplyAction="http://tempuri.org/IImporterSettingService/GetHeaderResponse")]
        Rac.VOne.Web.Models.ImporterSettingsResult GetHeader(string SessionKey, int CompanyId, int FormatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/GetHeader", ReplyAction="http://tempuri.org/IImporterSettingService/GetHeaderResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImporterSettingsResult> GetHeaderAsync(string SessionKey, int CompanyId, int FormatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/Save", ReplyAction="http://tempuri.org/IImporterSettingService/SaveResponse")]
        Rac.VOne.Web.Models.ImporterSettingAndDetailResult Save(string SessionKey, Rac.VOne.Web.Models.ImporterSetting ImpSetting, Rac.VOne.Web.Models.ImporterSettingDetail[] ImpSettingDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/Save", ReplyAction="http://tempuri.org/IImporterSettingService/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImporterSettingAndDetailResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.ImporterSetting ImpSetting, Rac.VOne.Web.Models.ImporterSettingDetail[] ImpSettingDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/GetHeaderByCode", ReplyAction="http://tempuri.org/IImporterSettingService/GetHeaderByCodeResponse")]
        Rac.VOne.Web.Models.ImporterSettingResult GetHeaderByCode(string SessionKey, int CompanyId, int FormatId, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/GetHeaderByCode", ReplyAction="http://tempuri.org/IImporterSettingService/GetHeaderByCodeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImporterSettingResult> GetHeaderByCodeAsync(string SessionKey, int CompanyId, int FormatId, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/GetDetailByCode", ReplyAction="http://tempuri.org/IImporterSettingService/GetDetailByCodeResponse")]
        Rac.VOne.Web.Models.ImporterSettingDetailsResult GetDetailByCode(string SessionKey, int CompanyId, int FormatId, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/GetDetailByCode", ReplyAction="http://tempuri.org/IImporterSettingService/GetDetailByCodeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImporterSettingDetailsResult> GetDetailByCodeAsync(string SessionKey, int CompanyId, int FormatId, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/GetDetailById", ReplyAction="http://tempuri.org/IImporterSettingService/GetDetailByIdResponse")]
        Rac.VOne.Web.Models.ImporterSettingDetailsResult GetDetailById(string SessionKey, int ImporterSettingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/GetDetailById", ReplyAction="http://tempuri.org/IImporterSettingService/GetDetailByIdResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImporterSettingDetailsResult> GetDetailByIdAsync(string SessionKey, int ImporterSettingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/Delete", ReplyAction="http://tempuri.org/IImporterSettingService/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int ImporterSettingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImporterSettingService/Delete", ReplyAction="http://tempuri.org/IImporterSettingService/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int ImporterSettingId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImporterSettingServiceChannel : Rac.VOne.Client.Screen.ImporterSettingService.IImporterSettingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImporterSettingServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.ImporterSettingService.IImporterSettingService>, Rac.VOne.Client.Screen.ImporterSettingService.IImporterSettingService {
        
        public ImporterSettingServiceClient() {
        }
        
        public ImporterSettingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImporterSettingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImporterSettingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImporterSettingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.ImporterSettingsResult GetHeader(string SessionKey, int CompanyId, int FormatId) {
            return base.Channel.GetHeader(SessionKey, CompanyId, FormatId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImporterSettingsResult> GetHeaderAsync(string SessionKey, int CompanyId, int FormatId) {
            return base.Channel.GetHeaderAsync(SessionKey, CompanyId, FormatId);
        }
        
        public Rac.VOne.Web.Models.ImporterSettingAndDetailResult Save(string SessionKey, Rac.VOne.Web.Models.ImporterSetting ImpSetting, Rac.VOne.Web.Models.ImporterSettingDetail[] ImpSettingDetail) {
            return base.Channel.Save(SessionKey, ImpSetting, ImpSettingDetail);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImporterSettingAndDetailResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.ImporterSetting ImpSetting, Rac.VOne.Web.Models.ImporterSettingDetail[] ImpSettingDetail) {
            return base.Channel.SaveAsync(SessionKey, ImpSetting, ImpSettingDetail);
        }
        
        public Rac.VOne.Web.Models.ImporterSettingResult GetHeaderByCode(string SessionKey, int CompanyId, int FormatId, string Code) {
            return base.Channel.GetHeaderByCode(SessionKey, CompanyId, FormatId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImporterSettingResult> GetHeaderByCodeAsync(string SessionKey, int CompanyId, int FormatId, string Code) {
            return base.Channel.GetHeaderByCodeAsync(SessionKey, CompanyId, FormatId, Code);
        }
        
        public Rac.VOne.Web.Models.ImporterSettingDetailsResult GetDetailByCode(string SessionKey, int CompanyId, int FormatId, string Code) {
            return base.Channel.GetDetailByCode(SessionKey, CompanyId, FormatId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImporterSettingDetailsResult> GetDetailByCodeAsync(string SessionKey, int CompanyId, int FormatId, string Code) {
            return base.Channel.GetDetailByCodeAsync(SessionKey, CompanyId, FormatId, Code);
        }
        
        public Rac.VOne.Web.Models.ImporterSettingDetailsResult GetDetailById(string SessionKey, int ImporterSettingId) {
            return base.Channel.GetDetailById(SessionKey, ImporterSettingId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImporterSettingDetailsResult> GetDetailByIdAsync(string SessionKey, int ImporterSettingId) {
            return base.Channel.GetDetailByIdAsync(SessionKey, ImporterSettingId);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int ImporterSettingId) {
            return base.Channel.Delete(SessionKey, ImporterSettingId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int ImporterSettingId) {
            return base.Channel.DeleteAsync(SessionKey, ImporterSettingId);
        }
    }
}
