//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.CollectionScheduleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CollectionScheduleService.ICollectionScheduleService")]
    public interface ICollectionScheduleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollectionScheduleService/Get", ReplyAction="http://tempuri.org/ICollectionScheduleService/GetResponse")]
        Rac.VOne.Web.Models.CollectionSchedulesResult Get(string SessionKey, Rac.VOne.Web.Models.CollectionScheduleSearch SearchOption, string connectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICollectionScheduleService/Get", ReplyAction="http://tempuri.org/ICollectionScheduleService/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CollectionSchedulesResult> GetAsync(string SessionKey, Rac.VOne.Web.Models.CollectionScheduleSearch SearchOption, string connectionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICollectionScheduleServiceChannel : Rac.VOne.Client.Screen.CollectionScheduleService.ICollectionScheduleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CollectionScheduleServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.CollectionScheduleService.ICollectionScheduleService>, Rac.VOne.Client.Screen.CollectionScheduleService.ICollectionScheduleService {
        
        public CollectionScheduleServiceClient() {
        }
        
        public CollectionScheduleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CollectionScheduleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollectionScheduleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollectionScheduleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.CollectionSchedulesResult Get(string SessionKey, Rac.VOne.Web.Models.CollectionScheduleSearch SearchOption, string connectionId) {
            return base.Channel.Get(SessionKey, SearchOption, connectionId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CollectionSchedulesResult> GetAsync(string SessionKey, Rac.VOne.Web.Models.CollectionScheduleSearch SearchOption, string connectionId) {
            return base.Channel.GetAsync(SessionKey, SearchOption, connectionId);
        }
    }
}
