//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.CustomerPaymentContractMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerPaymentContractMasterService.ICustomerPaymentContractMaster")]
    public interface ICustomerPaymentContractMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerPaymentContractMaster/Exist", ReplyAction="http://tempuri.org/ICustomerPaymentContractMaster/ExistResponse")]
        Rac.VOne.Web.Models.ExistResult Exist(int Id, string SessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerPaymentContractMaster/Exist", ReplyAction="http://tempuri.org/ICustomerPaymentContractMaster/ExistResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistAsync(int Id, string SessionKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerPaymentContractMasterChannel : Rac.VOne.Client.Screen.CustomerPaymentContractMasterService.ICustomerPaymentContractMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerPaymentContractMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.CustomerPaymentContractMasterService.ICustomerPaymentContractMaster>, Rac.VOne.Client.Screen.CustomerPaymentContractMasterService.ICustomerPaymentContractMaster {
        
        public CustomerPaymentContractMasterClient() {
        }
        
        public CustomerPaymentContractMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerPaymentContractMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerPaymentContractMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerPaymentContractMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.ExistResult Exist(int Id, string SessionKey) {
            return base.Channel.Exist(Id, SessionKey);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistAsync(int Id, string SessionKey) {
            return base.Channel.ExistAsync(Id, SessionKey);
        }
    }
}
