
export enum IMPORTER_BILLING_FIELDS {
        ///<summary>会社コード</summary>
        CompanyCode = 1,        
        ///<summary>得意先コード</summary>
        CustomerCode,
        ///<summary>請求日</summary>
        BilledAt,
        ///<summary>請求金額</summary>
        BillingAmount,
        ///<summary>消費税</summary>
        TaxAmount,
        ///<summary>入金予定日</summary>
        DueAt,
        ///<summary>請求部門</summary>
        DepartmentCode,
        ///<summary>債権科目</summary>
        DebitAccountTitleCode,
        ///<summary>売上日</summary>
        SalesAt,
        ///<summary>請求書番号</summary>
        InvoiceCode,
        ///<summary>請求締日</summary>
        ClosingAt,
        ///<summary>担当者</summary>
        StaffCode,
        ///<summary>備考</summary>
        Note1,
        ///<summary>請求区分</summary>
        BillingCategoryCode,
        ///<summary>回収区分</summary>
        CollectCategoryCode,
        ///<summary>数量</summary>
        Quantity,
        ///<summary>単位</summary>
        UnitSymbol,
        ///<summary>単価</summary>
        UnitPrice,
        ///<summary>契約番号</summary>
        ContractNumber,
        ///<summary>金額（抜）</summary>
        Price,
        ///<summary>税区</summary>
        TaxClassId,
        ///<summary>備考2</summary>
        Note2,
        ///<summary>備考3</summary>
        Note3,
        ///<summary>備考4</summary>
        Note4,
        ///<summary>備考5</summary>
        Note5,
        ///<summary>備考6</summary>
        Note6,
        ///<summary>備考7</summary>
        Note7,
        ///<summary>備考8</summary>
        Note8,
        ///<summary>得意先名称</summary>
        CustomerName,
        ///<summary>得意先カナ</summary>
        CustomerKana,
        ///<summary>照合番号</summary>
        CollationKey,
        ///<summary>歩引利用</summary>
        UseDiscount,
        ///<summary>通貨コード</summary>
        CurrencyCode,
        ///<summary>銀行コード</summary>
        ExclusiveBankCode,
        ///<summary>支店コード</summary>
        ExclusiveBranchCode,
        ///<summary>仮想支店コード</summary>
        ExclusiveVirtualBranchCode,
        ///<summary>仮想口座番号</summary>
        ExclusiveAccountNumber,
        ///<summary>消費税率</summary>
        TaxRate,
}

export enum IMPORTER_RECEIPT_FIELDS {
        ///<summary>得意先コード</summary>
        CustomerCode = 1,
        ///<summary>入金日</summary>
        RecordedAt,
        ///<summary>入金区分</summary>
        ReceiptCategoryCode,
        ///<summary>入金額</summary>
        ReceiptAmount,
        ///<summary>期日</summary>
        DueAt,
        ///<summary>備考</summary>
        Note1,
        ///<summary>入金部門コード</summary>
        SectionCode,
        ///<summary>通貨コード</summary>
        CurrencyCode,
        ///<summary>備考2</summary>
        Note2,
        ///<summary>備考3</summary>
        Note3,
        ///<summary>備考4</summary>
        Note4,
        ///<summary>振込依頼人名</summary>
        PayerName,
        ///<summary>銀行コード</summary>
        BankCode,
        ///<summary>銀行名</summary>
        BankName,
        ///<summary>支店コード</summary>
        BranchCode,
        ///<summary>支店名</summary>
        BranchName,
        ///<summary>預金種別</summary>
        AccountTypeId,
        ///<summary>口座番号</summary>
        AccountNumber,
        ///<summary>口座名</summary>
        AccountName,
        ///<summary>仕向銀行</summary>
        SourceBankName,
        ///<summary>仕向支店</summary>
        SourceBranchName,
        ///<summary>手形番号</summary>
        BillNumber,
        ///<summary>券面銀行コード</summary>
        BillBankCode,
        ///<summary>券面支店コード</summary>
        BillBranchCode,
        ///<summary>振出日</summary>
        BillDrawAt,
        ///<summary>振出人</summary>
        BillDrawer,
}


export enum IMPORTER_CUSTOMER_FIELDS
{
    ///<summary>会社コード</summary>
    CompanyCode = 1,
    ///<summary>得意先コード</summary>
    CustomerCode,
    ///<summary>得意先名</summary>
    CustomerName,
    ///<summary>得意先名カナ</summary>
    CustomerKana,
    ///<summary>専用銀行コード</summary>
    ExclusiveBankCode,
    ///<summary>専用銀行名</summary>
    ExclusiveBankName,
    ///<summary>専用支店コード</summary>
    ExclusiveBranchCode,
    ///<summary>仮想支店名</summary>
    ExclusiveBranchName,
    ///<summary>専用入金口座番号</summary>
    ExclusiveAccountNumber,
    ///<summary>預金種別</summary>
    ExclusiveAccountTypeId,
    ///<summary>手数料負担区分</summary>
    ShareTransferFee,
    ///<summary>与信限度額</summary>
    CreditLimit,
    ///<summary>締日</summary>
    ClosingDay,
    ///<summary>回収方法</summary>
    CollectCategoryId,
    ///<summary>回収予定（月）</summary>
    CollectOffsetMonth,
    ///<summary>回収予定（日）</summary>
    CollectOffsetDay,
    /// <summary>回収予定（都度請求）</summary>
    CollectOffsetDayPerBilling,
    ///<summary>営業担当者</summary>
    StaffCode,
    ///<summary>債権代表者フラグ</summary>
    IsParent,
    ///<summary>郵便番号</summary>
    PostalCode,
    ///<summary>住所1</summary>
    Address1,
    ///<summary>住所2</summary>
    Address2,
    ///<summary>TEL番号</summary>
    Tel,
    ///<summary>FAX番号</summary>
    Fax,
    ///<summary>相手先担当者名</summary>
    CustomerStaffName,
    ///<summary>備考</summary>
    Note,
    ///<summary>手数料自動学習</summary>
    UseFeeLearning,
    ///<summary>回収サイト</summary>
    SightOfBill,
    ///<summary>電子手形用企業コード</summary>
    DensaiCode,
    ///<summary>信用調査用企業コード</summary>
    CreditCode,
    ///<summary>与信ランク</summary>
    CreditRank,
    ///<summary>口座振替用銀行コード</summary>
    TransferBankCode,
    ///<summary>口座振替用銀行名</summary>
    TransferBankName,
    ///<summary>口座振替用支店コード</summary>
    TransferBranchCode,
    ///<summary>口座振替用支店名</summary>
    TransferBranchName,
    ///<summary>口座振替用口座番号</summary>
    TransferAccountNumber,
    ///<summary>口座振替用預金種目</summary>
    TransferAccountTypeId,
    ///<summary>口座振替用顧客コード</summary>
    TransferCustomerCode,
    ///<summary>口座振替用新規コード</summary>
    TransferNewCode,
    ///<summary>口座振替用預金者名</summary>
    TransferAccountName,
    ///<summary>約定金額</summary>
    ThresholdValue,
    ///<summary>約定金額未満</summary>
    LessThanCollectCategoryId,
    ///<summary>約定金額以上1</summary>
    GreaterThanCollectCategoryId1,
    ///<summary>分割1</summary>
    GreaterThanRate1,
    ///<summary>端数1</summary>
    GreaterThanRoundingMode1,
    ///<summary>回収サイト1</summary>
    GreaterThanSightOfBill1,
    ///<summary>約定金額以上2</summary>
    GreaterThanCollectCategoryId2,
    ///<summary>分割2</summary>
    GreaterThanRate2,
    ///<summary>端数2</summary>
    GreaterThanRoundingMode2,
    ///<summary>回収サイト2</summary>
    GreaterThanSightOfBill2,
    ///<summary>約定金額以上3</summary>
    GreaterThanCollectCategoryId3,
    ///<summary>分割3</summary>
    GreaterThanRate3,
    ///<summary>端数3</summary>
    GreaterThanRoundingMode3,
    ///<summary>回収サイト3</summary>
    GreaterThanSightOfBill3,
    ///<summary>カナ自動学習</summary>
    UseKanaLearning,
    ///<summary>休業日の設定</summary>
    HolidayFlag,
    ///<summary>手数料誤差利用</summary>
    UseFeeTolerance,
    ///<summary>一括消込対象外（個別消込優先）</summary>
    PrioritizeMatchingIndividually,
    ///<summary>照合番号</summary>
    CollationKey,
    ///<summary>請求書発行対象外</summary>
    ExcludeInvoicePublish,
    ///<summary>督促状発行対象外</summary>
    ExcludeReminderPublish,
    ///<summary>相手先部署</summary>
    DestinationDepartmentName,
    ///<summary>敬称</summary>
    Honorific,
}

export enum IMPORTER_PAYMENT_SCHEDULE_FIELDS
{
    ///<summary>入金予定額</summary>
    ReceiptAmount = 1,
    ///<summary>会社コード</summary>
    CompanyCode,
    ///<summary>債権代表者コード</summary>
    ParentCustomerCode,
    ///<summary>得意先コード</summary>
    CustomerCode,
    ///<summary>請求日</summary>
    BilledAt,
    ///<summary>請求金額</summary>
    BillingAmount,
    ///<summary>消費税</summary>
    TaxAmount,
    ///<summary>入金予定日</summary>
    DueAt,
    ///<summary>請求部門</summary>
    DepartmentCode,
    ///<summary>債権科目</summary>
    DebitAccountTitleCode,
    ///<summary>売上日</summary>
    SalesAt,
    ///<summary>請求書番号</summary>
    InvoiceCode,
    ///<summary>請求締日</summary>
    ClosingAt,
    ///<summary>担当者</summary>
    StaffCode,
    ///<summary>備考</summary>
    Note1,
    ///<summary>請求区分</summary>
    BillingCategoryCode,
    ///<summary>備考2</summary>
    Note2,
    ///<summary>備考3</summary>
    Note3,
    ///<summary>備考4</summary>
    Note4,
    ///<summary>備考5</summary>
    Note5,
    ///<summary>備考6</summary>
    Note6,
    ///<summary>備考7</summary>
    Note7,
    ///<summary>備考8</summary>
    Note8,
    ///<summary>通貨コード</summary>
    CurrencyCode,
    ///<summary>入金予定キー</summary>
    ScheduledPaymentKey,
}