//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.PasswordPolicyMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PasswordPolicyMasterService.IPasswordPolicyMaster")]
    public interface IPasswordPolicyMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordPolicyMaster/Get", ReplyAction="http://tempuri.org/IPasswordPolicyMaster/GetResponse")]
        Rac.VOne.Web.Models.PasswordPolicyResult Get(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordPolicyMaster/Get", ReplyAction="http://tempuri.org/IPasswordPolicyMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.PasswordPolicyResult> GetAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordPolicyMaster/Save", ReplyAction="http://tempuri.org/IPasswordPolicyMaster/SaveResponse")]
        Rac.VOne.Web.Models.PasswordPolicyResult Save(string SessionKey, Rac.VOne.Web.Models.PasswordPolicy PasswordPolicy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPasswordPolicyMaster/Save", ReplyAction="http://tempuri.org/IPasswordPolicyMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.PasswordPolicyResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.PasswordPolicy PasswordPolicy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPasswordPolicyMasterChannel : Rac.VOne.Client.Screen.PasswordPolicyMasterService.IPasswordPolicyMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PasswordPolicyMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.PasswordPolicyMasterService.IPasswordPolicyMaster>, Rac.VOne.Client.Screen.PasswordPolicyMasterService.IPasswordPolicyMaster {
        
        public PasswordPolicyMasterClient() {
        }
        
        public PasswordPolicyMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PasswordPolicyMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordPolicyMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordPolicyMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.PasswordPolicyResult Get(string SessionKey, int CompanyId) {
            return base.Channel.Get(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.PasswordPolicyResult> GetAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.PasswordPolicyResult Save(string SessionKey, Rac.VOne.Web.Models.PasswordPolicy PasswordPolicy) {
            return base.Channel.Save(SessionKey, PasswordPolicy);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.PasswordPolicyResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.PasswordPolicy PasswordPolicy) {
            return base.Channel.SaveAsync(SessionKey, PasswordPolicy);
        }
    }
}
