//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.KanaHistoryPaymentAgencyMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KanaHistoryPaymentAgencyMasterService.IKanaHistoryPaymentAgencyMaster")]
    public interface IKanaHistoryPaymentAgencyMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/GetList", ReplyAction="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/GetListResponse")]
        Rac.VOne.Web.Models.KanaHistoryPaymentAgencysResult GetList(string SessionKey, int CompanyId, string PayerName, string PaymentAgencyCodeFrom, string PaymentAgencyCodeTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/GetList", ReplyAction="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/GetListResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.KanaHistoryPaymentAgencysResult> GetListAsync(string SessionKey, int CompanyId, string PayerName, string PaymentAgencyCodeFrom, string PaymentAgencyCodeTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/Delete", ReplyAction="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CompanyId, string PayerName, string SourceBankName, string SourceBranchName, int PaymentAgencyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/Delete", ReplyAction="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CompanyId, string PayerName, string SourceBankName, string SourceBranchName, int PaymentAgencyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/Import", ReplyAction="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/ImportResponse")]
        Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] InsertList, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] UpdateList, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/Import", ReplyAction="http://tempuri.org/IKanaHistoryPaymentAgencyMaster/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] InsertList, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] UpdateList, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] DeleteList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKanaHistoryPaymentAgencyMasterChannel : Rac.VOne.Client.Screen.KanaHistoryPaymentAgencyMasterService.IKanaHistoryPaymentAgencyMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KanaHistoryPaymentAgencyMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.KanaHistoryPaymentAgencyMasterService.IKanaHistoryPaymentAgencyMaster>, Rac.VOne.Client.Screen.KanaHistoryPaymentAgencyMasterService.IKanaHistoryPaymentAgencyMaster {
        
        public KanaHistoryPaymentAgencyMasterClient() {
        }
        
        public KanaHistoryPaymentAgencyMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KanaHistoryPaymentAgencyMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KanaHistoryPaymentAgencyMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KanaHistoryPaymentAgencyMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.KanaHistoryPaymentAgencysResult GetList(string SessionKey, int CompanyId, string PayerName, string PaymentAgencyCodeFrom, string PaymentAgencyCodeTo) {
            return base.Channel.GetList(SessionKey, CompanyId, PayerName, PaymentAgencyCodeFrom, PaymentAgencyCodeTo);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.KanaHistoryPaymentAgencysResult> GetListAsync(string SessionKey, int CompanyId, string PayerName, string PaymentAgencyCodeFrom, string PaymentAgencyCodeTo) {
            return base.Channel.GetListAsync(SessionKey, CompanyId, PayerName, PaymentAgencyCodeFrom, PaymentAgencyCodeTo);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CompanyId, string PayerName, string SourceBankName, string SourceBranchName, int PaymentAgencyId) {
            return base.Channel.Delete(SessionKey, CompanyId, PayerName, SourceBankName, SourceBranchName, PaymentAgencyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CompanyId, string PayerName, string SourceBankName, string SourceBranchName, int PaymentAgencyId) {
            return base.Channel.DeleteAsync(SessionKey, CompanyId, PayerName, SourceBankName, SourceBranchName, PaymentAgencyId);
        }
        
        public Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] InsertList, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] UpdateList, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] DeleteList) {
            return base.Channel.Import(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] InsertList, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] UpdateList, Rac.VOne.Web.Models.KanaHistoryPaymentAgency[] DeleteList) {
            return base.Channel.ImportAsync(SessionKey, InsertList, UpdateList, DeleteList);
        }
    }
}
