//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.BillingBalanceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BillingBalanceService.IBillingBalanceService")]
    public interface IBillingBalanceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingBalanceService/GetLastCarryOverAt", ReplyAction="http://tempuri.org/IBillingBalanceService/GetLastCarryOverAtResponse")]
        Rac.VOne.Web.Models.BillingBalanceResult GetLastCarryOverAt(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingBalanceService/GetLastCarryOverAt", ReplyAction="http://tempuri.org/IBillingBalanceService/GetLastCarryOverAtResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingBalanceResult> GetLastCarryOverAtAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingBalanceService/Save", ReplyAction="http://tempuri.org/IBillingBalanceService/SaveResponse")]
        Rac.VOne.Web.Models.BillingBalancesResult Save(string SessionKey, int CompanyId, System.DateTime CarryOverAt, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingBalanceService/Save", ReplyAction="http://tempuri.org/IBillingBalanceService/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingBalancesResult> SaveAsync(string SessionKey, int CompanyId, System.DateTime CarryOverAt, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingBalanceService/Cancel", ReplyAction="http://tempuri.org/IBillingBalanceService/CancelResponse")]
        Rac.VOne.Web.Models.CountResult Cancel(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingBalanceService/Cancel", ReplyAction="http://tempuri.org/IBillingBalanceService/CancelResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> CancelAsync(string SessionKey, int CompanyId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBillingBalanceServiceChannel : Rac.VOne.Client.Screen.BillingBalanceService.IBillingBalanceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillingBalanceServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.BillingBalanceService.IBillingBalanceService>, Rac.VOne.Client.Screen.BillingBalanceService.IBillingBalanceService {
        
        public BillingBalanceServiceClient() {
        }
        
        public BillingBalanceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillingBalanceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillingBalanceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillingBalanceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.BillingBalanceResult GetLastCarryOverAt(string SessionKey, int CompanyId) {
            return base.Channel.GetLastCarryOverAt(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingBalanceResult> GetLastCarryOverAtAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetLastCarryOverAtAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.BillingBalancesResult Save(string SessionKey, int CompanyId, System.DateTime CarryOverAt, int LoginUserId) {
            return base.Channel.Save(SessionKey, CompanyId, CarryOverAt, LoginUserId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingBalancesResult> SaveAsync(string SessionKey, int CompanyId, System.DateTime CarryOverAt, int LoginUserId) {
            return base.Channel.SaveAsync(SessionKey, CompanyId, CarryOverAt, LoginUserId);
        }
        
        public Rac.VOne.Web.Models.CountResult Cancel(string SessionKey, int CompanyId) {
            return base.Channel.Cancel(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> CancelAsync(string SessionKey, int CompanyId) {
            return base.Channel.CancelAsync(SessionKey, CompanyId);
        }
    }
}
