//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Common.LogsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogsService.ILogsService")]
    public interface ILogsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogsService/SaveErrorLog", ReplyAction="http://tempuri.org/ILogsService/SaveErrorLogResponse")]
        bool SaveErrorLog(Rac.VOne.Web.Models.Logs log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogsService/SaveErrorLog", ReplyAction="http://tempuri.org/ILogsService/SaveErrorLogResponse")]
        System.Threading.Tasks.Task<bool> SaveErrorLogAsync(Rac.VOne.Web.Models.Logs log);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogsServiceChannel : Rac.VOne.Client.Common.LogsService.ILogsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogsServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Common.LogsService.ILogsService>, Rac.VOne.Client.Common.LogsService.ILogsService {
        
        public LogsServiceClient() {
        }
        
        public LogsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveErrorLog(Rac.VOne.Web.Models.Logs log) {
            return base.Channel.SaveErrorLog(log);
        }
        
        public System.Threading.Tasks.Task<bool> SaveErrorLogAsync(Rac.VOne.Web.Models.Logs log) {
            return base.Channel.SaveErrorLogAsync(log);
        }
    }
}
