//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.GeneralSettingMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeneralSettingMasterService.IGeneralSettingMaster")]
    public interface IGeneralSettingMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralSettingMaster/GetItems", ReplyAction="http://tempuri.org/IGeneralSettingMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.GeneralSettingsResult GetItems(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralSettingMaster/GetItems", ReplyAction="http://tempuri.org/IGeneralSettingMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.GeneralSettingsResult> GetItemsAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralSettingMaster/Save", ReplyAction="http://tempuri.org/IGeneralSettingMaster/SaveResponse")]
        Rac.VOne.Web.Models.GeneralSettingResult Save(string SessionKey, Rac.VOne.Web.Models.GeneralSetting Generalsetting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralSettingMaster/Save", ReplyAction="http://tempuri.org/IGeneralSettingMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.GeneralSettingResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.GeneralSetting Generalsetting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralSettingMaster/GetByCode", ReplyAction="http://tempuri.org/IGeneralSettingMaster/GetByCodeResponse")]
        Rac.VOne.Web.Models.GeneralSettingResult GetByCode(string SessionKey, int CompanyId, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralSettingMaster/GetByCode", ReplyAction="http://tempuri.org/IGeneralSettingMaster/GetByCodeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.GeneralSettingResult> GetByCodeAsync(string SessionKey, int CompanyId, string Code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralSettingMasterChannel : Rac.VOne.Client.Screen.GeneralSettingMasterService.IGeneralSettingMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralSettingMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.GeneralSettingMasterService.IGeneralSettingMaster>, Rac.VOne.Client.Screen.GeneralSettingMasterService.IGeneralSettingMaster {
        
        public GeneralSettingMasterClient() {
        }
        
        public GeneralSettingMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneralSettingMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralSettingMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralSettingMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.GeneralSettingsResult GetItems(string SessionKey, int CompanyId) {
            return base.Channel.GetItems(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.GeneralSettingsResult> GetItemsAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.GeneralSettingResult Save(string SessionKey, Rac.VOne.Web.Models.GeneralSetting Generalsetting) {
            return base.Channel.Save(SessionKey, Generalsetting);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.GeneralSettingResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.GeneralSetting Generalsetting) {
            return base.Channel.SaveAsync(SessionKey, Generalsetting);
        }
        
        public Rac.VOne.Web.Models.GeneralSettingResult GetByCode(string SessionKey, int CompanyId, string Code) {
            return base.Channel.GetByCode(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.GeneralSettingResult> GetByCodeAsync(string SessionKey, int CompanyId, string Code) {
            return base.Channel.GetByCodeAsync(SessionKey, CompanyId, Code);
        }
    }
}
