//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.ReceiptExcludeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReceiptExcludeService.IReceiptExcludeService")]
    public interface IReceiptExcludeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiptExcludeService/ExistExcludeCategory", ReplyAction="http://tempuri.org/IReceiptExcludeService/ExistExcludeCategoryResponse")]
        Rac.VOne.Web.Models.ExistResult ExistExcludeCategory(string SessionKey, int CategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiptExcludeService/ExistExcludeCategory", ReplyAction="http://tempuri.org/IReceiptExcludeService/ExistExcludeCategoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistExcludeCategoryAsync(string SessionKey, int CategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiptExcludeService/GetByReceiptId", ReplyAction="http://tempuri.org/IReceiptExcludeService/GetByReceiptIdResponse")]
        Rac.VOne.Web.Models.ReceiptExcludesResult GetByReceiptId(string SessionKey, long ReceiptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiptExcludeService/GetByReceiptId", ReplyAction="http://tempuri.org/IReceiptExcludeService/GetByReceiptIdResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReceiptExcludesResult> GetByReceiptIdAsync(string SessionKey, long ReceiptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiptExcludeService/GetByIds", ReplyAction="http://tempuri.org/IReceiptExcludeService/GetByIdsResponse")]
        Rac.VOne.Web.Models.ReceiptExcludesResult GetByIds(string SessionKey, long[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiptExcludeService/GetByIds", ReplyAction="http://tempuri.org/IReceiptExcludeService/GetByIdsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReceiptExcludesResult> GetByIdsAsync(string SessionKey, long[] ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceiptExcludeServiceChannel : Rac.VOne.Client.Screen.ReceiptExcludeService.IReceiptExcludeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiptExcludeServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.ReceiptExcludeService.IReceiptExcludeService>, Rac.VOne.Client.Screen.ReceiptExcludeService.IReceiptExcludeService {
        
        public ReceiptExcludeServiceClient() {
        }
        
        public ReceiptExcludeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiptExcludeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiptExcludeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiptExcludeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistExcludeCategory(string SessionKey, int CategoryId) {
            return base.Channel.ExistExcludeCategory(SessionKey, CategoryId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistExcludeCategoryAsync(string SessionKey, int CategoryId) {
            return base.Channel.ExistExcludeCategoryAsync(SessionKey, CategoryId);
        }
        
        public Rac.VOne.Web.Models.ReceiptExcludesResult GetByReceiptId(string SessionKey, long ReceiptId) {
            return base.Channel.GetByReceiptId(SessionKey, ReceiptId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReceiptExcludesResult> GetByReceiptIdAsync(string SessionKey, long ReceiptId) {
            return base.Channel.GetByReceiptIdAsync(SessionKey, ReceiptId);
        }
        
        public Rac.VOne.Web.Models.ReceiptExcludesResult GetByIds(string SessionKey, long[] ids) {
            return base.Channel.GetByIds(SessionKey, ids);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReceiptExcludesResult> GetByIdsAsync(string SessionKey, long[] ids) {
            return base.Channel.GetByIdsAsync(SessionKey, ids);
        }
    }
}
