//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.HatarakuDBJournalizingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HatarakuDBJournalizingService.IHatarakuDBJournalizingService")]
    public interface IHatarakuDBJournalizingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHatarakuDBJournalizingService/GetSummary", ReplyAction="http://tempuri.org/IHatarakuDBJournalizingService/GetSummaryResponse")]
        Rac.VOne.Web.Models.JournalizingSummariesResult GetSummary(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHatarakuDBJournalizingService/GetSummary", ReplyAction="http://tempuri.org/IHatarakuDBJournalizingService/GetSummaryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.JournalizingSummariesResult> GetSummaryAsync(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHatarakuDBJournalizingService/Extract", ReplyAction="http://tempuri.org/IHatarakuDBJournalizingService/ExtractResponse")]
        Rac.VOne.Web.Models.HatarakuDBDataResult Extract(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHatarakuDBJournalizingService/Extract", ReplyAction="http://tempuri.org/IHatarakuDBJournalizingService/ExtractResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.HatarakuDBDataResult> ExtractAsync(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHatarakuDBJournalizingService/Update", ReplyAction="http://tempuri.org/IHatarakuDBJournalizingService/UpdateResponse")]
        Rac.VOne.Web.Models.CountResult Update(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHatarakuDBJournalizingService/Update", ReplyAction="http://tempuri.org/IHatarakuDBJournalizingService/UpdateResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> UpdateAsync(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHatarakuDBJournalizingService/Cancel", ReplyAction="http://tempuri.org/IHatarakuDBJournalizingService/CancelResponse")]
        Rac.VOne.Web.Models.CountResult Cancel(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHatarakuDBJournalizingService/Cancel", ReplyAction="http://tempuri.org/IHatarakuDBJournalizingService/CancelResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> CancelAsync(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHatarakuDBJournalizingServiceChannel : Rac.VOne.Client.Screen.HatarakuDBJournalizingService.IHatarakuDBJournalizingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HatarakuDBJournalizingServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.HatarakuDBJournalizingService.IHatarakuDBJournalizingService>, Rac.VOne.Client.Screen.HatarakuDBJournalizingService.IHatarakuDBJournalizingService {
        
        public HatarakuDBJournalizingServiceClient() {
        }
        
        public HatarakuDBJournalizingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HatarakuDBJournalizingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HatarakuDBJournalizingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HatarakuDBJournalizingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.JournalizingSummariesResult GetSummary(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option) {
            return base.Channel.GetSummary(SessionKey, option);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.JournalizingSummariesResult> GetSummaryAsync(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option) {
            return base.Channel.GetSummaryAsync(SessionKey, option);
        }
        
        public Rac.VOne.Web.Models.HatarakuDBDataResult Extract(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option) {
            return base.Channel.Extract(SessionKey, option);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.HatarakuDBDataResult> ExtractAsync(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option) {
            return base.Channel.ExtractAsync(SessionKey, option);
        }
        
        public Rac.VOne.Web.Models.CountResult Update(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option) {
            return base.Channel.Update(SessionKey, option);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> UpdateAsync(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option) {
            return base.Channel.UpdateAsync(SessionKey, option);
        }
        
        public Rac.VOne.Web.Models.CountResult Cancel(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option) {
            return base.Channel.Cancel(SessionKey, option);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> CancelAsync(string SessionKey, Rac.VOne.Web.Models.JournalizingOption option) {
            return base.Channel.CancelAsync(SessionKey, option);
        }
    }
}
