export class Billing {
    public id: number;
    public companyId: number;
    public currencyId: number;
    public customerId: number;
    public departmentId: number;
    public staffId: number;
    public billingCategoryId: number;
    public inputType: number;
    public billingInputTypeId: number;
    public billedAt: string;
    public closingAt: string;
    public salesAt: string;
    public dueAt: string;
    public billingAmount: number;
    public taxAmount: number;
    public assignmentAmount: number;
    public remainAmount: number;
    public targetAmount: number;
    public offsetAmount: number;
    public assignmentFlag: number;
    public approved: number;
    public collectCategoryId: number;
    public originalCollectCategoryId: number | null;
    public debitAccountTitleId: number | null;
    public creditAccountTitleId: number | null;
    public originalDueAt: string | null;
    public outputAt: string | null;
    public publishAt: string | null;
    public invoiceCode: string | null;
    public taxClassId: number;
    public note1: string | null;
    public note2: string | null;
    public note3: string | null;
    public note4: string | null;
    public note5: string | null;
    public note6: string | null;
    public note7: string | null;
    public note8: string | null;
    public deleteAt: string | null;
    public requestDate: string | null;
    public resultCode: number | null;
    public transferOriginalDueAt: string | null;
    public scheduledPaymentKey: string | null;
    public quantity: number | null;
    public unitPrice: number | null;
    public unitSymbol: string | null;
    public price: number | null;
    public createBy: number;
    public createAt: string;
    public updateBy: number;
    public updateAt: string;
    public billingInputId: number | null;
    public billingDueAt: string;
    public destinationId: number | null;
    public currencyCode: string | null;
    public customerCode: string | null;
    public customerName: string | null;
    public customerKana: string | null;
    public departmentCode: string | null;
    public departmentName: string | null;
    public staffName: string | null;
    public staffCode: string | null;
    public memo: string | null;
    public billingCategoryCode: string | null;
    public billingCategoryName: string | null;
    public collectCategoryCode: string | null;
    public collectCategoryName: string | null;
    public loginUserCode: string | null;
    public loginUserName: string | null;
    public contractNumber: string | null;
    public confirm: number;
    public billingDiscountId: number | null;
    public discountAmount: number;
    public discountAmount1: number;
    public discountAmount2: number;
    public discountAmount3: number;
    public discountAmount4: number;
    public discountAmount5: number;
    public billingId: number;
    public parentCustomerId: number;
    public parentCustomerCode: string | null;
    public parentCustomerName: string | null;
    public companyCode: string | null;
    public accountTitleCode: string | null;
    public paymentAmount: number;
    public categoryCodeAndName: string | null;
    public orgCategoryCodeAndName: string | null;
    public modifiedDueAt: string | null;
    public firstRecordedAt: string | null;
    public lastRecordedAt: string | null;
    public billingInputPublishAt: string | null;
    public bankTransferFee: number;
    public taxDifference: number;
    public isParent: number;
    public billingDivisionContract: number;
    public useDiscount: Boolean;
    public currencyPrecision: number;
    public useLongTermAdvancedReceived: number;
    public accountTransferLogId: number;
    public periodicBillingSettingId: number;
    public displayOrder: number;
}

