export class BillingInvoiceDetailForPrint {
    public billingInputId: number;
    public invoiceCode: string | null;
    public billedAt: string;
    public closingAt: string;
    public salesAt: string | null;
    public dueAt: string;
    public billingAmount: number;
    public taxAmount: number;
    public taxExcludedPrice: number;
    public remainAmount: number;
    public taxClassName: string | null;
    public note1: string | null;
    public note2: string | null;
    public quantity: number | null;
    public unitPrice: number | null;
    public unitSymbol: string | null;
    public staffName: string | null;
    public displayStaff: number;
    public tel: string | null;
    public fax: string | null;
    public customerPostalCode: string | null;
    public customerAddress1: string | null;
    public customerAddress2: string | null;
    public customerCode: string | null;
    public customerName: string | null;
    public destinationId: number | null;
    public destinationName: string | null;
    public destinationPostalCode: string | null;
    public destinationAddress1: string | null;
    public destinationAddress2: string | null;
    public destinationDepartmentName: string | null;
    public destinationAddressee: string | null;
    public destinationHonorific: string | null;
    public title: string | null;
    public greeting: string | null;
    public dueDateComment: string | null;
    public dueDateFormat: number;
    public transferFeeComment: string | null;
    public receiveAccountId1: number;
    public receiveAccountId2: number;
    public receiveAccountId3: number;
    public receiveAccount1: string | null;
    public receiveAccount2: string | null;
    public receiveAccount3: string | null;
    public bankAccountName: string | null;
    public exclusiveAccount: string | null;
    public detailCount: number;
    public shareTransferFee: number;
    public customerDestinationDepartmentName: string | null;
    public customerStaffName: string | null;
    public customerHonorific: string | null;
}

