export class BillingImport {
    public companyId: number;
    public currencyCode: string | null;
    public customerCode: string | null;
    public departmentCode: string | null;
    public departmentId: number;
    public staffCode: string | null;
    public staffId: number;
    public billingCategoryCode: string | null;
    public inputType: string | null;
    public collectCategoryCode: string | null;
    public collectCategoryId: number;
    public billedAt: string;
    public closingAt: string;
    public salesAt: string;
    public dueAt: string;
    public billingAmount: number;
    public taxAmount: number;
    public debitAccountTitleCode: string | null;
    public invoiceCode: string | null;
    public taxClassId: number;
    public note1: string | null;
    public note2: string | null;
    public note3: string | null;
    public note4: string | null;
    public note5: string | null;
    public note6: string | null;
    public note7: string | null;
    public note8: string | null;
    public price: number;
    public exclusiveBankCode: string | null;
    public exclusiveBranchCode: string | null;
    public exclusiveVirtualBranchCode: string | null;
    public exclusiveAccountNumber: string | null;
    public billingId: number | null;
    public discountType: number;
    public discountAmount: number;
    public assignmentFlag: number;
    public autoCreationCustomerFlag: number;
    public contractNumber: string | null;
    public companyCode: string | null;
    public customerName: string | null;
    public customerKana: string | null;
    public collationKey: string | null;
    public useDiscount: number;
    public useLongTermAdvanceReceived: number;
    public registerContractInAdvance: number;
    public taxRate: number;
    public billedAtForPrint: string | null;
    public closingAtForPrint: string | null;
    public dueAtForPrint: string | null;
    public saleAtForPrint: string | null;
    public billingAmountForPrint: string | null;
    public taxAmountForPrint: string | null;
    public priceForPrint: string | null;
    public useDiscounForPrint: string | null;
    public taxClassIdForPrint: string | null;
    public customerId: number;
    public debitAccountTitleId: number;
    public billingCategoryId: number;
    public currencyId: number;
}

