export class BillingInvoiceDetailForExport {
    public companyCode: string | null;
    public billingInputId: number;
    public billingId: number;
    public billedAt: string;
    public closingAt: string;
    public salesAt: string;
    public dueAt: string;
    public billingAmount: number;
    public taxAmount: number;
    public price: number;
    public remainAmount: number;
    public invoiceCode: string | null;
    public note1: string | null;
    public note2: string | null;
    public note3: string | null;
    public note4: string | null;
    public note5: string | null;
    public note6: string | null;
    public note7: string | null;
    public note8: string | null;
    public memo: string | null;
    public contractNumber: string | null;
    public quantity: number;
    public unitSymbol: string | null;
    public unitPrice: number;
    public publishAt: string;
    public publishAt1st: string;
    public assignmentFlag: number;
    public departmentCode: string | null;
    public departmentName: string | null;
    public billingCategoryCode: string | null;
    public billingCategoryName: string | null;
    public billingCategoryExternalCode: string | null;
    public taxClassId: number;
    public taxClassName: string | null;
    public collectCategoryCode: string | null;
    public collectCategoryName: string | null;
    public collectCategoryExternalCode: string | null;
    public staffName: string | null;
    public staffCode: string | null;
    public customerCode: string | null;
    public customerName: string | null;
    public shareTransferFee: number;
    public customerPostalCode: string | null;
    public customerAddress1: string | null;
    public customerAddress2: string | null;
    public customerDepartmentName: string | null;
    public customerAddressee: string | null;
    public customerHonorific: string | null;
    public customerNote: string | null;
    public exclusiveBankCode: string | null;
    public exclusiveBankName: string | null;
    public exclusiveBranchCode: string | null;
    public virtualBranchCode: string | null;
    public exclusiveBranchName: string | null;
    public virtualAccountNumber: string | null;
    public exclusiveAccountTypeId: number;
    public companyBankName1: string | null;
    public companyBranchName1: string | null;
    public companyAccountType1: string | null;
    public companyAccountNumber1: string | null;
    public companyBankName2: string | null;
    public companyBranchName2: string | null;
    public companyAccountType2: string | null;
    public companyAccountNumber2: string | null;
    public companyBankName3: string | null;
    public companyBranchName3: string | null;
    public companyAccountType3: string | null;
    public companyAccountNumber3: string | null;
    public companyBankAccountName: string | null;
    public companyName: string | null;
    public companyPostalCode: string | null;
    public companyAddress1: string | null;
    public companyAddress2: string | null;
    public companyTel: string | null;
    public companyFax: string | null;
}

