export class CustomerDiscount {
    public customerId: number;
    public sequence: number;
    public rate: number;
    public roundingMode: number;
    public minValue: number;
    public departmentId: number | null;
    public accountTitleId: number | null;
    public subCode: string | null;
    public createBy: number;
    public createAt: string;
    public updateBy: number;
    public updateAt: string;
    public departmentCode: string | null;
    public departmentName: string | null;
    public accountTitleCode: string | null;
    public accountTitleName: string | null;
    public companyId: number;
    public companyCode: string | null;
    public customerCode: string | null;
    public customerName: string | null;
    public rate1: number | null;
    public rate2: number | null;
    public rate3: number | null;
    public rate4: number | null;
    public rate5: number | null;
    public roundingMode1: number;
    public roundingMode2: number;
    public roundingMode3: number;
    public roundingMode4: number;
    public roundingMode5: number;
    public departmentId1: number | null;
    public departmentId2: number | null;
    public departmentId3: number | null;
    public departmentId4: number | null;
    public departmentId5: number | null;
    public accountTitleId1: number | null;
    public accountTitleId2: number | null;
    public accountTitleId3: number | null;
    public accountTitleId4: number | null;
    public accountTitleId5: number | null;
    public subCode1: string | null;
    public subCode2: string | null;
    public subCode3: string | null;
    public subCode4: string | null;
    public subCode5: string | null;
}

