export class MatchedReceipt {
    public companyCode: string | null;
    public slipNumber: number;
    public customerCode: string | null;
    public customerName: string | null;
    public invoiceCode: string | null;
    public billedAt: string;
    public receiptCategoryCode: string | null;
    public receiptCategoryName: string | null;
    public recordedAt: string;
    public dueAt: string | null;
    public amount: number;
    public departmentCode: string | null;
    public departmentName: string | null;
    public currencyCode: string | null;
    public receiptAmount: number;
    public id: number;
    public billingNote1: string | null;
    public billingNote2: string | null;
    public billingNote3: string | null;
    public billingNote4: string | null;
    public receiptNote1: string | null;
    public receiptNote2: string | null;
    public receiptNote3: string | null;
    public receiptNote4: string | null;
    public billNumber: string | null;
    public billBankCode: string | null;
    public billBranchCode: string | null;
    public billDrawAt: string | null;
    public billDrawer: string | null;
    public billingMemo: string | null;
    public receiptMemo: string | null;
    public matchingMemo: string | null;
    public bankCode: string | null;
    public bankName: string | null;
    public branchCode: string | null;
    public branchName: string | null;
    public accountNumber: string | null;
    public sourceBankName: string | null;
    public sourceBranchName: string | null;
    public virtualBranchCode: string | null;
    public virtualAccountNumber: string | null;
    public sectionCode: string | null;
    public sectionName: string | null;
    public receiptCategoryExternalCode: string | null;
    public originalReceiptId: number;
    public journalizingCategory: string | null;
}

