export class ScheduledPaymentImport {
    public id: number;
    public companyId: number;
    public currencyId: number;
    public customerId: number;
    public departmentId: number;
    public staffId: number;
    public billingCategoryId: number;
    public inputType: number;
    public billingInputTypeId: number;
    public billedAt: string;
    public closingAt: string;
    public salesAt: string;
    public dueAt: string;
    public billingAmount: number;
    public taxAmount: number;
    public assignmentAmount: number;
    public remainAmount: number;
    public targetAmount: number;
    public offsetAmount: number;
    public assignmentFlag: number;
    public approved: number;
    public collectCategoryId: number;
    public originalCollectCategoryId: number | null;
    public debitAccountTitleId: number | null;
    public creditAccountTitleId: number | null;
    public originalDueAt: string | null;
    public outputAt: string | null;
    public publishAt: string | null;
    public invoiceCode: string | null;
    public taxClassId: number;
    public note1: string | null;
    public note2: string | null;
    public note3: string | null;
    public note4: string | null;
    public note5: string | null;
    public note6: string | null;
    public note7: string | null;
    public note8: string | null;
    public scheduledPaymentKey: string | null;
    public currencyCode: string | null;
    public customerCode: string | null;
    public customerName: string | null;
    public customerKana: string | null;
    public departmentCode: string | null;
    public departmentName: string | null;
    public staffName: string | null;
    public staffCode: string | null;
    public billingCategoryCode: string | null;
    public billingCategoryName: string | null;
    public collectCategoryCode: string | null;
    public loginUserCode: string | null;
    public billingId: number;
    public parentCustomerId: number;
    public parentCustomerCode: string | null;
    public isParent: Boolean;
    public companyCode: string | null;
    public accountTitleCode: string | null;
    public updateFlg: number;
    public customerFlg: number;
    public lineNo: number;
}

