//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.StatusMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatusMasterService.IStatusMaster")]
    public interface IStatusMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/GetStatusByCode", ReplyAction="http://tempuri.org/IStatusMaster/GetStatusByCodeResponse")]
        Rac.VOne.Web.Models.StatusResult GetStatusByCode(string SessionKey, int CompanyId, int StatusType, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/GetStatusByCode", ReplyAction="http://tempuri.org/IStatusMaster/GetStatusByCodeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.StatusResult> GetStatusByCodeAsync(string SessionKey, int CompanyId, int StatusType, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/GetStatusesByStatusType", ReplyAction="http://tempuri.org/IStatusMaster/GetStatusesByStatusTypeResponse")]
        Rac.VOne.Web.Models.StatusesResult GetStatusesByStatusType(string SessionKey, int CompanyId, int StatusType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/GetStatusesByStatusType", ReplyAction="http://tempuri.org/IStatusMaster/GetStatusesByStatusTypeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.StatusesResult> GetStatusesByStatusTypeAsync(string SessionKey, int CompanyId, int StatusType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/Save", ReplyAction="http://tempuri.org/IStatusMaster/SaveResponse")]
        Rac.VOne.Web.Models.StatusResult Save(string SessionKey, Rac.VOne.Web.Models.Status Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/Save", ReplyAction="http://tempuri.org/IStatusMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.StatusResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Status Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/Delete", ReplyAction="http://tempuri.org/IStatusMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/Delete", ReplyAction="http://tempuri.org/IStatusMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/ExistReminder", ReplyAction="http://tempuri.org/IStatusMaster/ExistReminderResponse")]
        Rac.VOne.Web.Models.ExistResult ExistReminder(string SessionKey, int StatusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/ExistReminder", ReplyAction="http://tempuri.org/IStatusMaster/ExistReminderResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistReminderAsync(string SessionKey, int StatusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/ExistReminderHistory", ReplyAction="http://tempuri.org/IStatusMaster/ExistReminderHistoryResponse")]
        Rac.VOne.Web.Models.ExistResult ExistReminderHistory(string SessionKey, int StatusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusMaster/ExistReminderHistory", ReplyAction="http://tempuri.org/IStatusMaster/ExistReminderHistoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistReminderHistoryAsync(string SessionKey, int StatusId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStatusMasterChannel : Rac.VOne.Client.Screen.StatusMasterService.IStatusMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatusMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.StatusMasterService.IStatusMaster>, Rac.VOne.Client.Screen.StatusMasterService.IStatusMaster {
        
        public StatusMasterClient() {
        }
        
        public StatusMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatusMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.StatusResult GetStatusByCode(string SessionKey, int CompanyId, int StatusType, string Code) {
            return base.Channel.GetStatusByCode(SessionKey, CompanyId, StatusType, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.StatusResult> GetStatusByCodeAsync(string SessionKey, int CompanyId, int StatusType, string Code) {
            return base.Channel.GetStatusByCodeAsync(SessionKey, CompanyId, StatusType, Code);
        }
        
        public Rac.VOne.Web.Models.StatusesResult GetStatusesByStatusType(string SessionKey, int CompanyId, int StatusType) {
            return base.Channel.GetStatusesByStatusType(SessionKey, CompanyId, StatusType);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.StatusesResult> GetStatusesByStatusTypeAsync(string SessionKey, int CompanyId, int StatusType) {
            return base.Channel.GetStatusesByStatusTypeAsync(SessionKey, CompanyId, StatusType);
        }
        
        public Rac.VOne.Web.Models.StatusResult Save(string SessionKey, Rac.VOne.Web.Models.Status Status) {
            return base.Channel.Save(SessionKey, Status);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.StatusResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Status Status) {
            return base.Channel.SaveAsync(SessionKey, Status);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int Id) {
            return base.Channel.Delete(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int Id) {
            return base.Channel.DeleteAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistReminder(string SessionKey, int StatusId) {
            return base.Channel.ExistReminder(SessionKey, StatusId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistReminderAsync(string SessionKey, int StatusId) {
            return base.Channel.ExistReminderAsync(SessionKey, StatusId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistReminderHistory(string SessionKey, int StatusId) {
            return base.Channel.ExistReminderHistory(SessionKey, StatusId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistReminderHistoryAsync(string SessionKey, int StatusId) {
            return base.Channel.ExistReminderHistoryAsync(SessionKey, StatusId);
        }
    }
}
