//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.ReminderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReminderService.IReminderService")]
    public interface IReminderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/Exist", ReplyAction="http://tempuri.org/IReminderService/ExistResponse")]
        Rac.VOne.Web.Models.ExistResult Exist(string SessionKey, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/Exist", ReplyAction="http://tempuri.org/IReminderService/ExistResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistAsync(string SessionKey, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetItems", ReplyAction="http://tempuri.org/IReminderService/GetItemsResponse")]
        Rac.VOne.Web.Models.ReminderResult GetItems(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetItems", ReplyAction="http://tempuri.org/IReminderService/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderResult> GetItemsAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetSummaryItems", ReplyAction="http://tempuri.org/IReminderService/GetSummaryItemsResponse")]
        Rac.VOne.Web.Models.ReminderSummaryResult GetSummaryItems(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetSummaryItems", ReplyAction="http://tempuri.org/IReminderService/GetSummaryItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderSummaryResult> GetSummaryItemsAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetSummaryItemsByDestination", ReplyAction="http://tempuri.org/IReminderService/GetSummaryItemsByDestinationResponse")]
        Rac.VOne.Web.Models.ReminderSummaryResult GetSummaryItemsByDestination(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetSummaryItemsByDestination", ReplyAction="http://tempuri.org/IReminderService/GetSummaryItemsByDestinationResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderSummaryResult> GetSummaryItemsByDestinationAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForPrint", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForPrintResponse")]
        Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForPrint(string SessionKey, int companyId, int[] reminderIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForPrint", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForPrintResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForPrintAsync(string SessionKey, int companyId, int[] reminderIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForPrintByDestinationCode", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForPrintByDestinationCodeRe" +
            "sponse")]
        Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForPrintByDestinationCode(string SessionKey, Rac.VOne.Web.Models.Reminder[] reminders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForPrintByDestinationCode", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForPrintByDestinationCodeRe" +
            "sponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForPrintByDestinationCodeAsync(string SessionKey, Rac.VOne.Web.Models.Reminder[] reminders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForSummaryPrint", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForSummaryPrintResponse")]
        Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForSummaryPrint(string SessionKey, int companyId, int[] customerIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForSummaryPrint", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForSummaryPrintResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForSummaryPrintAsync(string SessionKey, int companyId, int[] customerIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForSummaryPrintByDestinatio" +
            "nCode", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForSummaryPrintByDestinatio" +
            "nCodeResponse")]
        Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForSummaryPrintByDestinationCode(string SessionKey, Rac.VOne.Web.Models.ReminderSummary[] reminderSummaries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForSummaryPrintByDestinatio" +
            "nCode", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForSummaryPrintByDestinatio" +
            "nCodeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForSummaryPrintByDestinationCodeAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSummary[] reminderSummaries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForReprint", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForReprintResponse")]
        Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForReprint(string SessionKey, int companyId, Rac.VOne.Web.Models.ReminderOutputed reminderOutputed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForReprint", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForReprintResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForReprintAsync(string SessionKey, int companyId, Rac.VOne.Web.Models.ReminderOutputed reminderOutputed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForReprintByDestination", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForReprintByDestinationResp" +
            "onse")]
        Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForReprintByDestination(string SessionKey, int companyId, Rac.VOne.Web.Models.ReminderOutputed reminderOutputed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderBillingForReprintByDestination", ReplyAction="http://tempuri.org/IReminderService/GetReminderBillingForReprintByDestinationResp" +
            "onse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForReprintByDestinationAsync(string SessionKey, int companyId, Rac.VOne.Web.Models.ReminderOutputed reminderOutputed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/Create", ReplyAction="http://tempuri.org/IReminderService/CreateResponse")]
        Rac.VOne.Web.Models.ReminderResult Create(string SessionKey, int companyId, int loginUserId, int useForeignCurrency, Rac.VOne.Web.Models.Reminder[] Reminder, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/Create", ReplyAction="http://tempuri.org/IReminderService/CreateResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderResult> CreateAsync(string SessionKey, int companyId, int loginUserId, int useForeignCurrency, Rac.VOne.Web.Models.Reminder[] Reminder, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetHistoryItemsByReminderId", ReplyAction="http://tempuri.org/IReminderService/GetHistoryItemsByReminderIdResponse")]
        Rac.VOne.Web.Models.ReminderHistoriesResult GetHistoryItemsByReminderId(string SessionKey, int reminderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetHistoryItemsByReminderId", ReplyAction="http://tempuri.org/IReminderService/GetHistoryItemsByReminderIdResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderHistoriesResult> GetHistoryItemsByReminderIdAsync(string SessionKey, int reminderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetSummaryHistoryItemsByReminderSummaryId", ReplyAction="http://tempuri.org/IReminderService/GetSummaryHistoryItemsByReminderSummaryIdResp" +
            "onse")]
        Rac.VOne.Web.Models.ReminderSummaryHistoriesResult GetSummaryHistoryItemsByReminderSummaryId(string SessionKey, int reminderSummaryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetSummaryHistoryItemsByReminderSummaryId", ReplyAction="http://tempuri.org/IReminderService/GetSummaryHistoryItemsByReminderSummaryIdResp" +
            "onse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderSummaryHistoriesResult> GetSummaryHistoryItemsByReminderSummaryIdAsync(string SessionKey, int reminderSummaryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateStatus", ReplyAction="http://tempuri.org/IReminderService/UpdateStatusResponse")]
        Rac.VOne.Web.Models.CountResult UpdateStatus(string SessionKey, int loginUserId, Rac.VOne.Web.Models.Reminder[] Reminder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateStatus", ReplyAction="http://tempuri.org/IReminderService/UpdateStatusResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> UpdateStatusAsync(string SessionKey, int loginUserId, Rac.VOne.Web.Models.Reminder[] Reminder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateSummaryStatus", ReplyAction="http://tempuri.org/IReminderService/UpdateSummaryStatusResponse")]
        Rac.VOne.Web.Models.CountResult UpdateSummaryStatus(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderSummary[] ReminderSummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateSummaryStatus", ReplyAction="http://tempuri.org/IReminderService/UpdateSummaryStatusResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> UpdateSummaryStatusAsync(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderSummary[] ReminderSummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateReminderOutputed", ReplyAction="http://tempuri.org/IReminderService/UpdateReminderOutputedResponse")]
        Rac.VOne.Web.Models.CountResult UpdateReminderOutputed(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderOutputed[] ReminderOutputed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateReminderOutputed", ReplyAction="http://tempuri.org/IReminderService/UpdateReminderOutputedResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> UpdateReminderOutputedAsync(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderOutputed[] ReminderOutputed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateReminderSummaryOutputed", ReplyAction="http://tempuri.org/IReminderService/UpdateReminderSummaryOutputedResponse")]
        Rac.VOne.Web.Models.CountResult UpdateReminderSummaryOutputed(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderOutputed[] reminderOutputed, Rac.VOne.Web.Models.ReminderSummary[] ReminderSummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateReminderSummaryOutputed", ReplyAction="http://tempuri.org/IReminderService/UpdateReminderSummaryOutputedResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> UpdateReminderSummaryOutputedAsync(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderOutputed[] reminderOutputed, Rac.VOne.Web.Models.ReminderSummary[] ReminderSummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetOutputedItems", ReplyAction="http://tempuri.org/IReminderService/GetOutputedItemsResponse")]
        Rac.VOne.Web.Models.ReminderOutputedResult GetOutputedItems(string SessionKey, Rac.VOne.Web.Models.ReminderOutputedSearch search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetOutputedItems", ReplyAction="http://tempuri.org/IReminderService/GetOutputedItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderOutputedResult> GetOutputedItemsAsync(string SessionKey, Rac.VOne.Web.Models.ReminderOutputedSearch search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetMaxOutputNo", ReplyAction="http://tempuri.org/IReminderService/GetMaxOutputNoResponse")]
        Rac.VOne.Web.Models.CountResult GetMaxOutputNo(string SessionKey, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetMaxOutputNo", ReplyAction="http://tempuri.org/IReminderService/GetMaxOutputNoResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> GetMaxOutputNoAsync(string SessionKey, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderList", ReplyAction="http://tempuri.org/IReminderService/GetReminderListResponse")]
        Rac.VOne.Web.Models.ReminderHistoriesResult GetReminderList(string SessionKey, Rac.VOne.Web.Models.ReminderSearch search, Rac.VOne.Web.Models.ReminderCommonSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetReminderList", ReplyAction="http://tempuri.org/IReminderService/GetReminderListResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderHistoriesResult> GetReminderListAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSearch search, Rac.VOne.Web.Models.ReminderCommonSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateReminderHistory", ReplyAction="http://tempuri.org/IReminderService/UpdateReminderHistoryResponse")]
        Rac.VOne.Web.Models.ReminderHistoryResult UpdateReminderHistory(string SessionKey, Rac.VOne.Web.Models.ReminderHistory reminderHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateReminderHistory", ReplyAction="http://tempuri.org/IReminderService/UpdateReminderHistoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderHistoryResult> UpdateReminderHistoryAsync(string SessionKey, Rac.VOne.Web.Models.ReminderHistory reminderHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateReminderSummaryHistory", ReplyAction="http://tempuri.org/IReminderService/UpdateReminderSummaryHistoryResponse")]
        Rac.VOne.Web.Models.ReminderSummaryHistoryResult UpdateReminderSummaryHistory(string SessionKey, Rac.VOne.Web.Models.ReminderSummaryHistory reminderSummaryHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/UpdateReminderSummaryHistory", ReplyAction="http://tempuri.org/IReminderService/UpdateReminderSummaryHistoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderSummaryHistoryResult> UpdateReminderSummaryHistoryAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSummaryHistory reminderSummaryHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/DeleteHistory", ReplyAction="http://tempuri.org/IReminderService/DeleteHistoryResponse")]
        Rac.VOne.Web.Models.CountResult DeleteHistory(string SessionKey, Rac.VOne.Web.Models.ReminderHistory reminderHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/DeleteHistory", ReplyAction="http://tempuri.org/IReminderService/DeleteHistoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteHistoryAsync(string SessionKey, Rac.VOne.Web.Models.ReminderHistory reminderHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/DeleteSummaryHistory", ReplyAction="http://tempuri.org/IReminderService/DeleteSummaryHistoryResponse")]
        Rac.VOne.Web.Models.CountResult DeleteSummaryHistory(string SessionKey, Rac.VOne.Web.Models.ReminderSummaryHistory reminderSummaryHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/DeleteSummaryHistory", ReplyAction="http://tempuri.org/IReminderService/DeleteSummaryHistoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteSummaryHistoryAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSummaryHistory reminderSummaryHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetCancelDecisionItems", ReplyAction="http://tempuri.org/IReminderService/GetCancelDecisionItemsResponse")]
        Rac.VOne.Web.Models.ReminderResult GetCancelDecisionItems(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/GetCancelDecisionItems", ReplyAction="http://tempuri.org/IReminderService/GetCancelDecisionItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderResult> GetCancelDecisionItemsAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/CancelReminders", ReplyAction="http://tempuri.org/IReminderService/CancelRemindersResponse")]
        Rac.VOne.Web.Models.CountResult CancelReminders(string SessionKey, Rac.VOne.Web.Models.Reminder[] reminders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/CancelReminders", ReplyAction="http://tempuri.org/IReminderService/CancelRemindersResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> CancelRemindersAsync(string SessionKey, Rac.VOne.Web.Models.Reminder[] reminders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/ExistDestination", ReplyAction="http://tempuri.org/IReminderService/ExistDestinationResponse")]
        Rac.VOne.Web.Models.ExistResult ExistDestination(string SessionKey, int DestinationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReminderService/ExistDestination", ReplyAction="http://tempuri.org/IReminderService/ExistDestinationResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistDestinationAsync(string SessionKey, int DestinationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReminderServiceChannel : Rac.VOne.Client.Screen.ReminderService.IReminderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReminderServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.ReminderService.IReminderService>, Rac.VOne.Client.Screen.ReminderService.IReminderService {
        
        public ReminderServiceClient() {
        }
        
        public ReminderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReminderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReminderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReminderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.ExistResult Exist(string SessionKey, int companyId) {
            return base.Channel.Exist(SessionKey, companyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistAsync(string SessionKey, int companyId) {
            return base.Channel.ExistAsync(SessionKey, companyId);
        }
        
        public Rac.VOne.Web.Models.ReminderResult GetItems(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary) {
            return base.Channel.GetItems(SessionKey, condition, setting, summary);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderResult> GetItemsAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary) {
            return base.Channel.GetItemsAsync(SessionKey, condition, setting, summary);
        }
        
        public Rac.VOne.Web.Models.ReminderSummaryResult GetSummaryItems(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting) {
            return base.Channel.GetSummaryItems(SessionKey, condition, setting);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderSummaryResult> GetSummaryItemsAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting) {
            return base.Channel.GetSummaryItemsAsync(SessionKey, condition, setting);
        }
        
        public Rac.VOne.Web.Models.ReminderSummaryResult GetSummaryItemsByDestination(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting) {
            return base.Channel.GetSummaryItemsByDestination(SessionKey, condition, setting);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderSummaryResult> GetSummaryItemsByDestinationAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting) {
            return base.Channel.GetSummaryItemsByDestinationAsync(SessionKey, condition, setting);
        }
        
        public Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForPrint(string SessionKey, int companyId, int[] reminderIds) {
            return base.Channel.GetReminderBillingForPrint(SessionKey, companyId, reminderIds);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForPrintAsync(string SessionKey, int companyId, int[] reminderIds) {
            return base.Channel.GetReminderBillingForPrintAsync(SessionKey, companyId, reminderIds);
        }
        
        public Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForPrintByDestinationCode(string SessionKey, Rac.VOne.Web.Models.Reminder[] reminders) {
            return base.Channel.GetReminderBillingForPrintByDestinationCode(SessionKey, reminders);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForPrintByDestinationCodeAsync(string SessionKey, Rac.VOne.Web.Models.Reminder[] reminders) {
            return base.Channel.GetReminderBillingForPrintByDestinationCodeAsync(SessionKey, reminders);
        }
        
        public Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForSummaryPrint(string SessionKey, int companyId, int[] customerIds) {
            return base.Channel.GetReminderBillingForSummaryPrint(SessionKey, companyId, customerIds);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForSummaryPrintAsync(string SessionKey, int companyId, int[] customerIds) {
            return base.Channel.GetReminderBillingForSummaryPrintAsync(SessionKey, companyId, customerIds);
        }
        
        public Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForSummaryPrintByDestinationCode(string SessionKey, Rac.VOne.Web.Models.ReminderSummary[] reminderSummaries) {
            return base.Channel.GetReminderBillingForSummaryPrintByDestinationCode(SessionKey, reminderSummaries);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForSummaryPrintByDestinationCodeAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSummary[] reminderSummaries) {
            return base.Channel.GetReminderBillingForSummaryPrintByDestinationCodeAsync(SessionKey, reminderSummaries);
        }
        
        public Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForReprint(string SessionKey, int companyId, Rac.VOne.Web.Models.ReminderOutputed reminderOutputed) {
            return base.Channel.GetReminderBillingForReprint(SessionKey, companyId, reminderOutputed);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForReprintAsync(string SessionKey, int companyId, Rac.VOne.Web.Models.ReminderOutputed reminderOutputed) {
            return base.Channel.GetReminderBillingForReprintAsync(SessionKey, companyId, reminderOutputed);
        }
        
        public Rac.VOne.Web.Models.ReminderBillingResult GetReminderBillingForReprintByDestination(string SessionKey, int companyId, Rac.VOne.Web.Models.ReminderOutputed reminderOutputed) {
            return base.Channel.GetReminderBillingForReprintByDestination(SessionKey, companyId, reminderOutputed);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderBillingResult> GetReminderBillingForReprintByDestinationAsync(string SessionKey, int companyId, Rac.VOne.Web.Models.ReminderOutputed reminderOutputed) {
            return base.Channel.GetReminderBillingForReprintByDestinationAsync(SessionKey, companyId, reminderOutputed);
        }
        
        public Rac.VOne.Web.Models.ReminderResult Create(string SessionKey, int companyId, int loginUserId, int useForeignCurrency, Rac.VOne.Web.Models.Reminder[] Reminder, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary) {
            return base.Channel.Create(SessionKey, companyId, loginUserId, useForeignCurrency, Reminder, setting, summary);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderResult> CreateAsync(string SessionKey, int companyId, int loginUserId, int useForeignCurrency, Rac.VOne.Web.Models.Reminder[] Reminder, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary) {
            return base.Channel.CreateAsync(SessionKey, companyId, loginUserId, useForeignCurrency, Reminder, setting, summary);
        }
        
        public Rac.VOne.Web.Models.ReminderHistoriesResult GetHistoryItemsByReminderId(string SessionKey, int reminderId) {
            return base.Channel.GetHistoryItemsByReminderId(SessionKey, reminderId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderHistoriesResult> GetHistoryItemsByReminderIdAsync(string SessionKey, int reminderId) {
            return base.Channel.GetHistoryItemsByReminderIdAsync(SessionKey, reminderId);
        }
        
        public Rac.VOne.Web.Models.ReminderSummaryHistoriesResult GetSummaryHistoryItemsByReminderSummaryId(string SessionKey, int reminderSummaryId) {
            return base.Channel.GetSummaryHistoryItemsByReminderSummaryId(SessionKey, reminderSummaryId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderSummaryHistoriesResult> GetSummaryHistoryItemsByReminderSummaryIdAsync(string SessionKey, int reminderSummaryId) {
            return base.Channel.GetSummaryHistoryItemsByReminderSummaryIdAsync(SessionKey, reminderSummaryId);
        }
        
        public Rac.VOne.Web.Models.CountResult UpdateStatus(string SessionKey, int loginUserId, Rac.VOne.Web.Models.Reminder[] Reminder) {
            return base.Channel.UpdateStatus(SessionKey, loginUserId, Reminder);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> UpdateStatusAsync(string SessionKey, int loginUserId, Rac.VOne.Web.Models.Reminder[] Reminder) {
            return base.Channel.UpdateStatusAsync(SessionKey, loginUserId, Reminder);
        }
        
        public Rac.VOne.Web.Models.CountResult UpdateSummaryStatus(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderSummary[] ReminderSummary) {
            return base.Channel.UpdateSummaryStatus(SessionKey, loginUserId, ReminderSummary);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> UpdateSummaryStatusAsync(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderSummary[] ReminderSummary) {
            return base.Channel.UpdateSummaryStatusAsync(SessionKey, loginUserId, ReminderSummary);
        }
        
        public Rac.VOne.Web.Models.CountResult UpdateReminderOutputed(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderOutputed[] ReminderOutputed) {
            return base.Channel.UpdateReminderOutputed(SessionKey, loginUserId, ReminderOutputed);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> UpdateReminderOutputedAsync(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderOutputed[] ReminderOutputed) {
            return base.Channel.UpdateReminderOutputedAsync(SessionKey, loginUserId, ReminderOutputed);
        }
        
        public Rac.VOne.Web.Models.CountResult UpdateReminderSummaryOutputed(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderOutputed[] reminderOutputed, Rac.VOne.Web.Models.ReminderSummary[] ReminderSummary) {
            return base.Channel.UpdateReminderSummaryOutputed(SessionKey, loginUserId, reminderOutputed, ReminderSummary);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> UpdateReminderSummaryOutputedAsync(string SessionKey, int loginUserId, Rac.VOne.Web.Models.ReminderOutputed[] reminderOutputed, Rac.VOne.Web.Models.ReminderSummary[] ReminderSummary) {
            return base.Channel.UpdateReminderSummaryOutputedAsync(SessionKey, loginUserId, reminderOutputed, ReminderSummary);
        }
        
        public Rac.VOne.Web.Models.ReminderOutputedResult GetOutputedItems(string SessionKey, Rac.VOne.Web.Models.ReminderOutputedSearch search) {
            return base.Channel.GetOutputedItems(SessionKey, search);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderOutputedResult> GetOutputedItemsAsync(string SessionKey, Rac.VOne.Web.Models.ReminderOutputedSearch search) {
            return base.Channel.GetOutputedItemsAsync(SessionKey, search);
        }
        
        public Rac.VOne.Web.Models.CountResult GetMaxOutputNo(string SessionKey, int companyId) {
            return base.Channel.GetMaxOutputNo(SessionKey, companyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> GetMaxOutputNoAsync(string SessionKey, int companyId) {
            return base.Channel.GetMaxOutputNoAsync(SessionKey, companyId);
        }
        
        public Rac.VOne.Web.Models.ReminderHistoriesResult GetReminderList(string SessionKey, Rac.VOne.Web.Models.ReminderSearch search, Rac.VOne.Web.Models.ReminderCommonSetting setting) {
            return base.Channel.GetReminderList(SessionKey, search, setting);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderHistoriesResult> GetReminderListAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSearch search, Rac.VOne.Web.Models.ReminderCommonSetting setting) {
            return base.Channel.GetReminderListAsync(SessionKey, search, setting);
        }
        
        public Rac.VOne.Web.Models.ReminderHistoryResult UpdateReminderHistory(string SessionKey, Rac.VOne.Web.Models.ReminderHistory reminderHistory) {
            return base.Channel.UpdateReminderHistory(SessionKey, reminderHistory);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderHistoryResult> UpdateReminderHistoryAsync(string SessionKey, Rac.VOne.Web.Models.ReminderHistory reminderHistory) {
            return base.Channel.UpdateReminderHistoryAsync(SessionKey, reminderHistory);
        }
        
        public Rac.VOne.Web.Models.ReminderSummaryHistoryResult UpdateReminderSummaryHistory(string SessionKey, Rac.VOne.Web.Models.ReminderSummaryHistory reminderSummaryHistory) {
            return base.Channel.UpdateReminderSummaryHistory(SessionKey, reminderSummaryHistory);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderSummaryHistoryResult> UpdateReminderSummaryHistoryAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSummaryHistory reminderSummaryHistory) {
            return base.Channel.UpdateReminderSummaryHistoryAsync(SessionKey, reminderSummaryHistory);
        }
        
        public Rac.VOne.Web.Models.CountResult DeleteHistory(string SessionKey, Rac.VOne.Web.Models.ReminderHistory reminderHistory) {
            return base.Channel.DeleteHistory(SessionKey, reminderHistory);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteHistoryAsync(string SessionKey, Rac.VOne.Web.Models.ReminderHistory reminderHistory) {
            return base.Channel.DeleteHistoryAsync(SessionKey, reminderHistory);
        }
        
        public Rac.VOne.Web.Models.CountResult DeleteSummaryHistory(string SessionKey, Rac.VOne.Web.Models.ReminderSummaryHistory reminderSummaryHistory) {
            return base.Channel.DeleteSummaryHistory(SessionKey, reminderSummaryHistory);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteSummaryHistoryAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSummaryHistory reminderSummaryHistory) {
            return base.Channel.DeleteSummaryHistoryAsync(SessionKey, reminderSummaryHistory);
        }
        
        public Rac.VOne.Web.Models.ReminderResult GetCancelDecisionItems(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary) {
            return base.Channel.GetCancelDecisionItems(SessionKey, condition, setting, summary);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReminderResult> GetCancelDecisionItemsAsync(string SessionKey, Rac.VOne.Web.Models.ReminderSearch condition, Rac.VOne.Web.Models.ReminderCommonSetting setting, Rac.VOne.Web.Models.ReminderSummarySetting[] summary) {
            return base.Channel.GetCancelDecisionItemsAsync(SessionKey, condition, setting, summary);
        }
        
        public Rac.VOne.Web.Models.CountResult CancelReminders(string SessionKey, Rac.VOne.Web.Models.Reminder[] reminders) {
            return base.Channel.CancelReminders(SessionKey, reminders);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> CancelRemindersAsync(string SessionKey, Rac.VOne.Web.Models.Reminder[] reminders) {
            return base.Channel.CancelRemindersAsync(SessionKey, reminders);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistDestination(string SessionKey, int DestinationId) {
            return base.Channel.ExistDestination(SessionKey, DestinationId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistDestinationAsync(string SessionKey, int DestinationId) {
            return base.Channel.ExistDestinationAsync(SessionKey, DestinationId);
        }
    }
}
