//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.BillingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BillingService.IBillingService")]
    public interface IBillingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Save", ReplyAction="http://tempuri.org/IBillingService/SaveResponse")]
        Rac.VOne.Web.Models.BillingsResult Save(string SessionKey, Rac.VOne.Web.Models.Billing[] billings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Save", ReplyAction="http://tempuri.org/IBillingService/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Billing[] billings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/SaveForInput", ReplyAction="http://tempuri.org/IBillingService/SaveForInputResponse")]
        Rac.VOne.Web.Models.BillingsResult SaveForInput(string SessionKey, Rac.VOne.Web.Models.Billing[] billings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/SaveForInput", ReplyAction="http://tempuri.org/IBillingService/SaveForInputResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> SaveForInputAsync(string SessionKey, Rac.VOne.Web.Models.Billing[] billings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Delete", ReplyAction="http://tempuri.org/IBillingService/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, long[] Id, int UseLongTermAdvanceReceived, int RegisterContractInAdvance, int UseDiscount, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Delete", ReplyAction="http://tempuri.org/IBillingService/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, long[] Id, int UseLongTermAdvanceReceived, int RegisterContractInAdvance, int UseDiscount, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/DeleteByInputId", ReplyAction="http://tempuri.org/IBillingService/DeleteByInputIdResponse")]
        Rac.VOne.Web.Models.CountResult DeleteByInputId(string SessionKey, long InputId, int UseLongTermAdvanceReceived, int RegisterContractInAdvance, int UseDiscount, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/DeleteByInputId", ReplyAction="http://tempuri.org/IBillingService/DeleteByInputIdResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteByInputIdAsync(string SessionKey, long InputId, int UseLongTermAdvanceReceived, int RegisterContractInAdvance, int UseDiscount, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Get", ReplyAction="http://tempuri.org/IBillingService/GetResponse")]
        Rac.VOne.Web.Models.BillingResult Get(string SessionKey, long[] Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Get", ReplyAction="http://tempuri.org/IBillingService/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingResult> GetAsync(string SessionKey, long[] Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetItems", ReplyAction="http://tempuri.org/IBillingService/GetItemsResponse")]
        Rac.VOne.Web.Models.BillingsResult GetItems(string SessionKey, Rac.VOne.Web.Models.BillingSearch BillingSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetItems", ReplyAction="http://tempuri.org/IBillingService/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> GetItemsAsync(string SessionKey, Rac.VOne.Web.Models.BillingSearch BillingSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/InputScheduledPayment", ReplyAction="http://tempuri.org/IBillingService/InputScheduledPaymentResponse")]
        Rac.VOne.Web.Models.BillingsResult InputScheduledPayment(string sessionKey, Rac.VOne.Web.Models.Billing[] billings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/InputScheduledPayment", ReplyAction="http://tempuri.org/IBillingService/InputScheduledPaymentResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> InputScheduledPaymentAsync(string sessionKey, Rac.VOne.Web.Models.Billing[] billings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/SaveMemo", ReplyAction="http://tempuri.org/IBillingService/SaveMemoResponse")]
        Rac.VOne.Web.Models.CountResult SaveMemo(string SessionKey, long Id, string Memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/SaveMemo", ReplyAction="http://tempuri.org/IBillingService/SaveMemoResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> SaveMemoAsync(string SessionKey, long Id, string Memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/DeleteMemo", ReplyAction="http://tempuri.org/IBillingService/DeleteMemoResponse")]
        Rac.VOne.Web.Models.CountResult DeleteMemo(string SessionKey, long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/DeleteMemo", ReplyAction="http://tempuri.org/IBillingService/DeleteMemoResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteMemoAsync(string SessionKey, long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetMemo", ReplyAction="http://tempuri.org/IBillingService/GetMemoResponse")]
        Rac.VOne.Web.Models.BillMemoResult GetMemo(string SessionKey, long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetMemo", ReplyAction="http://tempuri.org/IBillingService/GetMemoResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillMemoResult> GetMemoAsync(string SessionKey, long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/SaveDiscount", ReplyAction="http://tempuri.org/IBillingService/SaveDiscountResponse")]
        Rac.VOne.Web.Models.CountResult SaveDiscount(string SessionKey, Rac.VOne.Web.Models.BillingDiscount BillingDiscount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/SaveDiscount", ReplyAction="http://tempuri.org/IBillingService/SaveDiscountResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> SaveDiscountAsync(string SessionKey, Rac.VOne.Web.Models.BillingDiscount BillingDiscount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/DeleteDiscount", ReplyAction="http://tempuri.org/IBillingService/DeleteDiscountResponse")]
        Rac.VOne.Web.Models.CountResult DeleteDiscount(string SessionKey, long BillingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/DeleteDiscount", ReplyAction="http://tempuri.org/IBillingService/DeleteDiscountResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteDiscountAsync(string SessionKey, long BillingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetDiscount", ReplyAction="http://tempuri.org/IBillingService/GetDiscountResponse")]
        Rac.VOne.Web.Models.BillingDiscountsResult GetDiscount(string SessionKey, long BillingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetDiscount", ReplyAction="http://tempuri.org/IBillingService/GetDiscountResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingDiscountsResult> GetDiscountAsync(string SessionKey, long BillingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistAccountTitle", ReplyAction="http://tempuri.org/IBillingService/ExistAccountTitleResponse")]
        Rac.VOne.Web.Models.ExistResult ExistAccountTitle(string SessionKey, int AccountTitleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistAccountTitle", ReplyAction="http://tempuri.org/IBillingService/ExistAccountTitleResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistAccountTitleAsync(string SessionKey, int AccountTitleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistCollectCategory", ReplyAction="http://tempuri.org/IBillingService/ExistCollectCategoryResponse")]
        Rac.VOne.Web.Models.ExistResult ExistCollectCategory(string SessionKey, int CategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistCollectCategory", ReplyAction="http://tempuri.org/IBillingService/ExistCollectCategoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCollectCategoryAsync(string SessionKey, int CategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistCustomer", ReplyAction="http://tempuri.org/IBillingService/ExistCustomerResponse")]
        Rac.VOne.Web.Models.ExistResult ExistCustomer(string SessionKey, int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistCustomer", ReplyAction="http://tempuri.org/IBillingService/ExistCustomerResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCustomerAsync(string SessionKey, int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistBillingCategory", ReplyAction="http://tempuri.org/IBillingService/ExistBillingCategoryResponse")]
        Rac.VOne.Web.Models.ExistResult ExistBillingCategory(string SessionKey, int CategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistBillingCategory", ReplyAction="http://tempuri.org/IBillingService/ExistBillingCategoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistBillingCategoryAsync(string SessionKey, int CategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistStaff", ReplyAction="http://tempuri.org/IBillingService/ExistStaffResponse")]
        Rac.VOne.Web.Models.ExistResult ExistStaff(string SessionKey, int StaffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistStaff", ReplyAction="http://tempuri.org/IBillingService/ExistStaffResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistStaffAsync(string SessionKey, int StaffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistCurrency", ReplyAction="http://tempuri.org/IBillingService/ExistCurrencyResponse")]
        Rac.VOne.Web.Models.ExistResult ExistCurrency(string SessionKey, int CurrencyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistCurrency", ReplyAction="http://tempuri.org/IBillingService/ExistCurrencyResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCurrencyAsync(string SessionKey, int CurrencyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistDepartment", ReplyAction="http://tempuri.org/IBillingService/ExistDepartmentResponse")]
        Rac.VOne.Web.Models.ExistResult ExistDepartment(string SessionKey, int DepartmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistDepartment", ReplyAction="http://tempuri.org/IBillingService/ExistDepartmentResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistDepartmentAsync(string SessionKey, int DepartmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistDestination", ReplyAction="http://tempuri.org/IBillingService/ExistDestinationResponse")]
        Rac.VOne.Web.Models.ExistResult ExistDestination(string SessionKey, int DestinationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExistDestination", ReplyAction="http://tempuri.org/IBillingService/ExistDestinationResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistDestinationAsync(string SessionKey, int DestinationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ImportScheduledPayment", ReplyAction="http://tempuri.org/IBillingService/ImportScheduledPaymentResponse")]
        Rac.VOne.Web.Models.ScheduledPaymentImportResult ImportScheduledPayment(string SessionKey, int CompanyId, int LoginUserId, int ImporterSettingId, Rac.VOne.Web.Models.ScheduledPaymentImport[] SchedulePayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ImportScheduledPayment", ReplyAction="http://tempuri.org/IBillingService/ImportScheduledPaymentResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ScheduledPaymentImportResult> ImportScheduledPaymentAsync(string SessionKey, int CompanyId, int LoginUserId, int ImporterSettingId, Rac.VOne.Web.Models.ScheduledPaymentImport[] SchedulePayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Omit", ReplyAction="http://tempuri.org/IBillingService/OmitResponse")]
        Rac.VOne.Web.Models.CountResult Omit(string SessionKey, int doDelete, int loginUserId, Rac.VOne.Web.Models.Transaction[] transactions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Omit", ReplyAction="http://tempuri.org/IBillingService/OmitResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> OmitAsync(string SessionKey, int doDelete, int loginUserId, Rac.VOne.Web.Models.Transaction[] transactions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetItemsForScheduledPaymentImport", ReplyAction="http://tempuri.org/IBillingService/GetItemsForScheduledPaymentImportResponse")]
        Rac.VOne.Web.Models.BillingsResult GetItemsForScheduledPaymentImport(string SessionKey, int CompanyId, Rac.VOne.Web.Models.ScheduledPaymentImport[] SchedulePayment, Rac.VOne.Web.Models.ImporterSettingDetail[] details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetItemsForScheduledPaymentImport", ReplyAction="http://tempuri.org/IBillingService/GetItemsForScheduledPaymentImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> GetItemsForScheduledPaymentImportAsync(string SessionKey, int CompanyId, Rac.VOne.Web.Models.ScheduledPaymentImport[] SchedulePayment, Rac.VOne.Web.Models.ImporterSettingDetail[] details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Import", ReplyAction="http://tempuri.org/IBillingService/ImportResponse")]
        Rac.VOne.Web.Models.BillingImportResult Import(string SessionKey, int CompanyId, int LoginUserId, int ImporterSettingId, Rac.VOne.Web.Models.BillingImport[] billingImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Import", ReplyAction="http://tempuri.org/IBillingService/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingImportResult> ImportAsync(string SessionKey, int CompanyId, int LoginUserId, int ImporterSettingId, Rac.VOne.Web.Models.BillingImport[] billingImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/BillingImportDuplicationCheck", ReplyAction="http://tempuri.org/IBillingService/BillingImportDuplicationCheckResponse")]
        Rac.VOne.Web.Models.BillingImportDuplicationResult BillingImportDuplicationCheck(string SessionKey, int CompanyId, Rac.VOne.Web.Models.BillingImportDuplicationWithCode[] BillingImportDuplication, Rac.VOne.Web.Models.ImporterSettingDetail[] ImporterSettingDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/BillingImportDuplicationCheck", ReplyAction="http://tempuri.org/IBillingService/BillingImportDuplicationCheckResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingImportDuplicationResult> BillingImportDuplicationCheckAsync(string SessionKey, int CompanyId, Rac.VOne.Web.Models.BillingImportDuplicationWithCode[] BillingImportDuplication, Rac.VOne.Web.Models.ImporterSettingDetail[] ImporterSettingDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetBillingJournalizingSummary", ReplyAction="http://tempuri.org/IBillingService/GetBillingJournalizingSummaryResponse")]
        Rac.VOne.Web.Models.JournalizingSummariesResult GetBillingJournalizingSummary(string SessionKey, int OutputFlg, int CompanyId, int CurrencyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetBillingJournalizingSummary", ReplyAction="http://tempuri.org/IBillingService/GetBillingJournalizingSummaryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.JournalizingSummariesResult> GetBillingJournalizingSummaryAsync(string SessionKey, int OutputFlg, int CompanyId, int CurrencyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExtractBillingJournalizing", ReplyAction="http://tempuri.org/IBillingService/ExtractBillingJournalizingResponse")]
        Rac.VOne.Web.Models.BillingJournalizingsResult ExtractBillingJournalizing(string SessionKey, int CompanyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo, int CurrencyId, System.DateTime[] OutputAt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ExtractBillingJournalizing", ReplyAction="http://tempuri.org/IBillingService/ExtractBillingJournalizingResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingJournalizingsResult> ExtractBillingJournalizingAsync(string SessionKey, int CompanyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo, int CurrencyId, System.DateTime[] OutputAt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/UpdateOutputAt", ReplyAction="http://tempuri.org/IBillingService/UpdateOutputAtResponse")]
        Rac.VOne.Web.Models.BillingsResult UpdateOutputAt(string SessionKey, int CompanyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo, int CurrencyId, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/UpdateOutputAt", ReplyAction="http://tempuri.org/IBillingService/UpdateOutputAtResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> UpdateOutputAtAsync(string SessionKey, int CompanyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo, int CurrencyId, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/CancelBillingJournalizing", ReplyAction="http://tempuri.org/IBillingService/CancelBillingJournalizingResponse")]
        Rac.VOne.Web.Models.BillingsResult CancelBillingJournalizing(string SessionKey, int CompanyId, int CurrencyId, System.DateTime[] OutputAt, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/CancelBillingJournalizing", ReplyAction="http://tempuri.org/IBillingService/CancelBillingJournalizingResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> CancelBillingJournalizingAsync(string SessionKey, int CompanyId, int CurrencyId, System.DateTime[] OutputAt, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetAccountTransferMatchingTargetList", ReplyAction="http://tempuri.org/IBillingService/GetAccountTransferMatchingTargetListResponse")]
        Rac.VOne.Web.Models.BillingsResult GetAccountTransferMatchingTargetList(string sessionKey, int companyId, int paymentAgencyId, System.DateTime transferDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetAccountTransferMatchingTargetList", ReplyAction="http://tempuri.org/IBillingService/GetAccountTransferMatchingTargetListResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> GetAccountTransferMatchingTargetListAsync(string sessionKey, int companyId, int paymentAgencyId, System.DateTime transferDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ImportAccountTransferResult", ReplyAction="http://tempuri.org/IBillingService/ImportAccountTransferResultResponse")]
        Rac.VOne.Web.Models.AccountTransferImportResult ImportAccountTransferResult(string sessionKey, Rac.VOne.Web.Models.AccountTransferImportData[] importDataList, System.Nullable<int> dueDateOffset, System.Nullable<int> collectCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ImportAccountTransferResult", ReplyAction="http://tempuri.org/IBillingService/ImportAccountTransferResultResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.AccountTransferImportResult> ImportAccountTransferResultAsync(string sessionKey, Rac.VOne.Web.Models.AccountTransferImportData[] importDataList, System.Nullable<int> dueDateOffset, System.Nullable<int> collectCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetDueAtModifyItems", ReplyAction="http://tempuri.org/IBillingService/GetDueAtModifyItemsResponse")]
        Rac.VOne.Web.Models.BillingDueAtModifyResults GetDueAtModifyItems(string sessionKey, Rac.VOne.Web.Models.BillingSearch option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetDueAtModifyItems", ReplyAction="http://tempuri.org/IBillingService/GetDueAtModifyItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingDueAtModifyResults> GetDueAtModifyItemsAsync(string sessionKey, Rac.VOne.Web.Models.BillingSearch option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/UpdateDueAt", ReplyAction="http://tempuri.org/IBillingService/UpdateDueAtResponse")]
        Rac.VOne.Web.Models.BillingsResult UpdateDueAt(string sessionKey, Rac.VOne.Web.Models.BillingDueAtModify[] billings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/UpdateDueAt", ReplyAction="http://tempuri.org/IBillingService/UpdateDueAtResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> UpdateDueAtAsync(string sessionKey, Rac.VOne.Web.Models.BillingDueAtModify[] billings);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBillingServiceChannel : Rac.VOne.Client.Screen.BillingService.IBillingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillingServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.BillingService.IBillingService>, Rac.VOne.Client.Screen.BillingService.IBillingService {
        
        public BillingServiceClient() {
        }
        
        public BillingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.BillingsResult Save(string SessionKey, Rac.VOne.Web.Models.Billing[] billings) {
            return base.Channel.Save(SessionKey, billings);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Billing[] billings) {
            return base.Channel.SaveAsync(SessionKey, billings);
        }
        
        public Rac.VOne.Web.Models.BillingsResult SaveForInput(string SessionKey, Rac.VOne.Web.Models.Billing[] billings) {
            return base.Channel.SaveForInput(SessionKey, billings);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> SaveForInputAsync(string SessionKey, Rac.VOne.Web.Models.Billing[] billings) {
            return base.Channel.SaveForInputAsync(SessionKey, billings);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, long[] Id, int UseLongTermAdvanceReceived, int RegisterContractInAdvance, int UseDiscount, int LoginUserId) {
            return base.Channel.Delete(SessionKey, Id, UseLongTermAdvanceReceived, RegisterContractInAdvance, UseDiscount, LoginUserId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, long[] Id, int UseLongTermAdvanceReceived, int RegisterContractInAdvance, int UseDiscount, int LoginUserId) {
            return base.Channel.DeleteAsync(SessionKey, Id, UseLongTermAdvanceReceived, RegisterContractInAdvance, UseDiscount, LoginUserId);
        }
        
        public Rac.VOne.Web.Models.CountResult DeleteByInputId(string SessionKey, long InputId, int UseLongTermAdvanceReceived, int RegisterContractInAdvance, int UseDiscount, int LoginUserId) {
            return base.Channel.DeleteByInputId(SessionKey, InputId, UseLongTermAdvanceReceived, RegisterContractInAdvance, UseDiscount, LoginUserId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteByInputIdAsync(string SessionKey, long InputId, int UseLongTermAdvanceReceived, int RegisterContractInAdvance, int UseDiscount, int LoginUserId) {
            return base.Channel.DeleteByInputIdAsync(SessionKey, InputId, UseLongTermAdvanceReceived, RegisterContractInAdvance, UseDiscount, LoginUserId);
        }
        
        public Rac.VOne.Web.Models.BillingResult Get(string SessionKey, long[] Id) {
            return base.Channel.Get(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingResult> GetAsync(string SessionKey, long[] Id) {
            return base.Channel.GetAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.BillingsResult GetItems(string SessionKey, Rac.VOne.Web.Models.BillingSearch BillingSearch) {
            return base.Channel.GetItems(SessionKey, BillingSearch);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> GetItemsAsync(string SessionKey, Rac.VOne.Web.Models.BillingSearch BillingSearch) {
            return base.Channel.GetItemsAsync(SessionKey, BillingSearch);
        }
        
        public Rac.VOne.Web.Models.BillingsResult InputScheduledPayment(string sessionKey, Rac.VOne.Web.Models.Billing[] billings) {
            return base.Channel.InputScheduledPayment(sessionKey, billings);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> InputScheduledPaymentAsync(string sessionKey, Rac.VOne.Web.Models.Billing[] billings) {
            return base.Channel.InputScheduledPaymentAsync(sessionKey, billings);
        }
        
        public Rac.VOne.Web.Models.CountResult SaveMemo(string SessionKey, long Id, string Memo) {
            return base.Channel.SaveMemo(SessionKey, Id, Memo);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> SaveMemoAsync(string SessionKey, long Id, string Memo) {
            return base.Channel.SaveMemoAsync(SessionKey, Id, Memo);
        }
        
        public Rac.VOne.Web.Models.CountResult DeleteMemo(string SessionKey, long Id) {
            return base.Channel.DeleteMemo(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteMemoAsync(string SessionKey, long Id) {
            return base.Channel.DeleteMemoAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.BillMemoResult GetMemo(string SessionKey, long Id) {
            return base.Channel.GetMemo(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillMemoResult> GetMemoAsync(string SessionKey, long Id) {
            return base.Channel.GetMemoAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.CountResult SaveDiscount(string SessionKey, Rac.VOne.Web.Models.BillingDiscount BillingDiscount) {
            return base.Channel.SaveDiscount(SessionKey, BillingDiscount);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> SaveDiscountAsync(string SessionKey, Rac.VOne.Web.Models.BillingDiscount BillingDiscount) {
            return base.Channel.SaveDiscountAsync(SessionKey, BillingDiscount);
        }
        
        public Rac.VOne.Web.Models.CountResult DeleteDiscount(string SessionKey, long BillingId) {
            return base.Channel.DeleteDiscount(SessionKey, BillingId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteDiscountAsync(string SessionKey, long BillingId) {
            return base.Channel.DeleteDiscountAsync(SessionKey, BillingId);
        }
        
        public Rac.VOne.Web.Models.BillingDiscountsResult GetDiscount(string SessionKey, long BillingId) {
            return base.Channel.GetDiscount(SessionKey, BillingId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingDiscountsResult> GetDiscountAsync(string SessionKey, long BillingId) {
            return base.Channel.GetDiscountAsync(SessionKey, BillingId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistAccountTitle(string SessionKey, int AccountTitleId) {
            return base.Channel.ExistAccountTitle(SessionKey, AccountTitleId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistAccountTitleAsync(string SessionKey, int AccountTitleId) {
            return base.Channel.ExistAccountTitleAsync(SessionKey, AccountTitleId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistCollectCategory(string SessionKey, int CategoryId) {
            return base.Channel.ExistCollectCategory(SessionKey, CategoryId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCollectCategoryAsync(string SessionKey, int CategoryId) {
            return base.Channel.ExistCollectCategoryAsync(SessionKey, CategoryId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistCustomer(string SessionKey, int CustomerId) {
            return base.Channel.ExistCustomer(SessionKey, CustomerId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCustomerAsync(string SessionKey, int CustomerId) {
            return base.Channel.ExistCustomerAsync(SessionKey, CustomerId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistBillingCategory(string SessionKey, int CategoryId) {
            return base.Channel.ExistBillingCategory(SessionKey, CategoryId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistBillingCategoryAsync(string SessionKey, int CategoryId) {
            return base.Channel.ExistBillingCategoryAsync(SessionKey, CategoryId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistStaff(string SessionKey, int StaffId) {
            return base.Channel.ExistStaff(SessionKey, StaffId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistStaffAsync(string SessionKey, int StaffId) {
            return base.Channel.ExistStaffAsync(SessionKey, StaffId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistCurrency(string SessionKey, int CurrencyId) {
            return base.Channel.ExistCurrency(SessionKey, CurrencyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCurrencyAsync(string SessionKey, int CurrencyId) {
            return base.Channel.ExistCurrencyAsync(SessionKey, CurrencyId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistDepartment(string SessionKey, int DepartmentId) {
            return base.Channel.ExistDepartment(SessionKey, DepartmentId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistDepartmentAsync(string SessionKey, int DepartmentId) {
            return base.Channel.ExistDepartmentAsync(SessionKey, DepartmentId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistDestination(string SessionKey, int DestinationId) {
            return base.Channel.ExistDestination(SessionKey, DestinationId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistDestinationAsync(string SessionKey, int DestinationId) {
            return base.Channel.ExistDestinationAsync(SessionKey, DestinationId);
        }
        
        public Rac.VOne.Web.Models.ScheduledPaymentImportResult ImportScheduledPayment(string SessionKey, int CompanyId, int LoginUserId, int ImporterSettingId, Rac.VOne.Web.Models.ScheduledPaymentImport[] SchedulePayment) {
            return base.Channel.ImportScheduledPayment(SessionKey, CompanyId, LoginUserId, ImporterSettingId, SchedulePayment);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ScheduledPaymentImportResult> ImportScheduledPaymentAsync(string SessionKey, int CompanyId, int LoginUserId, int ImporterSettingId, Rac.VOne.Web.Models.ScheduledPaymentImport[] SchedulePayment) {
            return base.Channel.ImportScheduledPaymentAsync(SessionKey, CompanyId, LoginUserId, ImporterSettingId, SchedulePayment);
        }
        
        public Rac.VOne.Web.Models.CountResult Omit(string SessionKey, int doDelete, int loginUserId, Rac.VOne.Web.Models.Transaction[] transactions) {
            return base.Channel.Omit(SessionKey, doDelete, loginUserId, transactions);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> OmitAsync(string SessionKey, int doDelete, int loginUserId, Rac.VOne.Web.Models.Transaction[] transactions) {
            return base.Channel.OmitAsync(SessionKey, doDelete, loginUserId, transactions);
        }
        
        public Rac.VOne.Web.Models.BillingsResult GetItemsForScheduledPaymentImport(string SessionKey, int CompanyId, Rac.VOne.Web.Models.ScheduledPaymentImport[] SchedulePayment, Rac.VOne.Web.Models.ImporterSettingDetail[] details) {
            return base.Channel.GetItemsForScheduledPaymentImport(SessionKey, CompanyId, SchedulePayment, details);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> GetItemsForScheduledPaymentImportAsync(string SessionKey, int CompanyId, Rac.VOne.Web.Models.ScheduledPaymentImport[] SchedulePayment, Rac.VOne.Web.Models.ImporterSettingDetail[] details) {
            return base.Channel.GetItemsForScheduledPaymentImportAsync(SessionKey, CompanyId, SchedulePayment, details);
        }
        
        public Rac.VOne.Web.Models.BillingImportResult Import(string SessionKey, int CompanyId, int LoginUserId, int ImporterSettingId, Rac.VOne.Web.Models.BillingImport[] billingImport) {
            return base.Channel.Import(SessionKey, CompanyId, LoginUserId, ImporterSettingId, billingImport);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingImportResult> ImportAsync(string SessionKey, int CompanyId, int LoginUserId, int ImporterSettingId, Rac.VOne.Web.Models.BillingImport[] billingImport) {
            return base.Channel.ImportAsync(SessionKey, CompanyId, LoginUserId, ImporterSettingId, billingImport);
        }
        
        public Rac.VOne.Web.Models.BillingImportDuplicationResult BillingImportDuplicationCheck(string SessionKey, int CompanyId, Rac.VOne.Web.Models.BillingImportDuplicationWithCode[] BillingImportDuplication, Rac.VOne.Web.Models.ImporterSettingDetail[] ImporterSettingDetail) {
            return base.Channel.BillingImportDuplicationCheck(SessionKey, CompanyId, BillingImportDuplication, ImporterSettingDetail);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingImportDuplicationResult> BillingImportDuplicationCheckAsync(string SessionKey, int CompanyId, Rac.VOne.Web.Models.BillingImportDuplicationWithCode[] BillingImportDuplication, Rac.VOne.Web.Models.ImporterSettingDetail[] ImporterSettingDetail) {
            return base.Channel.BillingImportDuplicationCheckAsync(SessionKey, CompanyId, BillingImportDuplication, ImporterSettingDetail);
        }
        
        public Rac.VOne.Web.Models.JournalizingSummariesResult GetBillingJournalizingSummary(string SessionKey, int OutputFlg, int CompanyId, int CurrencyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo) {
            return base.Channel.GetBillingJournalizingSummary(SessionKey, OutputFlg, CompanyId, CurrencyId, BilledAtFrom, BilledAtTo);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.JournalizingSummariesResult> GetBillingJournalizingSummaryAsync(string SessionKey, int OutputFlg, int CompanyId, int CurrencyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo) {
            return base.Channel.GetBillingJournalizingSummaryAsync(SessionKey, OutputFlg, CompanyId, CurrencyId, BilledAtFrom, BilledAtTo);
        }
        
        public Rac.VOne.Web.Models.BillingJournalizingsResult ExtractBillingJournalizing(string SessionKey, int CompanyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo, int CurrencyId, System.DateTime[] OutputAt) {
            return base.Channel.ExtractBillingJournalizing(SessionKey, CompanyId, BilledAtFrom, BilledAtTo, CurrencyId, OutputAt);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingJournalizingsResult> ExtractBillingJournalizingAsync(string SessionKey, int CompanyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo, int CurrencyId, System.DateTime[] OutputAt) {
            return base.Channel.ExtractBillingJournalizingAsync(SessionKey, CompanyId, BilledAtFrom, BilledAtTo, CurrencyId, OutputAt);
        }
        
        public Rac.VOne.Web.Models.BillingsResult UpdateOutputAt(string SessionKey, int CompanyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo, int CurrencyId, int LoginUserId) {
            return base.Channel.UpdateOutputAt(SessionKey, CompanyId, BilledAtFrom, BilledAtTo, CurrencyId, LoginUserId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> UpdateOutputAtAsync(string SessionKey, int CompanyId, System.Nullable<System.DateTime> BilledAtFrom, System.Nullable<System.DateTime> BilledAtTo, int CurrencyId, int LoginUserId) {
            return base.Channel.UpdateOutputAtAsync(SessionKey, CompanyId, BilledAtFrom, BilledAtTo, CurrencyId, LoginUserId);
        }
        
        public Rac.VOne.Web.Models.BillingsResult CancelBillingJournalizing(string SessionKey, int CompanyId, int CurrencyId, System.DateTime[] OutputAt, int LoginUserId) {
            return base.Channel.CancelBillingJournalizing(SessionKey, CompanyId, CurrencyId, OutputAt, LoginUserId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> CancelBillingJournalizingAsync(string SessionKey, int CompanyId, int CurrencyId, System.DateTime[] OutputAt, int LoginUserId) {
            return base.Channel.CancelBillingJournalizingAsync(SessionKey, CompanyId, CurrencyId, OutputAt, LoginUserId);
        }
        
        public Rac.VOne.Web.Models.BillingsResult GetAccountTransferMatchingTargetList(string sessionKey, int companyId, int paymentAgencyId, System.DateTime transferDate) {
            return base.Channel.GetAccountTransferMatchingTargetList(sessionKey, companyId, paymentAgencyId, transferDate);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> GetAccountTransferMatchingTargetListAsync(string sessionKey, int companyId, int paymentAgencyId, System.DateTime transferDate) {
            return base.Channel.GetAccountTransferMatchingTargetListAsync(sessionKey, companyId, paymentAgencyId, transferDate);
        }
        
        public Rac.VOne.Web.Models.AccountTransferImportResult ImportAccountTransferResult(string sessionKey, Rac.VOne.Web.Models.AccountTransferImportData[] importDataList, System.Nullable<int> dueDateOffset, System.Nullable<int> collectCategoryId) {
            return base.Channel.ImportAccountTransferResult(sessionKey, importDataList, dueDateOffset, collectCategoryId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.AccountTransferImportResult> ImportAccountTransferResultAsync(string sessionKey, Rac.VOne.Web.Models.AccountTransferImportData[] importDataList, System.Nullable<int> dueDateOffset, System.Nullable<int> collectCategoryId) {
            return base.Channel.ImportAccountTransferResultAsync(sessionKey, importDataList, dueDateOffset, collectCategoryId);
        }
        
        public Rac.VOne.Web.Models.BillingDueAtModifyResults GetDueAtModifyItems(string sessionKey, Rac.VOne.Web.Models.BillingSearch option) {
            return base.Channel.GetDueAtModifyItems(sessionKey, option);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingDueAtModifyResults> GetDueAtModifyItemsAsync(string sessionKey, Rac.VOne.Web.Models.BillingSearch option) {
            return base.Channel.GetDueAtModifyItemsAsync(sessionKey, option);
        }
        
        public Rac.VOne.Web.Models.BillingsResult UpdateDueAt(string sessionKey, Rac.VOne.Web.Models.BillingDueAtModify[] billings) {
            return base.Channel.UpdateDueAt(sessionKey, billings);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> UpdateDueAtAsync(string sessionKey, Rac.VOne.Web.Models.BillingDueAtModify[] billings) {
            return base.Channel.UpdateDueAtAsync(sessionKey, billings);
        }
    }
}
