//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.BankBranchMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankBranchMasterService.IBankBranchMaster")]
    public interface IBankBranchMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBranchMaster/Get", ReplyAction="http://tempuri.org/IBankBranchMaster/GetResponse")]
        Rac.VOne.Web.Models.BankBranchResult Get(string Sessionkey, int CompanyId, string BankCode, string BranchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBranchMaster/Get", ReplyAction="http://tempuri.org/IBankBranchMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BankBranchResult> GetAsync(string Sessionkey, int CompanyId, string BankCode, string BranchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBranchMaster/Save", ReplyAction="http://tempuri.org/IBankBranchMaster/SaveResponse")]
        Rac.VOne.Web.Models.BankBranchResult Save(string Sessionkey, Rac.VOne.Web.Models.BankBranch BankBranch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBranchMaster/Save", ReplyAction="http://tempuri.org/IBankBranchMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BankBranchResult> SaveAsync(string Sessionkey, Rac.VOne.Web.Models.BankBranch BankBranch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBranchMaster/Delete", ReplyAction="http://tempuri.org/IBankBranchMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string Sessionkey, int CompanyId, string BankCode, string BranchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBranchMaster/Delete", ReplyAction="http://tempuri.org/IBankBranchMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string Sessionkey, int CompanyId, string BankCode, string BranchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBranchMaster/GetItems", ReplyAction="http://tempuri.org/IBankBranchMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.BankBranchsResult GetItems(string Sessionkey, int CompanyId, Rac.VOne.Web.Models.BankBranchSearch BankBranchSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBranchMaster/GetItems", ReplyAction="http://tempuri.org/IBankBranchMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BankBranchsResult> GetItemsAsync(string Sessionkey, int CompanyId, Rac.VOne.Web.Models.BankBranchSearch BankBranchSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBranchMaster/Import", ReplyAction="http://tempuri.org/IBankBranchMaster/ImportResponse")]
        Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.BankBranch[] insertList, Rac.VOne.Web.Models.BankBranch[] updateList, Rac.VOne.Web.Models.BankBranch[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBranchMaster/Import", ReplyAction="http://tempuri.org/IBankBranchMaster/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.BankBranch[] insertList, Rac.VOne.Web.Models.BankBranch[] updateList, Rac.VOne.Web.Models.BankBranch[] deleteList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankBranchMasterChannel : Rac.VOne.Client.Screen.BankBranchMasterService.IBankBranchMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankBranchMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.BankBranchMasterService.IBankBranchMaster>, Rac.VOne.Client.Screen.BankBranchMasterService.IBankBranchMaster {
        
        public BankBranchMasterClient() {
        }
        
        public BankBranchMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankBranchMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankBranchMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankBranchMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.BankBranchResult Get(string Sessionkey, int CompanyId, string BankCode, string BranchCode) {
            return base.Channel.Get(Sessionkey, CompanyId, BankCode, BranchCode);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BankBranchResult> GetAsync(string Sessionkey, int CompanyId, string BankCode, string BranchCode) {
            return base.Channel.GetAsync(Sessionkey, CompanyId, BankCode, BranchCode);
        }
        
        public Rac.VOne.Web.Models.BankBranchResult Save(string Sessionkey, Rac.VOne.Web.Models.BankBranch BankBranch) {
            return base.Channel.Save(Sessionkey, BankBranch);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BankBranchResult> SaveAsync(string Sessionkey, Rac.VOne.Web.Models.BankBranch BankBranch) {
            return base.Channel.SaveAsync(Sessionkey, BankBranch);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string Sessionkey, int CompanyId, string BankCode, string BranchCode) {
            return base.Channel.Delete(Sessionkey, CompanyId, BankCode, BranchCode);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string Sessionkey, int CompanyId, string BankCode, string BranchCode) {
            return base.Channel.DeleteAsync(Sessionkey, CompanyId, BankCode, BranchCode);
        }
        
        public Rac.VOne.Web.Models.BankBranchsResult GetItems(string Sessionkey, int CompanyId, Rac.VOne.Web.Models.BankBranchSearch BankBranchSearch) {
            return base.Channel.GetItems(Sessionkey, CompanyId, BankBranchSearch);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BankBranchsResult> GetItemsAsync(string Sessionkey, int CompanyId, Rac.VOne.Web.Models.BankBranchSearch BankBranchSearch) {
            return base.Channel.GetItemsAsync(Sessionkey, CompanyId, BankBranchSearch);
        }
        
        public Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.BankBranch[] insertList, Rac.VOne.Web.Models.BankBranch[] updateList, Rac.VOne.Web.Models.BankBranch[] deleteList) {
            return base.Channel.Import(SessionKey, insertList, updateList, deleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.BankBranch[] insertList, Rac.VOne.Web.Models.BankBranch[] updateList, Rac.VOne.Web.Models.BankBranch[] deleteList) {
            return base.Channel.ImportAsync(SessionKey, insertList, updateList, deleteList);
        }
    }
}
