//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.HolidayCalendarMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HolidayCalendarMasterService.IHolidayCalendarMaster")]
    public interface IHolidayCalendarMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayCalendarMaster/Save", ReplyAction="http://tempuri.org/IHolidayCalendarMaster/SaveResponse")]
        Rac.VOne.Web.Models.HolidayCalendarResult Save(string SessionKey, Rac.VOne.Web.Models.HolidayCalendar HolidayCalendar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayCalendarMaster/Save", ReplyAction="http://tempuri.org/IHolidayCalendarMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.HolidayCalendarResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.HolidayCalendar HolidayCalendar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayCalendarMaster/Delete", ReplyAction="http://tempuri.org/IHolidayCalendarMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CompanyId, System.DateTime[] Holiday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayCalendarMaster/Delete", ReplyAction="http://tempuri.org/IHolidayCalendarMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CompanyId, System.DateTime[] Holiday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayCalendarMaster/GetItems", ReplyAction="http://tempuri.org/IHolidayCalendarMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.HolidayCalendarsResult GetItems(string SessionKey, Rac.VOne.Web.Models.HolidayCalendarSearch option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayCalendarMaster/GetItems", ReplyAction="http://tempuri.org/IHolidayCalendarMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.HolidayCalendarsResult> GetItemsAsync(string SessionKey, Rac.VOne.Web.Models.HolidayCalendarSearch option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayCalendarMaster/Import", ReplyAction="http://tempuri.org/IHolidayCalendarMaster/ImportResponse")]
        Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.HolidayCalendar[] InsertList, Rac.VOne.Web.Models.HolidayCalendar[] UpdateList, Rac.VOne.Web.Models.HolidayCalendar[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayCalendarMaster/Import", ReplyAction="http://tempuri.org/IHolidayCalendarMaster/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.HolidayCalendar[] InsertList, Rac.VOne.Web.Models.HolidayCalendar[] UpdateList, Rac.VOne.Web.Models.HolidayCalendar[] DeleteList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHolidayCalendarMasterChannel : Rac.VOne.Client.Screen.HolidayCalendarMasterService.IHolidayCalendarMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidayCalendarMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.HolidayCalendarMasterService.IHolidayCalendarMaster>, Rac.VOne.Client.Screen.HolidayCalendarMasterService.IHolidayCalendarMaster {
        
        public HolidayCalendarMasterClient() {
        }
        
        public HolidayCalendarMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidayCalendarMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayCalendarMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayCalendarMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.HolidayCalendarResult Save(string SessionKey, Rac.VOne.Web.Models.HolidayCalendar HolidayCalendar) {
            return base.Channel.Save(SessionKey, HolidayCalendar);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.HolidayCalendarResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.HolidayCalendar HolidayCalendar) {
            return base.Channel.SaveAsync(SessionKey, HolidayCalendar);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CompanyId, System.DateTime[] Holiday) {
            return base.Channel.Delete(SessionKey, CompanyId, Holiday);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CompanyId, System.DateTime[] Holiday) {
            return base.Channel.DeleteAsync(SessionKey, CompanyId, Holiday);
        }
        
        public Rac.VOne.Web.Models.HolidayCalendarsResult GetItems(string SessionKey, Rac.VOne.Web.Models.HolidayCalendarSearch option) {
            return base.Channel.GetItems(SessionKey, option);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.HolidayCalendarsResult> GetItemsAsync(string SessionKey, Rac.VOne.Web.Models.HolidayCalendarSearch option) {
            return base.Channel.GetItemsAsync(SessionKey, option);
        }
        
        public Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.HolidayCalendar[] InsertList, Rac.VOne.Web.Models.HolidayCalendar[] UpdateList, Rac.VOne.Web.Models.HolidayCalendar[] DeleteList) {
            return base.Channel.Import(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.HolidayCalendar[] InsertList, Rac.VOne.Web.Models.HolidayCalendar[] UpdateList, Rac.VOne.Web.Models.HolidayCalendar[] DeleteList) {
            return base.Channel.ImportAsync(SessionKey, InsertList, UpdateList, DeleteList);
        }
    }
}
