//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.DataMaintenanceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataMaintenanceService.IDataMaintenanceService")]
    public interface IDataMaintenanceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataMaintenanceService/DeleteData", ReplyAction="http://tempuri.org/IDataMaintenanceService/DeleteDataResponse")]
        Rac.VOne.Web.Models.CountResult DeleteData(string SessionKey, System.DateTime deleteDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataMaintenanceService/DeleteData", ReplyAction="http://tempuri.org/IDataMaintenanceService/DeleteDataResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteDataAsync(string SessionKey, System.DateTime deleteDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataMaintenanceServiceChannel : Rac.VOne.Client.Screen.DataMaintenanceService.IDataMaintenanceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataMaintenanceServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.DataMaintenanceService.IDataMaintenanceService>, Rac.VOne.Client.Screen.DataMaintenanceService.IDataMaintenanceService {
        
        public DataMaintenanceServiceClient() {
        }
        
        public DataMaintenanceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataMaintenanceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataMaintenanceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataMaintenanceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.CountResult DeleteData(string SessionKey, System.DateTime deleteDate) {
            return base.Channel.DeleteData(SessionKey, deleteDate);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteDataAsync(string SessionKey, System.DateTime deleteDate) {
            return base.Channel.DeleteDataAsync(SessionKey, deleteDate);
        }
    }
}
