//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.TaskScheduleHistoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskScheduleHistoryService.ITaskScheduleHistoryService")]
    public interface ITaskScheduleHistoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleHistoryService/GetItems", ReplyAction="http://tempuri.org/ITaskScheduleHistoryService/GetItemsResponse")]
        Rac.VOne.Web.Models.TaskScheduleHistoryResult GetItems(string SessionKey, Rac.VOne.Web.Models.TaskScheduleHistorySearch searchConditions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleHistoryService/GetItems", ReplyAction="http://tempuri.org/ITaskScheduleHistoryService/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.TaskScheduleHistoryResult> GetItemsAsync(string SessionKey, Rac.VOne.Web.Models.TaskScheduleHistorySearch searchConditions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleHistoryService/Delete", ReplyAction="http://tempuri.org/ITaskScheduleHistoryService/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleHistoryService/Delete", ReplyAction="http://tempuri.org/ITaskScheduleHistoryService/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleHistoryService/Save", ReplyAction="http://tempuri.org/ITaskScheduleHistoryService/SaveResponse")]
        Rac.VOne.Web.Models.TaskScheduleHistoryResult Save(string SessionKey, Rac.VOne.Web.Models.TaskScheduleHistory history);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleHistoryService/Save", ReplyAction="http://tempuri.org/ITaskScheduleHistoryService/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.TaskScheduleHistoryResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.TaskScheduleHistory history);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskScheduleHistoryServiceChannel : Rac.VOne.Client.Screen.TaskScheduleHistoryService.ITaskScheduleHistoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskScheduleHistoryServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.TaskScheduleHistoryService.ITaskScheduleHistoryService>, Rac.VOne.Client.Screen.TaskScheduleHistoryService.ITaskScheduleHistoryService {
        
        public TaskScheduleHistoryServiceClient() {
        }
        
        public TaskScheduleHistoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskScheduleHistoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskScheduleHistoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskScheduleHistoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.TaskScheduleHistoryResult GetItems(string SessionKey, Rac.VOne.Web.Models.TaskScheduleHistorySearch searchConditions) {
            return base.Channel.GetItems(SessionKey, searchConditions);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.TaskScheduleHistoryResult> GetItemsAsync(string SessionKey, Rac.VOne.Web.Models.TaskScheduleHistorySearch searchConditions) {
            return base.Channel.GetItemsAsync(SessionKey, searchConditions);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CompanyId) {
            return base.Channel.Delete(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CompanyId) {
            return base.Channel.DeleteAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.TaskScheduleHistoryResult Save(string SessionKey, Rac.VOne.Web.Models.TaskScheduleHistory history) {
            return base.Channel.Save(SessionKey, history);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.TaskScheduleHistoryResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.TaskScheduleHistory history) {
            return base.Channel.SaveAsync(SessionKey, history);
        }
    }
}
