//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.CustomerDiscountMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerDiscountMasterService.ICustomerDiscountMaster")]
    public interface ICustomerDiscountMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerDiscountMaster/ExistAccountTitle", ReplyAction="http://tempuri.org/ICustomerDiscountMaster/ExistAccountTitleResponse")]
        Rac.VOne.Web.Models.ExistResult ExistAccountTitle(string sessionKey, int accountTitleid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerDiscountMaster/ExistAccountTitle", ReplyAction="http://tempuri.org/ICustomerDiscountMaster/ExistAccountTitleResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistAccountTitleAsync(string sessionKey, int accountTitleid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerDiscountMaster/Import", ReplyAction="http://tempuri.org/ICustomerDiscountMaster/ImportResponse")]
        Rac.VOne.Web.Models.ImportResult Import(string sessionKey, Rac.VOne.Web.Models.CustomerDiscount[] insertList, Rac.VOne.Web.Models.CustomerDiscount[] updateList, Rac.VOne.Web.Models.CustomerDiscount[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerDiscountMaster/Import", ReplyAction="http://tempuri.org/ICustomerDiscountMaster/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string sessionKey, Rac.VOne.Web.Models.CustomerDiscount[] insertList, Rac.VOne.Web.Models.CustomerDiscount[] updateList, Rac.VOne.Web.Models.CustomerDiscount[] deleteList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerDiscountMasterChannel : Rac.VOne.Client.Screen.CustomerDiscountMasterService.ICustomerDiscountMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerDiscountMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.CustomerDiscountMasterService.ICustomerDiscountMaster>, Rac.VOne.Client.Screen.CustomerDiscountMasterService.ICustomerDiscountMaster {
        
        public CustomerDiscountMasterClient() {
        }
        
        public CustomerDiscountMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerDiscountMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerDiscountMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerDiscountMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistAccountTitle(string sessionKey, int accountTitleid) {
            return base.Channel.ExistAccountTitle(sessionKey, accountTitleid);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistAccountTitleAsync(string sessionKey, int accountTitleid) {
            return base.Channel.ExistAccountTitleAsync(sessionKey, accountTitleid);
        }
        
        public Rac.VOne.Web.Models.ImportResult Import(string sessionKey, Rac.VOne.Web.Models.CustomerDiscount[] insertList, Rac.VOne.Web.Models.CustomerDiscount[] updateList, Rac.VOne.Web.Models.CustomerDiscount[] deleteList) {
            return base.Channel.Import(sessionKey, insertList, updateList, deleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string sessionKey, Rac.VOne.Web.Models.CustomerDiscount[] insertList, Rac.VOne.Web.Models.CustomerDiscount[] updateList, Rac.VOne.Web.Models.CustomerDiscount[] deleteList) {
            return base.Channel.ImportAsync(sessionKey, insertList, updateList, deleteList);
        }
    }
}
