//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.DepartmentMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DepartmentMasterService.IDepartmentMaster")]
    public interface IDepartmentMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/Save", ReplyAction="http://tempuri.org/IDepartmentMaster/SaveResponse")]
        Rac.VOne.Web.Models.DepartmentResult Save(string SessionKey, Rac.VOne.Web.Models.Department Department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/Save", ReplyAction="http://tempuri.org/IDepartmentMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Department Department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/Delete", ReplyAction="http://tempuri.org/IDepartmentMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/Delete", ReplyAction="http://tempuri.org/IDepartmentMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/Get", ReplyAction="http://tempuri.org/IDepartmentMaster/GetResponse")]
        Rac.VOne.Web.Models.DepartmentsResult Get(string SessionKey, int[] Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/Get", ReplyAction="http://tempuri.org/IDepartmentMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetAsync(string SessionKey, int[] Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetByCode", ReplyAction="http://tempuri.org/IDepartmentMaster/GetByCodeResponse")]
        Rac.VOne.Web.Models.DepartmentsResult GetByCode(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetByCode", ReplyAction="http://tempuri.org/IDepartmentMaster/GetByCodeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetByCodeAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetByCodeAndStaff", ReplyAction="http://tempuri.org/IDepartmentMaster/GetByCodeAndStaffResponse")]
        Rac.VOne.Web.Models.DepartmentResult GetByCodeAndStaff(string SessionKey, int CompanyId, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetByCodeAndStaff", ReplyAction="http://tempuri.org/IDepartmentMaster/GetByCodeAndStaffResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentResult> GetByCodeAndStaffAsync(string SessionKey, int CompanyId, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetItems", ReplyAction="http://tempuri.org/IDepartmentMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.DepartmentsResult GetItems(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetItems", ReplyAction="http://tempuri.org/IDepartmentMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetItemsAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetDepartmentAndStaff", ReplyAction="http://tempuri.org/IDepartmentMaster/GetDepartmentAndStaffResponse")]
        Rac.VOne.Web.Models.DepartmentsResult GetDepartmentAndStaff(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetDepartmentAndStaff", ReplyAction="http://tempuri.org/IDepartmentMaster/GetDepartmentAndStaffResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetDepartmentAndStaffAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/Import", ReplyAction="http://tempuri.org/IDepartmentMaster/ImportResponse")]
        Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.Department[] InsertList, Rac.VOne.Web.Models.Department[] UpdateList, Rac.VOne.Web.Models.Department[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/Import", ReplyAction="http://tempuri.org/IDepartmentMaster/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.Department[] InsertList, Rac.VOne.Web.Models.Department[] UpdateList, Rac.VOne.Web.Models.Department[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetImportItemsStaff", ReplyAction="http://tempuri.org/IDepartmentMaster/GetImportItemsStaffResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsStaff(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetImportItemsStaff", ReplyAction="http://tempuri.org/IDepartmentMaster/GetImportItemsStaffResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsStaffAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetImportItemsSectionWithDepartment", ReplyAction="http://tempuri.org/IDepartmentMaster/GetImportItemsSectionWithDepartmentResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsSectionWithDepartment(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetImportItemsSectionWithDepartment", ReplyAction="http://tempuri.org/IDepartmentMaster/GetImportItemsSectionWithDepartmentResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsSectionWithDepartmentAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetImportItemsBilling", ReplyAction="http://tempuri.org/IDepartmentMaster/GetImportItemsBillingResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsBilling(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetImportItemsBilling", ReplyAction="http://tempuri.org/IDepartmentMaster/GetImportItemsBillingResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsBillingAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/DepartmentWithSection", ReplyAction="http://tempuri.org/IDepartmentMaster/DepartmentWithSectionResponse")]
        Rac.VOne.Web.Models.DepartmentsResult DepartmentWithSection(string SessionKey, int CompanyId, int SectionId, int[] GridDepartmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/DepartmentWithSection", ReplyAction="http://tempuri.org/IDepartmentMaster/DepartmentWithSectionResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> DepartmentWithSectionAsync(string SessionKey, int CompanyId, int SectionId, int[] GridDepartmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetWithoutSection", ReplyAction="http://tempuri.org/IDepartmentMaster/GetWithoutSectionResponse")]
        Rac.VOne.Web.Models.DepartmentsResult GetWithoutSection(string SessionKey, int CompanyId, int SectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetWithoutSection", ReplyAction="http://tempuri.org/IDepartmentMaster/GetWithoutSectionResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetWithoutSectionAsync(string SessionKey, int CompanyId, int SectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetByLoginUserId", ReplyAction="http://tempuri.org/IDepartmentMaster/GetByLoginUserIdResponse")]
        Rac.VOne.Web.Models.DepartmentsResult GetByLoginUserId(string SessionKey, int CompanyId, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentMaster/GetByLoginUserId", ReplyAction="http://tempuri.org/IDepartmentMaster/GetByLoginUserIdResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetByLoginUserIdAsync(string SessionKey, int CompanyId, int LoginUserId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepartmentMasterChannel : Rac.VOne.Client.Screen.DepartmentMasterService.IDepartmentMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartmentMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.DepartmentMasterService.IDepartmentMaster>, Rac.VOne.Client.Screen.DepartmentMasterService.IDepartmentMaster {
        
        public DepartmentMasterClient() {
        }
        
        public DepartmentMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartmentMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.DepartmentResult Save(string SessionKey, Rac.VOne.Web.Models.Department Department) {
            return base.Channel.Save(SessionKey, Department);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Department Department) {
            return base.Channel.SaveAsync(SessionKey, Department);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int Id) {
            return base.Channel.Delete(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int Id) {
            return base.Channel.DeleteAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.DepartmentsResult Get(string SessionKey, int[] Id) {
            return base.Channel.Get(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetAsync(string SessionKey, int[] Id) {
            return base.Channel.GetAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.DepartmentsResult GetByCode(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetByCode(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetByCodeAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetByCodeAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.DepartmentResult GetByCodeAndStaff(string SessionKey, int CompanyId, string Code) {
            return base.Channel.GetByCodeAndStaff(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentResult> GetByCodeAndStaffAsync(string SessionKey, int CompanyId, string Code) {
            return base.Channel.GetByCodeAndStaffAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.DepartmentsResult GetItems(string SessionKey, int CompanyId) {
            return base.Channel.GetItems(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetItemsAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.DepartmentsResult GetDepartmentAndStaff(string SessionKey, int CompanyId) {
            return base.Channel.GetDepartmentAndStaff(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetDepartmentAndStaffAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetDepartmentAndStaffAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.Department[] InsertList, Rac.VOne.Web.Models.Department[] UpdateList, Rac.VOne.Web.Models.Department[] DeleteList) {
            return base.Channel.Import(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.Department[] InsertList, Rac.VOne.Web.Models.Department[] UpdateList, Rac.VOne.Web.Models.Department[] DeleteList) {
            return base.Channel.ImportAsync(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsStaff(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsStaff(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsStaffAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsStaffAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsSectionWithDepartment(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsSectionWithDepartment(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsSectionWithDepartmentAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsSectionWithDepartmentAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsBilling(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsBilling(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsBillingAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsBillingAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.DepartmentsResult DepartmentWithSection(string SessionKey, int CompanyId, int SectionId, int[] GridDepartmentId) {
            return base.Channel.DepartmentWithSection(SessionKey, CompanyId, SectionId, GridDepartmentId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> DepartmentWithSectionAsync(string SessionKey, int CompanyId, int SectionId, int[] GridDepartmentId) {
            return base.Channel.DepartmentWithSectionAsync(SessionKey, CompanyId, SectionId, GridDepartmentId);
        }
        
        public Rac.VOne.Web.Models.DepartmentsResult GetWithoutSection(string SessionKey, int CompanyId, int SectionId) {
            return base.Channel.GetWithoutSection(SessionKey, CompanyId, SectionId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetWithoutSectionAsync(string SessionKey, int CompanyId, int SectionId) {
            return base.Channel.GetWithoutSectionAsync(SessionKey, CompanyId, SectionId);
        }
        
        public Rac.VOne.Web.Models.DepartmentsResult GetByLoginUserId(string SessionKey, int CompanyId, int LoginUserId) {
            return base.Channel.GetByLoginUserId(SessionKey, CompanyId, LoginUserId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.DepartmentsResult> GetByLoginUserIdAsync(string SessionKey, int CompanyId, int LoginUserId) {
            return base.Channel.GetByLoginUserIdAsync(SessionKey, CompanyId, LoginUserId);
        }
    }
}
