//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.LoginUserMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginUserMasterService.ILoginUserMaster")]
    public interface ILoginUserMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/Get", ReplyAction="http://tempuri.org/ILoginUserMaster/GetResponse")]
        Rac.VOne.Web.Models.UsersResult Get(string SessionKey, int[] Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/Get", ReplyAction="http://tempuri.org/ILoginUserMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.UsersResult> GetAsync(string SessionKey, int[] Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/Save", ReplyAction="http://tempuri.org/ILoginUserMaster/SaveResponse")]
        Rac.VOne.Web.Models.UserResult Save(string SessionKey, Rac.VOne.Web.Models.LoginUser UserData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/Save", ReplyAction="http://tempuri.org/ILoginUserMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.UserResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.LoginUser UserData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/GetItems", ReplyAction="http://tempuri.org/ILoginUserMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.UsersResult GetItems(string SessionKey, int CompanyId, Rac.VOne.Web.Models.LoginUserSearch LoginUserSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/GetItems", ReplyAction="http://tempuri.org/ILoginUserMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.UsersResult> GetItemsAsync(string SessionKey, int CompanyId, Rac.VOne.Web.Models.LoginUserSearch LoginUserSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/ResetPassword", ReplyAction="http://tempuri.org/ILoginUserMaster/ResetPasswordResponse")]
        Rac.VOne.Web.Models.CountResult ResetPassword(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/ResetPassword", ReplyAction="http://tempuri.org/ILoginUserMaster/ResetPasswordResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> ResetPasswordAsync(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/ExitStaff", ReplyAction="http://tempuri.org/ILoginUserMaster/ExitStaffResponse")]
        Rac.VOne.Web.Models.CountResult ExitStaff(string SessionKey, int StaffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/ExitStaff", ReplyAction="http://tempuri.org/ILoginUserMaster/ExitStaffResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> ExitStaffAsync(string SessionKey, int StaffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/Delete", ReplyAction="http://tempuri.org/ILoginUserMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/Delete", ReplyAction="http://tempuri.org/ILoginUserMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/GetByCode", ReplyAction="http://tempuri.org/ILoginUserMaster/GetByCodeResponse")]
        Rac.VOne.Web.Models.UsersResult GetByCode(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/GetByCode", ReplyAction="http://tempuri.org/ILoginUserMaster/GetByCodeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.UsersResult> GetByCodeAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/Import", ReplyAction="http://tempuri.org/ILoginUserMaster/ImportResponse")]
        Rac.VOne.Web.Models.ImportResultLoginUser Import(string SessionKey, int CompanyId, int LoginUserId, Rac.VOne.Web.Models.LoginUser[] InsertList, Rac.VOne.Web.Models.LoginUser[] UpdateList, Rac.VOne.Web.Models.LoginUser[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/Import", ReplyAction="http://tempuri.org/ILoginUserMaster/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResultLoginUser> ImportAsync(string SessionKey, int CompanyId, int LoginUserId, Rac.VOne.Web.Models.LoginUser[] InsertList, Rac.VOne.Web.Models.LoginUser[] UpdateList, Rac.VOne.Web.Models.LoginUser[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/GetImportItemsForSection", ReplyAction="http://tempuri.org/ILoginUserMaster/GetImportItemsForSectionResponse")]
        Rac.VOne.Web.Models.UsersResult GetImportItemsForSection(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/GetImportItemsForSection", ReplyAction="http://tempuri.org/ILoginUserMaster/GetImportItemsForSectionResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.UsersResult> GetImportItemsForSectionAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/GetItemsForGridLoader", ReplyAction="http://tempuri.org/ILoginUserMaster/GetItemsForGridLoaderResponse")]
        Rac.VOne.Web.Models.UsersResult GetItemsForGridLoader(string Sessionkey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserMaster/GetItemsForGridLoader", ReplyAction="http://tempuri.org/ILoginUserMaster/GetItemsForGridLoaderResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.UsersResult> GetItemsForGridLoaderAsync(string Sessionkey, int CompanyId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginUserMasterChannel : Rac.VOne.Client.Screen.LoginUserMasterService.ILoginUserMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginUserMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.LoginUserMasterService.ILoginUserMaster>, Rac.VOne.Client.Screen.LoginUserMasterService.ILoginUserMaster {
        
        public LoginUserMasterClient() {
        }
        
        public LoginUserMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginUserMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginUserMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginUserMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.UsersResult Get(string SessionKey, int[] Id) {
            return base.Channel.Get(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.UsersResult> GetAsync(string SessionKey, int[] Id) {
            return base.Channel.GetAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.UserResult Save(string SessionKey, Rac.VOne.Web.Models.LoginUser UserData) {
            return base.Channel.Save(SessionKey, UserData);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.UserResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.LoginUser UserData) {
            return base.Channel.SaveAsync(SessionKey, UserData);
        }
        
        public Rac.VOne.Web.Models.UsersResult GetItems(string SessionKey, int CompanyId, Rac.VOne.Web.Models.LoginUserSearch LoginUserSearch) {
            return base.Channel.GetItems(SessionKey, CompanyId, LoginUserSearch);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.UsersResult> GetItemsAsync(string SessionKey, int CompanyId, Rac.VOne.Web.Models.LoginUserSearch LoginUserSearch) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId, LoginUserSearch);
        }
        
        public Rac.VOne.Web.Models.CountResult ResetPassword(string SessionKey, int Id) {
            return base.Channel.ResetPassword(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> ResetPasswordAsync(string SessionKey, int Id) {
            return base.Channel.ResetPasswordAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.CountResult ExitStaff(string SessionKey, int StaffId) {
            return base.Channel.ExitStaff(SessionKey, StaffId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> ExitStaffAsync(string SessionKey, int StaffId) {
            return base.Channel.ExitStaffAsync(SessionKey, StaffId);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int Id) {
            return base.Channel.Delete(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int Id) {
            return base.Channel.DeleteAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.UsersResult GetByCode(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetByCode(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.UsersResult> GetByCodeAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetByCodeAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.ImportResultLoginUser Import(string SessionKey, int CompanyId, int LoginUserId, Rac.VOne.Web.Models.LoginUser[] InsertList, Rac.VOne.Web.Models.LoginUser[] UpdateList, Rac.VOne.Web.Models.LoginUser[] DeleteList) {
            return base.Channel.Import(SessionKey, CompanyId, LoginUserId, InsertList, UpdateList, DeleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResultLoginUser> ImportAsync(string SessionKey, int CompanyId, int LoginUserId, Rac.VOne.Web.Models.LoginUser[] InsertList, Rac.VOne.Web.Models.LoginUser[] UpdateList, Rac.VOne.Web.Models.LoginUser[] DeleteList) {
            return base.Channel.ImportAsync(SessionKey, CompanyId, LoginUserId, InsertList, UpdateList, DeleteList);
        }
        
        public Rac.VOne.Web.Models.UsersResult GetImportItemsForSection(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForSection(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.UsersResult> GetImportItemsForSectionAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForSectionAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.UsersResult GetItemsForGridLoader(string Sessionkey, int CompanyId) {
            return base.Channel.GetItemsForGridLoader(Sessionkey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.UsersResult> GetItemsForGridLoaderAsync(string Sessionkey, int CompanyId) {
            return base.Channel.GetItemsForGridLoaderAsync(Sessionkey, CompanyId);
        }
    }
}
