//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.MFBillingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MFBillingService.IMFBillingService")]
    public interface IMFBillingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMFBillingService/SavingSet", ReplyAction="http://tempuri.org/IMFBillingService/SavingSetResponse")]
        Rac.VOne.Web.Models.BillingsResult SavingSet(string SessionKey, Rac.VOne.Web.Models.Billing[] billings, Rac.VOne.Web.Models.Customer[] customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMFBillingService/SavingSet", ReplyAction="http://tempuri.org/IMFBillingService/SavingSetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> SavingSetAsync(string SessionKey, Rac.VOne.Web.Models.Billing[] billings, Rac.VOne.Web.Models.Customer[] customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMFBillingService/GetItems", ReplyAction="http://tempuri.org/IMFBillingService/GetItemsResponse")]
        Rac.VOne.Web.Models.MFBillingsResult GetItems(string SessionKey, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMFBillingService/GetItems", ReplyAction="http://tempuri.org/IMFBillingService/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MFBillingsResult> GetItemsAsync(string SessionKey, int companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMFBillingService/GetByBillingIds", ReplyAction="http://tempuri.org/IMFBillingService/GetByBillingIdsResponse")]
        Rac.VOne.Web.Models.MFBillingsResult GetByBillingIds(string sessionKey, long[] ids, bool isMatched);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMFBillingService/GetByBillingIds", ReplyAction="http://tempuri.org/IMFBillingService/GetByBillingIdsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MFBillingsResult> GetByBillingIdsAsync(string sessionKey, long[] ids, bool isMatched);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMFBillingServiceChannel : Rac.VOne.Client.Screen.MFBillingService.IMFBillingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MFBillingServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.MFBillingService.IMFBillingService>, Rac.VOne.Client.Screen.MFBillingService.IMFBillingService {
        
        public MFBillingServiceClient() {
        }
        
        public MFBillingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MFBillingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MFBillingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MFBillingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.BillingsResult SavingSet(string SessionKey, Rac.VOne.Web.Models.Billing[] billings, Rac.VOne.Web.Models.Customer[] customers) {
            return base.Channel.SavingSet(SessionKey, billings, customers);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.BillingsResult> SavingSetAsync(string SessionKey, Rac.VOne.Web.Models.Billing[] billings, Rac.VOne.Web.Models.Customer[] customers) {
            return base.Channel.SavingSetAsync(SessionKey, billings, customers);
        }
        
        public Rac.VOne.Web.Models.MFBillingsResult GetItems(string SessionKey, int companyId) {
            return base.Channel.GetItems(SessionKey, companyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MFBillingsResult> GetItemsAsync(string SessionKey, int companyId) {
            return base.Channel.GetItemsAsync(SessionKey, companyId);
        }
        
        public Rac.VOne.Web.Models.MFBillingsResult GetByBillingIds(string sessionKey, long[] ids, bool isMatched) {
            return base.Channel.GetByBillingIds(sessionKey, ids, isMatched);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MFBillingsResult> GetByBillingIdsAsync(string sessionKey, long[] ids, bool isMatched) {
            return base.Channel.GetByBillingIdsAsync(sessionKey, ids, isMatched);
        }
    }
}
