namespace Rac.VOne.Common.Importer.Customer
{
    public enum Fields
    {
        ///<summary>会社コード</summary>
        CompanyCode = 1,
        ///<summary>得意先コード</summary>
        CustomerCode,
        ///<summary>得意先名</summary>
        CustomerName,
        ///<summary>得意先名カナ</summary>
        CustomerKana,
        ///<summary>専用銀行コード</summary>
        ExclusiveBankCode,
        ///<summary>専用銀行名</summary>
        ExclusiveBankName,
        ///<summary>専用支店コード</summary>
        ExclusiveBranchCode,
        ///<summary>仮想支店名</summary>
        ExclusiveBranchName,
        ///<summary>専用入金口座番号</summary>
        ExclusiveAccountNumber,
        ///<summary>預金種別</summary>
        ExclusiveAccountTypeId,
        ///<summary>手数料負担区分</summary>
        ShareTransferFee,
        ///<summary>与信限度額</summary>
        CreditLimit,
        ///<summary>締日</summary>
        ClosingDay,
        ///<summary>回収方法</summary>
        CollectCategoryId,
        ///<summary>回収予定（月）</summary>
        CollectOffsetMonth,
        ///<summary>回収予定（日）</summary>
        CollectOffsetDay,
        /// <summary>回収予定（都度請求）</summary>
        CollectOffsetDayPerBilling,
        ///<summary>営業担当者</summary>
        StaffCode,
        ///<summary>債権代表者フラグ</summary>
        IsParent,
        ///<summary>郵便番号</summary>
        PostalCode,
        ///<summary>住所1</summary>
        Address1,
        ///<summary>住所2</summary>
        Address2,
        ///<summary>TEL番号</summary>
        Tel,
        ///<summary>FAX番号</summary>
        Fax,
        ///<summary>相手先担当者名</summary>
        CustomerStaffName,
        ///<summary>備考</summary>
        Note,
        ///<summary>手数料自動学習</summary>
        UseFeeLearning,
        ///<summary>回収サイト</summary>
        SightOfBill,
        ///<summary>電子手形用企業コード</summary>
        DensaiCode,
        ///<summary>信用調査用企業コード</summary>
        CreditCode,
        ///<summary>与信ランク</summary>
        CreditRank,
        ///<summary>口座振替用銀行コード</summary>
        TransferBankCode,
        ///<summary>口座振替用銀行名</summary>
        TransferBankName,
        ///<summary>口座振替用支店コード</summary>
        TransferBranchCode,
        ///<summary>口座振替用支店名</summary>
        TransferBranchName,
        ///<summary>口座振替用口座番号</summary>
        TransferAccountNumber,
        ///<summary>口座振替用預金種目</summary>
        TransferAccountTypeId,
        ///<summary>口座振替用顧客コード</summary>
        TransferCustomerCode,
        ///<summary>口座振替用新規コード</summary>
        TransferNewCode,
        ///<summary>口座振替用預金者名</summary>
        TransferAccountName,
        ///<summary>約定金額</summary>
        ThresholdValue,
        ///<summary>約定金額未満</summary>
        LessThanCollectCategoryId,
        ///<summary>約定金額以上1</summary>
        GreaterThanCollectCategoryId1,
        ///<summary>分割1</summary>
        GreaterThanRate1,
        ///<summary>端数1</summary>
        GreaterThanRoundingMode1,
        ///<summary>回収サイト1</summary>
        GreaterThanSightOfBill1,
        ///<summary>約定金額以上2</summary>
        GreaterThanCollectCategoryId2,
        ///<summary>分割2</summary>
        GreaterThanRate2,
        ///<summary>端数2</summary>
        GreaterThanRoundingMode2,
        ///<summary>回収サイト2</summary>
        GreaterThanSightOfBill2,
        ///<summary>約定金額以上3</summary>
        GreaterThanCollectCategoryId3,
        ///<summary>分割3</summary>
        GreaterThanRate3,
        ///<summary>端数3</summary>
        GreaterThanRoundingMode3,
        ///<summary>回収サイト3</summary>
        GreaterThanSightOfBill3,
        ///<summary>カナ自動学習</summary>
        UseKanaLearning,
        ///<summary>休業日の設定</summary>
        HolidayFlag,
        ///<summary>手数料誤差利用</summary>
        UseFeeTolerance,
        ///<summary>一括消込対象外（個別消込優先）</summary>
        PrioritizeMatchingIndividually,
        ///<summary>照合番号</summary>
        CollationKey,
        ///<summary>請求書発行対象外</summary>
        ExcludeInvoicePublish,
        ///<summary>督促状発行対象外</summary>
        ExcludeReminderPublish,
        ///<summary>相手先部署</summary>
        DestinationDepartmentName,
        ///<summary>敬称</summary>
        Honorific,
    }
}