//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.SectionMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SectionMasterService.ISectionMaster")]
    public interface ISectionMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetByLoginUserId", ReplyAction="http://tempuri.org/ISectionMaster/GetByLoginUserIdResponse")]
        Rac.VOne.Web.Models.SectionsResult GetByLoginUserId(string SessionKey, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetByLoginUserId", ReplyAction="http://tempuri.org/ISectionMaster/GetByLoginUserIdResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionsResult> GetByLoginUserIdAsync(string SessionKey, int LoginUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetByCode", ReplyAction="http://tempuri.org/ISectionMaster/GetByCodeResponse")]
        Rac.VOne.Web.Models.SectionsResult GetByCode(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetByCode", ReplyAction="http://tempuri.org/ISectionMaster/GetByCodeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionsResult> GetByCodeAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/Save", ReplyAction="http://tempuri.org/ISectionMaster/SaveResponse")]
        Rac.VOne.Web.Models.SectionResults Save(string SessionKey, Rac.VOne.Web.Models.Section Section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/Save", ReplyAction="http://tempuri.org/ISectionMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionResults> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Section Section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/Delete", ReplyAction="http://tempuri.org/ISectionMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/Delete", ReplyAction="http://tempuri.org/ISectionMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetItems", ReplyAction="http://tempuri.org/ISectionMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.SectionsResult GetItems(string SessionKey, int CompanyId, Rac.VOne.Web.Models.SectionSearch SectionSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetItems", ReplyAction="http://tempuri.org/ISectionMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionsResult> GetItemsAsync(string SessionKey, int CompanyId, Rac.VOne.Web.Models.SectionSearch SectionSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetByCustomerId", ReplyAction="http://tempuri.org/ISectionMaster/GetByCustomerIdResponse")]
        Rac.VOne.Web.Models.SectionResult GetByCustomerId(string SessionKey, int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetByCustomerId", ReplyAction="http://tempuri.org/ISectionMaster/GetByCustomerIdResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionResult> GetByCustomerIdAsync(string SessionKey, int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/Import", ReplyAction="http://tempuri.org/ISectionMaster/ImportResponse")]
        Rac.VOne.Web.Models.ImportResultSection Import(string SessionKey, Rac.VOne.Web.Models.Section[] InsertList, Rac.VOne.Web.Models.Section[] UpdateList, Rac.VOne.Web.Models.Section[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/Import", ReplyAction="http://tempuri.org/ISectionMaster/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResultSection> ImportAsync(string SessionKey, Rac.VOne.Web.Models.Section[] InsertList, Rac.VOne.Web.Models.Section[] UpdateList, Rac.VOne.Web.Models.Section[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForBankAccount", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForBankAccountResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForBankAccount(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForBankAccount", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForBankAccountResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForBankAccountAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForSectionWithDepartment", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForSectionWithDepartmentResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForSectionWithDepartment(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForSectionWithDepartment", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForSectionWithDepartmentResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForSectionWithDepartmentAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForSectionWithLoginUser", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForSectionWithLoginUserResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForSectionWithLoginUser(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForSectionWithLoginUser", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForSectionWithLoginUserResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForSectionWithLoginUserAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForReceipt", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForReceiptResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForReceipt(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForReceipt", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForReceiptResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForReceiptAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForNetting", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForNettingResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForNetting(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForNetting", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForNettingResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForNettingAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForSection", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForSectionResponse")]
        Rac.VOne.Web.Models.SectionsResult GetImportItemsForSection(string SessionKey, int CompanyId, string[] PayerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/GetImportItemsForSection", ReplyAction="http://tempuri.org/ISectionMaster/GetImportItemsForSectionResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionsResult> GetImportItemsForSectionAsync(string SessionKey, int CompanyId, string[] PayerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/Get", ReplyAction="http://tempuri.org/ISectionMaster/GetResponse")]
        Rac.VOne.Web.Models.SectionsResult Get(string SessionKey, int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectionMaster/Get", ReplyAction="http://tempuri.org/ISectionMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionsResult> GetAsync(string SessionKey, int[] ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISectionMasterChannel : Rac.VOne.Client.Screen.SectionMasterService.ISectionMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SectionMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.SectionMasterService.ISectionMaster>, Rac.VOne.Client.Screen.SectionMasterService.ISectionMaster {
        
        public SectionMasterClient() {
        }
        
        public SectionMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SectionMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SectionMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SectionMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.SectionsResult GetByLoginUserId(string SessionKey, int LoginUserId) {
            return base.Channel.GetByLoginUserId(SessionKey, LoginUserId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionsResult> GetByLoginUserIdAsync(string SessionKey, int LoginUserId) {
            return base.Channel.GetByLoginUserIdAsync(SessionKey, LoginUserId);
        }
        
        public Rac.VOne.Web.Models.SectionsResult GetByCode(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetByCode(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionsResult> GetByCodeAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetByCodeAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.SectionResults Save(string SessionKey, Rac.VOne.Web.Models.Section Section) {
            return base.Channel.Save(SessionKey, Section);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionResults> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Section Section) {
            return base.Channel.SaveAsync(SessionKey, Section);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int Id) {
            return base.Channel.Delete(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int Id) {
            return base.Channel.DeleteAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.SectionsResult GetItems(string SessionKey, int CompanyId, Rac.VOne.Web.Models.SectionSearch SectionSearch) {
            return base.Channel.GetItems(SessionKey, CompanyId, SectionSearch);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionsResult> GetItemsAsync(string SessionKey, int CompanyId, Rac.VOne.Web.Models.SectionSearch SectionSearch) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId, SectionSearch);
        }
        
        public Rac.VOne.Web.Models.SectionResult GetByCustomerId(string SessionKey, int CustomerId) {
            return base.Channel.GetByCustomerId(SessionKey, CustomerId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionResult> GetByCustomerIdAsync(string SessionKey, int CustomerId) {
            return base.Channel.GetByCustomerIdAsync(SessionKey, CustomerId);
        }
        
        public Rac.VOne.Web.Models.ImportResultSection Import(string SessionKey, Rac.VOne.Web.Models.Section[] InsertList, Rac.VOne.Web.Models.Section[] UpdateList, Rac.VOne.Web.Models.Section[] DeleteList) {
            return base.Channel.Import(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResultSection> ImportAsync(string SessionKey, Rac.VOne.Web.Models.Section[] InsertList, Rac.VOne.Web.Models.Section[] UpdateList, Rac.VOne.Web.Models.Section[] DeleteList) {
            return base.Channel.ImportAsync(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForBankAccount(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForBankAccount(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForBankAccountAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForBankAccountAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForSectionWithDepartment(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForSectionWithDepartment(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForSectionWithDepartmentAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForSectionWithDepartmentAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForSectionWithLoginUser(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForSectionWithLoginUser(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForSectionWithLoginUserAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForSectionWithLoginUserAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForReceipt(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForReceipt(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForReceiptAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForReceiptAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForNetting(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForNetting(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForNettingAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForNettingAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.SectionsResult GetImportItemsForSection(string SessionKey, int CompanyId, string[] PayerCode) {
            return base.Channel.GetImportItemsForSection(SessionKey, CompanyId, PayerCode);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionsResult> GetImportItemsForSectionAsync(string SessionKey, int CompanyId, string[] PayerCode) {
            return base.Channel.GetImportItemsForSectionAsync(SessionKey, CompanyId, PayerCode);
        }
        
        public Rac.VOne.Web.Models.SectionsResult Get(string SessionKey, int[] ids) {
            return base.Channel.Get(SessionKey, ids);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.SectionsResult> GetAsync(string SessionKey, int[] ids) {
            return base.Channel.GetAsync(SessionKey, ids);
        }
    }
}
