//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.EbData.CurrencyMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyMasterService.ICurrencyMaster")]
    public interface ICurrencyMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/Get", ReplyAction="http://tempuri.org/ICurrencyMaster/GetResponse")]
        Rac.VOne.Web.Models.CurrenciesResult Get(string SessionKey, int[] CurrencyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/Get", ReplyAction="http://tempuri.org/ICurrencyMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CurrenciesResult> GetAsync(string SessionKey, int[] CurrencyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/GetItems", ReplyAction="http://tempuri.org/ICurrencyMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.CurrenciesResult GetItems(string SessionKey, int CompanyId, Rac.VOne.Web.Models.CurrencySearch CurrencySearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/GetItems", ReplyAction="http://tempuri.org/ICurrencyMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CurrenciesResult> GetItemsAsync(string SessionKey, int CompanyId, Rac.VOne.Web.Models.CurrencySearch CurrencySearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/GetByCode", ReplyAction="http://tempuri.org/ICurrencyMaster/GetByCodeResponse")]
        Rac.VOne.Web.Models.CurrenciesResult GetByCode(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/GetByCode", ReplyAction="http://tempuri.org/ICurrencyMaster/GetByCodeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CurrenciesResult> GetByCodeAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/Save", ReplyAction="http://tempuri.org/ICurrencyMaster/SaveResponse")]
        Rac.VOne.Web.Models.CurrencyResult Save(string SessionKey, Rac.VOne.Web.Models.Currency Currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/Save", ReplyAction="http://tempuri.org/ICurrencyMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CurrencyResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Currency Currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/Delete", ReplyAction="http://tempuri.org/ICurrencyMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/Delete", ReplyAction="http://tempuri.org/ICurrencyMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/Import", ReplyAction="http://tempuri.org/ICurrencyMaster/ImportResponse")]
        Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.Currency[] InsertList, Rac.VOne.Web.Models.Currency[] UpdateList, Rac.VOne.Web.Models.Currency[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/Import", ReplyAction="http://tempuri.org/ICurrencyMaster/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.Currency[] InsertList, Rac.VOne.Web.Models.Currency[] UpdateList, Rac.VOne.Web.Models.Currency[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/GetImportItemsBilling", ReplyAction="http://tempuri.org/ICurrencyMaster/GetImportItemsBillingResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsBilling(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/GetImportItemsBilling", ReplyAction="http://tempuri.org/ICurrencyMaster/GetImportItemsBillingResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsBillingAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/GetImportItemsReceipt", ReplyAction="http://tempuri.org/ICurrencyMaster/GetImportItemsReceiptResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsReceipt(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/GetImportItemsReceipt", ReplyAction="http://tempuri.org/ICurrencyMaster/GetImportItemsReceiptResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsReceiptAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/GetImportItemsNetting", ReplyAction="http://tempuri.org/ICurrencyMaster/GetImportItemsNettingResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsNetting(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyMaster/GetImportItemsNetting", ReplyAction="http://tempuri.org/ICurrencyMaster/GetImportItemsNettingResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsNettingAsync(string SessionKey, int CompanyId, string[] Code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyMasterChannel : Rac.VOne.EbData.CurrencyMasterService.ICurrencyMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyMasterClient : System.ServiceModel.ClientBase<Rac.VOne.EbData.CurrencyMasterService.ICurrencyMaster>, Rac.VOne.EbData.CurrencyMasterService.ICurrencyMaster {
        
        public CurrencyMasterClient() {
        }
        
        public CurrencyMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.CurrenciesResult Get(string SessionKey, int[] CurrencyId) {
            return base.Channel.Get(SessionKey, CurrencyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CurrenciesResult> GetAsync(string SessionKey, int[] CurrencyId) {
            return base.Channel.GetAsync(SessionKey, CurrencyId);
        }
        
        public Rac.VOne.Web.Models.CurrenciesResult GetItems(string SessionKey, int CompanyId, Rac.VOne.Web.Models.CurrencySearch CurrencySearch) {
            return base.Channel.GetItems(SessionKey, CompanyId, CurrencySearch);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CurrenciesResult> GetItemsAsync(string SessionKey, int CompanyId, Rac.VOne.Web.Models.CurrencySearch CurrencySearch) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId, CurrencySearch);
        }
        
        public Rac.VOne.Web.Models.CurrenciesResult GetByCode(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetByCode(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CurrenciesResult> GetByCodeAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetByCodeAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.CurrencyResult Save(string SessionKey, Rac.VOne.Web.Models.Currency Currency) {
            return base.Channel.Save(SessionKey, Currency);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CurrencyResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Currency Currency) {
            return base.Channel.SaveAsync(SessionKey, Currency);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int Id) {
            return base.Channel.Delete(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int Id) {
            return base.Channel.DeleteAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.Currency[] InsertList, Rac.VOne.Web.Models.Currency[] UpdateList, Rac.VOne.Web.Models.Currency[] DeleteList) {
            return base.Channel.Import(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.Currency[] InsertList, Rac.VOne.Web.Models.Currency[] UpdateList, Rac.VOne.Web.Models.Currency[] DeleteList) {
            return base.Channel.ImportAsync(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsBilling(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsBilling(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsBillingAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsBillingAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsReceipt(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsReceipt(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsReceiptAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsReceiptAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsNetting(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsNetting(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsNettingAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsNettingAsync(SessionKey, CompanyId, Code);
        }
    }
}
