export class BillingSearch {
    public companyId: number;
    public bsBilledAtFrom: string | null;
    public bsBilledAtTo: string | null;
    public bsSalesAtFrom: string | null;
    public bsSalesAtTo: string | null;
    public bsDueAtFrom: string | null;
    public bsDueAtTo: string | null;
    public bsScheduledPaymentKey: string | null;
    public bsInvoiceCode: string | null;
    public bsInvoiceCodeFrom: string | null;
    public bsInvoiceCodeTo: string | null;
    public bsCustomerCode: string | null;
    public bsCustomerName: string | null;
    public bsCurrencyCode: string | null;
    public bsClosingAtFrom: string | null;
    public bsClosingAtTo: string | null;
    public bsDepartmentCodeFrom: string | null;
    public bsDepartmentCodeTo: string | null;
    public bsStaffCodeFrom: string | null;
    public bsStaffCodeTo: string | null;
    public bsCustomerCodeFrom: string | null;
    public bsCustomerCodeTo: string | null;
    public bsCustomerNameKana: string | null;
    public bsPayerName: string | null;
    public bsRemaingAmountFrom: number | null;
    public bsRemaingAmountTo: number | null;
    public bsBillingAmountFrom: number | null;
    public bsBillingAmountTo: number | null;
    public bsInputType: number;
    public bsMemo: string | null;
    public bsBillingCategoryId: number;
    public bsUpdateAtFrom: string | null;
    public bsUpdateAtTo: string | null;
    public bsUpdateBy: number | null;
    public bsNote1: string | null;
    public bsNote2: string | null;
    public bsNote3: string | null;
    public bsNote4: string | null;
    public bsNote5: string | null;
    public bsNote6: string | null;
    public bsNote7: string | null;
    public bsNote8: string | null;
    public parentCustomerId: number;
    public assignmentFlg: number;
    public useSectionMaster: Boolean;
    public loginUserId: number;
    public loginUserCode: string | null;
    public userId: number;
    public existsMemo: Boolean;
    public collectCategoryId: number;
    public requestDate: number;
    public currencyId: number;
    public isParentFlg: number;
    public customerId: number;
    public clientKey: string | null;
    public useDepartmentWork: Boolean;
    public isDeleted: Boolean;
    public bsDeleteAtFrom: string | null;
    public bsDeleteAtTo: string | null;
    public kobetsuType: string | null;
    public requireRecordedAt: Boolean;
    public customerCode: string | null;
    public billedAt: string | null;
    public billingAmount: number;
    public taxAmount: number;
    public invoiceCode: string | null;
    public note1: string | null;
    public price: number;
    public taxClassId: number | null;
    public note2: string | null;
    public note3: string | null;
    public note4: string | null;
    public note5: string | null;
    public note6: string | null;
    public note7: string | null;
    public note8: string | null;
    public currencyCode: string | null;
    public billingId: number | null;
    public billingInputId: number | null;
}

