export class Category {
    public id: number;
    public companyId: number;
    public categoryType: number;
    public code: string | null;
    public name: string | null;
    public accountTitleId: number | null;
    public subCode: string | null;
    public note: string | null;
    public taxClassId: number | null;
    public useLimitDate: number;
    public useLongTermAdvanceReceived: number;
    public useCashOnDueDates: number;
    public useAccountTransfer: number;
    public paymentAgencyId: number | null;
    public useDiscount: number;
    public useAdvanceReceived: number;
    public forceMatchingIndividually: number;
    public useInput: number;
    public matchingOrder: number;
    public stringValue1: string | null;
    public stringValue2: string | null;
    public stringValue3: string | null;
    public stringValue4: string | null;
    public stringValue5: string | null;
    public intValue1: number;
    public intValue2: number;
    public intValue3: number;
    public intValue4: number;
    public intValue5: number;
    public numericValue1: number;
    public numericValue2: number;
    public numericValue3: number;
    public numericValue4: number;
    public numericValue5: number;
    public updateBy: number;
    public updateAt: string;
    public externalCode: string | null;
    public categoryCompanyId: number;
    public createBy: number;
    public createAt: string;
    public excludeInvoicePublish: number;
    public accountTitleCode: string | null;
    public accountTitleName: string | null;
    public taxClassName: string | null;
    public paymentAgencyCode: string | null;
    public paymentAgencyName: string | null;
}

