export class Customer {
    public id: number;
    public companyId: number;
    public code: string | null;
    public name: string | null;
    public kana: string | null;
    public postalCode: string | null;
    public address1: string | null;
    public address2: string | null;
    public tel: string | null;
    public fax: string | null;
    public customerStaffName: string | null;
    public exclusiveBankCode: string | null;
    public exclusiveBankName: string | null;
    public exclusiveBranchCode: string | null;
    public exclusiveBranchName: string | null;
    public exclusiveAccountNumber: string | null;
    public exclusiveAccountTypeId: number | null;
    public shareTransferFee: number;
    public creditLimit: number;
    public closingDay: number;
    public collectCategoryId: number;
    public staffId: number;
    public isParent: number;
    public note: string | null;
    public sightOfBill: number | null;
    public densaiCode: string | null;
    public creditCode: string | null;
    public creditRank: string | null;
    public transferBankCode: string | null;
    public transferBankName: string | null;
    public transferBranchCode: string | null;
    public transferBranchName: string | null;
    public transferAccountNumber: string | null;
    public transferAccountTypeId: number | null;
    public receiveAccountId1: number;
    public receiveAccountId2: number;
    public receiveAccountId3: number;
    public useFeeLearning: number;
    public useKanaLearning: number;
    public holidayFlag: number;
    public useFeeTolerance: number;
    public stringValue1: string | null;
    public stringValue2: string | null;
    public stringValue3: string | null;
    public stringValue4: string | null;
    public stringValue5: string | null;
    public intValue1: number | null;
    public intValue2: number | null;
    public intValue3: number | null;
    public intValue4: number | null;
    public intValue5: number | null;
    public numericValue1: number | null;
    public numericValue2: number | null;
    public numericValue3: number | null;
    public numericValue4: number | null;
    public numericValue5: number | null;
    public createBy: number;
    public createAt: string;
    public updateBy: number;
    public updateAt: string;
    public transferCustomerCode: string | null;
    public transferNewCode: string | null;
    public transferAccountName: string | null;
    public collectOffsetMonth: number;
    public collectOffsetDay: number;
    public parentCustomerId: number;
    public prioritizeMatchingIndividually: number;
    public collationKey: string | null;
    public excludeInvoicePublish: number;
    public excludeReminderPublish: number;
    public destinationDepartmentName: string | null;
    public honorific: string | null;
    public staffName: string | null;
    public staffCode: string | null;
    public thresholdValue: number;
    public collectCategoryName: string | null;
    public lessThanCollectCategoryCode: string | null;
    public lessThanCollectCategoryId: number;
    public greaterThanCollectCategoryId1: number;
    public greaterThanCollectCategoryCode1: string | null;
    public greaterThanCollectCategoryId2: number | null;
    public greaterThanCollectCategoryCode2: string | null;
    public greaterThanCollectCategoryId3: number | null;
    public greaterThanCollectCategoryCode3: string | null;
    public greaterThanRate1: number | null;
    public greaterThanRate2: number | null;
    public greaterThanRate3: number | null;
    public greaterThanRoundingMode1: number | null;
    public greaterThanRoundingMode2: number | null;
    public greaterThanRoundingMode3: number | null;
    public greaterThanSightOfBill1: number | null;
    public greaterThanSightOfBill2: number | null;
    public greaterThanSightOfBill3: number | null;
    public parentCode: string | null;
    public parentName: string | null;
    public collectCategoryCode: string | null;
    public lessThanCollectCategoryName: string | null;
    public greaterThanCollectCategoryName1: string | null;
    public greaterThanCollectCategoryName2: string | null;
    public greaterThanCollectCategoryName3: string | null;
    public companyBankInfo1: string | null;
    public companyBankInfo2: string | null;
    public companyBankInfo3: string | null;
    public lastUpdateUser: string | null;
}

