export class ExportMatchingIndividual {
    public id: number;
    public companyId: number;
    public currencyId: number;
    public customerId: number;
    public departmentId: number;
    public staffId: number;
    public billingCategoryId: number;
    public inputType: number;
    public billingInputTypeId: number;
    public billedAt: string | null;
    public closingAt: string;
    public salesAt: string | null;
    public dueAt: string | null;
    public billingAmount: number | null;
    public taxAmount: number;
    public assignmentAmount: number;
    public remainAmount: number | null;
    public targetAmount: number | null;
    public offsetAmount: number;
    public assignmentFlag: number;
    public approved: number;
    public collectCategoryId: number;
    public originalCollectCategoryId: number | null;
    public debitAccountTitleId: number | null;
    public creditAccountTitleId: number | null;
    public originalDueAt: string | null;
    public outputAt: string | null;
    public publishAt: string | null;
    public invoiceCode: string | null;
    public taxClassId: number;
    public note1: string | null;
    public note2: string | null;
    public note3: string | null;
    public note4: string | null;
    public note5: string | null;
    public note6: string | null;
    public note7: string | null;
    public note8: string | null;
    public deleteAt: string | null;
    public requestDate: string | null;
    public resultCode: number | null;
    public transferOriginalDueAt: string | null;
    public scheduledPaymentKey: string | null;
    public quantity: number | null;
    public unitPrice: number | null;
    public unitSymbol: string | null;
    public price: number | null;
    public createBy: number;
    public createAt: string;
    public updateBy: number;
    public updateAt: string;
    public billingInputId: number | null;
    public currencyCode: string | null;
    public customerCode: string | null;
    public customerName: string | null;
    public customerKana: string | null;
    public departmentCode: string | null;
    public departmentName: string | null;
    public staffName: string | null;
    public staffCode: string | null;
    public memo: string | null;
    public billingCategoryCode: string | null;
    public billingCategoryName: string | null;
    public collectCategoryCode: string | null;
    public collectCategoryName: string | null;
    public loginUserCode: string | null;
    public loginUserName: string | null;
    public contractNumber: string | null;
    public confirm: number;
    public discountAmount: number | null;
    public discountAmount1: number;
    public discountAmount2: number;
    public discountAmount3: number;
    public discountAmount4: number;
    public discountAmount5: number;
    public billingId: number;
    public parentCustomerCode: string | null;
    public companyCode: string | null;
    public accountTitleCode: string | null;
    public code: string | null;
    public name: string | null;
    public paymentAmount: number;
    public categoryCodeAndName: string | null;
    public orgCategoryCodeAndName: string | null;
    public billingCategoryCodeAndName: string | null;
    public collectCategoryCodeAndName: string | null;
    public inputTypeName: string | null;
    public assignmentFlagName: string | null;
    public inputTypeNameAndIndex: string | null;
    public billCheck: string | null;
    public amount: number;
    public receiptId: number;
    public receiptCompanyId: number;
    public receiptCurrencyId: number;
    public privateBankCode: string | null;
    public receiptHeaderId: number | null;
    public receiptCategoryId: number;
    public receiptCustomerId: number | null;
    public sectionId: number | null;
    public receiptInputType: number;
    public apportioned: number;
    public receiptApproved: number;
    public workday: string;
    public recordedAt: string | null;
    public originalRecordedAt: string | null;
    public receiptAmount: number | null;
    public receiptAssignmentAmount: number;
    public receiptRemainAmount: number | null;
    public receiptAssignmentFlag: number;
    public payerCode: string | null;
    public payerName: string | null;
    public payerNameRaw: string | null;
    public sourceBankName: string | null;
    public sourceBranchName: string | null;
    public receiptOutputAt: string | null;
    public receiptDueAt: string | null;
    public mailedAt: string | null;
    public originalReceiptId: number | null;
    public excludeFlag: number;
    public excludeCategoryId: number | null;
    public excludeAmount: number;
    public referenceNumber: string | null;
    public recordNumber: string | null;
    public densaiRegisterAt: string | null;
    public receiptNote1: string | null;
    public receiptNote2: string | null;
    public receiptNote3: string | null;
    public receiptNote4: string | null;
    public billNumber: string | null;
    public billBankCode: string | null;
    public billBranchCode: string | null;
    public billDrawAt: string | null;
    public billDrawer: string | null;
    public receiptDeleteAt: string | null;
    public receiptCreateBy: number;
    public receiptCreateAt: string;
    public receiptUpdateBy: number;
    public receiptUpdateAt: string;
    public categoryName: string | null;
    public receiptCustomerCode: string | null;
    public receiptCustomerName: string | null;
    public excludeCategoryName: string | null;
    public receiptCurrencyCode: string | null;
    public sectionCode: string | null;
    public sectionName: string | null;
    public bankCode: string | null;
    public bankName: string | null;
    public branchCode: string | null;
    public branchName: string | null;
    public payerCodePrefix: string | null;
    public payerCodeSuffix: string | null;
    public useAdvanceReceived: number;
    public useForeignCurrency: number;
    public accountNumber: string | null;
    public receiptMemo: string | null;
    public sourceBank: string | null;
    public useFeeTolerance: number;
    public customerFee: number;
    public generalFee: number;
    public originalUpdateAt: string;
    public bankTransferFee: number;
    public nettingId: number | null;
    public recExcOutputAt: number;
    public useCashOnDueDates: number;
    public nettingState: string | null;
    public accountTypeName: string | null;
    public receiptAssignmentFlagName: string | null;
    public recCheck: string | null;
    public receiptCategroyCodeAndName: string | null;
}

