export class MatchingHistory {
    public createAt: string;
    public sectionCode: string | null;
    public sectionName: string | null;
    public departmentCode: string | null;
    public departmentName: string | null;
    public customerCode: string | null;
    public customerName: string | null;
    public billedAt: string | null;
    public salesAt: string | null;
    public invoiceCode: string | null;
    public billingCategoryCode: string | null;
    public billingCategoryName: string | null;
    public billingAmount: number | null;
    public billingAmountExcludingTax: number | null;
    public taxAmount: number | null;
    public matchingAmount: number | null;
    public billingRemain: number | null;
    public billingNote1: string | null;
    public billingNote2: string | null;
    public billingNote3: string | null;
    public billingNote4: string | null;
    public recordedAt: string | null;
    public receiptId: number | null;
    public receiptCategoryCode: string | null;
    public receiptCategoryName: string | null;
    public receiptAmount: number | null;
    public advanceReceivedOccured: Boolean;
    public receiptRemain: number | null;
    public payerName: string | null;
    public bankCode: string | null;
    public bankName: string | null;
    public branchCode: string | null;
    public branchName: string | null;
    public accountNumber: string | null;
    public receiptNote1: string | null;
    public receiptNote2: string | null;
    public receiptNote3: string | null;
    public receiptNote4: string | null;
    public payerCode: string | null;
    public loginUserCode: string | null;
    public loginUserName: string | null;
    public matchingProcessType: string | null;
    public matchingMemo: string | null;
    public matchingId: number;
    public taxDifference: number | null;
    public bankTransferFee: number | null;
    public matchingHeaderId: number;
    public billingId: number;
    public collectCategoryCode: string | null;
    public collectCategoryName: string | null;
}

