export class ReceiptSearch {
    public useForeignCurrencyFlg: number;
    public companyId: number;
    public loginUserId: number;
    public excludeFlag: number;
    public assignmentFlag: number;
    public payerName: string | null;
    public receiptAmountFrom: number | null;
    public receiptAmountTo: number | null;
    public remainAmountFrom: number | null;
    public remainAmountTo: number | null;
    public inputType: number | null;
    public note1: string | null;
    public note2: string | null;
    public note3: string | null;
    public note4: string | null;
    public updateAtFrom: string | null;
    public updateAtTo: string | null;
    public currencyId: number;
    public privateBankCode: string | null;
    public payerCodePrefix: string | null;
    public payerCodeSuffix: string | null;
    public billNumber: string | null;
    public billBankCode: string | null;
    public billBranchCode: string | null;
    public billDrawAtFrom: string | null;
    public billDrawAtTo: string | null;
    public billDrawer: string | null;
    public recordedAtFrom: string | null;
    public recordedAtTo: string | null;
    public sourceBankName: string | null;
    public sourceBranchName: string | null;
    public receiptCategoryId: number;
    public customerCodeFrom: string | null;
    public customerCodeTo: string | null;
    public sectionCodeFrom: string | null;
    public sectionCodeTo: string | null;
    public currencyCode: string | null;
    public receiptCategoryCode: string | null;
    public receiptCategoryCodeFrom: string | null;
    public receiptCategoryCodeTo: string | null;
    public excludeCategoryId: number | null;
    public sectionCode: string | null;
    public bankCode: string | null;
    public branchCode: string | null;
    public accountNumber: string | null;
    public accountTypeId: number;
    public existsMemo: number;
    public receiptMemo: string | null;
    public updateBy: number | null;
    public useSectionMaster: Boolean;
    public pageCount: number;
    public deleteFlg: number | null;
    public deleteAtFrom: string | null;
    public deleteAtTo: string | null;
    public advanceReceivedFlg: number | null;
    public kobetsuType: string | null;
    public useSectionWork: Boolean;
    public clientKey: string | null;
    public isEditable: Boolean;
}

