export class Receipt {
    public amount: number;
    public id: number;
    public companyId: number;
    public currencyId: number;
    public privateBankCode: string | null;
    public receiptHeaderId: number | null;
    public receiptCategoryId: number;
    public customerId: number | null;
    public sectionId: number | null;
    public inputType: number;
    public apportioned: number;
    public approved: number;
    public workday: string;
    public recordedAt: string;
    public originalRecordedAt: string | null;
    public receiptAmount: number;
    public assignmentAmount: number;
    public remainAmount: number;
    public assignmentFlag: number;
    public payerCode: string | null;
    public payerName: string | null;
    public payerNameRaw: string | null;
    public sourceBankName: string | null;
    public sourceBranchName: string | null;
    public outputAt: string | null;
    public dueAt: string | null;
    public mailedAt: string | null;
    public originalReceiptId: number | null;
    public excludeFlag: number;
    public excludeCategoryId: number | null;
    public excludeAmount: number;
    public referenceNumber: string | null;
    public recordNumber: string | null;
    public densaiRegisterAt: string | null;
    public note1: string | null;
    public note2: string | null;
    public note3: string | null;
    public note4: string | null;
    public billNumber: string | null;
    public billBankCode: string | null;
    public billBranchCode: string | null;
    public billDrawAt: string | null;
    public billDrawer: string | null;
    public deleteAt: string | null;
    public createBy: number;
    public createAt: string;
    public updateBy: number;
    public updateAt: string;
    public processingAt: string | null;
    public staffId: number | null;
    public collationKey: string | null;
    public bankCode: string | null;
    public bankName: string | null;
    public branchCode: string | null;
    public branchName: string | null;
    public accountTypeId: number | null;
    public accountNumber: string | null;
    public accountName: string | null;
    public categoryCode: string | null;
    public categoryName: string | null;
    public customerCode: string | null;
    public customerName: string | null;
    public excludeCategoryCode: string | null;
    public excludeCategoryName: string | null;
    public excludeCategoryCodeName: string | null;
    public currencyCode: string | null;
    public sectionCode: string | null;
    public sectionName: string | null;
    public useAdvanceReceived: number;
    public useForeignCurrency: number;
    public receiptMemo: string | null;
    public transferMemo: string | null;
    public useFeeTolerance: number;
    public customerFee: number;
    public generalFee: number;
    public originalUpdateAt: string;
    public bankTransferFee: number;
    public nettingId: number | null;
    public recExcOutputAt: number;
    public useCashOnDueDates: number;
    public accountTypeName: string | null;
    public cancelFlag: Boolean;
    public receiptStatusFlag: number;
    public remainAmountFlag: number;
    public excludeFlagBuffer: number;
    public excludeCategoryIdBuffer: number | null;
    public customerCodeBuffer: string | null;
}

