//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.ImportFileLogService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImportFileLogService.IImportFileLogService")]
    public interface IImportFileLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportFileLogService/GetHistory", ReplyAction="http://tempuri.org/IImportFileLogService/GetHistoryResponse")]
        Rac.VOne.Web.Models.ImportFileLogsResult GetHistory(string Sessionkey, int ComapnyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportFileLogService/GetHistory", ReplyAction="http://tempuri.org/IImportFileLogService/GetHistoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportFileLogsResult> GetHistoryAsync(string Sessionkey, int ComapnyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportFileLogService/DeleteItems", ReplyAction="http://tempuri.org/IImportFileLogService/DeleteItemsResponse")]
        Rac.VOne.Web.Models.ImportFileLogsResult DeleteItems(string SessionKey, int[] Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportFileLogService/DeleteItems", ReplyAction="http://tempuri.org/IImportFileLogService/DeleteItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportFileLogsResult> DeleteItemsAsync(string SessionKey, int[] Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportFileLogService/SaveImportFileLog", ReplyAction="http://tempuri.org/IImportFileLogService/SaveImportFileLogResponse")]
        Rac.VOne.Web.Models.ImportFileLogsResult SaveImportFileLog(string Sessionkey, Rac.VOne.Web.Models.ImportFileLog[] ImportFileLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportFileLogService/SaveImportFileLog", ReplyAction="http://tempuri.org/IImportFileLogService/SaveImportFileLogResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportFileLogsResult> SaveImportFileLogAsync(string Sessionkey, Rac.VOne.Web.Models.ImportFileLog[] ImportFileLog);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImportFileLogServiceChannel : Rac.VOne.Client.Screen.ImportFileLogService.IImportFileLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportFileLogServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.ImportFileLogService.IImportFileLogService>, Rac.VOne.Client.Screen.ImportFileLogService.IImportFileLogService {
        
        public ImportFileLogServiceClient() {
        }
        
        public ImportFileLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportFileLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportFileLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportFileLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.ImportFileLogsResult GetHistory(string Sessionkey, int ComapnyId) {
            return base.Channel.GetHistory(Sessionkey, ComapnyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportFileLogsResult> GetHistoryAsync(string Sessionkey, int ComapnyId) {
            return base.Channel.GetHistoryAsync(Sessionkey, ComapnyId);
        }
        
        public Rac.VOne.Web.Models.ImportFileLogsResult DeleteItems(string SessionKey, int[] Ids) {
            return base.Channel.DeleteItems(SessionKey, Ids);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportFileLogsResult> DeleteItemsAsync(string SessionKey, int[] Ids) {
            return base.Channel.DeleteItemsAsync(SessionKey, Ids);
        }
        
        public Rac.VOne.Web.Models.ImportFileLogsResult SaveImportFileLog(string Sessionkey, Rac.VOne.Web.Models.ImportFileLog[] ImportFileLog) {
            return base.Channel.SaveImportFileLog(Sessionkey, ImportFileLog);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportFileLogsResult> SaveImportFileLogAsync(string Sessionkey, Rac.VOne.Web.Models.ImportFileLog[] ImportFileLog) {
            return base.Channel.SaveImportFileLogAsync(Sessionkey, ImportFileLog);
        }
    }
}
