//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.AuthenticationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationService.IAuthentication")]
    public interface IAuthentication {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Authenticate", ReplyAction="http://tempuri.org/IAuthentication/AuthenticateResponse")]
        System.Data.DataSet Authenticate(System.Data.DataSet arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Authenticate", ReplyAction="http://tempuri.org/IAuthentication/AuthenticateResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> AuthenticateAsync(System.Data.DataSet arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Authorize", ReplyAction="http://tempuri.org/IAuthentication/AuthorizeResponse")]
        System.Data.DataSet Authorize(System.Data.DataSet arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Authorize", ReplyAction="http://tempuri.org/IAuthentication/AuthorizeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> AuthorizeAsync(System.Data.DataSet arg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationChannel : Rac.VOne.Client.Screen.AuthenticationService.IAuthentication, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.AuthenticationService.IAuthentication>, Rac.VOne.Client.Screen.AuthenticationService.IAuthentication {
        
        public AuthenticationClient() {
        }
        
        public AuthenticationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Authenticate(System.Data.DataSet arg) {
            return base.Channel.Authenticate(arg);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AuthenticateAsync(System.Data.DataSet arg) {
            return base.Channel.AuthenticateAsync(arg);
        }
        
        public System.Data.DataSet Authorize(System.Data.DataSet arg) {
            return base.Channel.Authorize(arg);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AuthorizeAsync(System.Data.DataSet arg) {
            return base.Channel.AuthorizeAsync(arg);
        }
    }
}
