//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.AdvanceReceivedBackupService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdvanceReceivedBackupService.IAdvanceReceivedBackupService")]
    public interface IAdvanceReceivedBackupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvanceReceivedBackupService/GetByOriginalReceiptId", ReplyAction="http://tempuri.org/IAdvanceReceivedBackupService/GetByOriginalReceiptIdResponse")]
        Rac.VOne.Web.Models.AdvanceReceivedBackupResult GetByOriginalReceiptId(string SessionKey, long OriginalReceiptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvanceReceivedBackupService/GetByOriginalReceiptId", ReplyAction="http://tempuri.org/IAdvanceReceivedBackupService/GetByOriginalReceiptIdResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.AdvanceReceivedBackupResult> GetByOriginalReceiptIdAsync(string SessionKey, long OriginalReceiptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvanceReceivedBackupService/GetByIds", ReplyAction="http://tempuri.org/IAdvanceReceivedBackupService/GetByIdsResponse")]
        Rac.VOne.Web.Models.AdvanceReceivedBackupsResult GetByIds(string SessionKey, long[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvanceReceivedBackupService/GetByIds", ReplyAction="http://tempuri.org/IAdvanceReceivedBackupService/GetByIdsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.AdvanceReceivedBackupsResult> GetByIdsAsync(string SessionKey, long[] ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdvanceReceivedBackupServiceChannel : Rac.VOne.Client.Screen.AdvanceReceivedBackupService.IAdvanceReceivedBackupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdvanceReceivedBackupServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.AdvanceReceivedBackupService.IAdvanceReceivedBackupService>, Rac.VOne.Client.Screen.AdvanceReceivedBackupService.IAdvanceReceivedBackupService {
        
        public AdvanceReceivedBackupServiceClient() {
        }
        
        public AdvanceReceivedBackupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdvanceReceivedBackupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvanceReceivedBackupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvanceReceivedBackupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.AdvanceReceivedBackupResult GetByOriginalReceiptId(string SessionKey, long OriginalReceiptId) {
            return base.Channel.GetByOriginalReceiptId(SessionKey, OriginalReceiptId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.AdvanceReceivedBackupResult> GetByOriginalReceiptIdAsync(string SessionKey, long OriginalReceiptId) {
            return base.Channel.GetByOriginalReceiptIdAsync(SessionKey, OriginalReceiptId);
        }
        
        public Rac.VOne.Web.Models.AdvanceReceivedBackupsResult GetByIds(string SessionKey, long[] ids) {
            return base.Channel.GetByIds(SessionKey, ids);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.AdvanceReceivedBackupsResult> GetByIdsAsync(string SessionKey, long[] ids) {
            return base.Channel.GetByIdsAsync(SessionKey, ids);
        }
    }
}
