//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.LoginUserLicenseMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginUserLicenseMasterService.ILoginUserLicenseMaster")]
    public interface ILoginUserLicenseMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserLicenseMaster/GetItems", ReplyAction="http://tempuri.org/ILoginUserLicenseMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.LoginUserLicensesResult GetItems(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserLicenseMaster/GetItems", ReplyAction="http://tempuri.org/ILoginUserLicenseMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.LoginUserLicensesResult> GetItemsAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserLicenseMaster/Save", ReplyAction="http://tempuri.org/ILoginUserLicenseMaster/SaveResponse")]
        Rac.VOne.Web.Models.LoginUserLicensesResult Save(string SessionKey, int CompanyId, string[] LicenseKeys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginUserLicenseMaster/Save", ReplyAction="http://tempuri.org/ILoginUserLicenseMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.LoginUserLicensesResult> SaveAsync(string SessionKey, int CompanyId, string[] LicenseKeys);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginUserLicenseMasterChannel : Rac.VOne.Client.Screen.LoginUserLicenseMasterService.ILoginUserLicenseMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginUserLicenseMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.LoginUserLicenseMasterService.ILoginUserLicenseMaster>, Rac.VOne.Client.Screen.LoginUserLicenseMasterService.ILoginUserLicenseMaster {
        
        public LoginUserLicenseMasterClient() {
        }
        
        public LoginUserLicenseMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginUserLicenseMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginUserLicenseMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginUserLicenseMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.LoginUserLicensesResult GetItems(string SessionKey, int CompanyId) {
            return base.Channel.GetItems(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.LoginUserLicensesResult> GetItemsAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.LoginUserLicensesResult Save(string SessionKey, int CompanyId, string[] LicenseKeys) {
            return base.Channel.Save(SessionKey, CompanyId, LicenseKeys);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.LoginUserLicensesResult> SaveAsync(string SessionKey, int CompanyId, string[] LicenseKeys) {
            return base.Channel.SaveAsync(SessionKey, CompanyId, LicenseKeys);
        }
    }
}
