//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.CustomerMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerMasterService.ICustomerMaster")]
    public interface ICustomerMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/Save", ReplyAction="http://tempuri.org/ICustomerMaster/SaveResponse")]
        Rac.VOne.Web.Models.CustomerResult Save(string SessionKey, Rac.VOne.Web.Models.Customer Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/Save", ReplyAction="http://tempuri.org/ICustomerMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Customer Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/SaveItems", ReplyAction="http://tempuri.org/ICustomerMaster/SaveItemsResponse")]
        Rac.VOne.Web.Models.CustomersResult SaveItems(string SessionKey, Rac.VOne.Web.Models.Customer[] Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/SaveItems", ReplyAction="http://tempuri.org/ICustomerMaster/SaveItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> SaveItemsAsync(string SessionKey, Rac.VOne.Web.Models.Customer[] Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/Get", ReplyAction="http://tempuri.org/ICustomerMaster/GetResponse")]
        Rac.VOne.Web.Models.CustomersResult Get(string SessionKey, int[] Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/Get", ReplyAction="http://tempuri.org/ICustomerMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetAsync(string SessionKey, int[] Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetItemsWith", ReplyAction="http://tempuri.org/ICustomerMaster/GetItemsWithResponse")]
        Rac.VOne.Web.Models.CustomersResult GetItemsWith(int CompanyId, string SessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetItemsWith", ReplyAction="http://tempuri.org/ICustomerMaster/GetItemsWithResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetItemsWithAsync(int CompanyId, string SessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/SavePaymentContract", ReplyAction="http://tempuri.org/ICustomerMaster/SavePaymentContractResponse")]
        Rac.VOne.Web.Models.CustomerPaymentContractResult SavePaymentContract(string SessionKey, Rac.VOne.Web.Models.CustomerPaymentContract CustomerPaymentContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/SavePaymentContract", ReplyAction="http://tempuri.org/ICustomerMaster/SavePaymentContractResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerPaymentContractResult> SavePaymentContractAsync(string SessionKey, Rac.VOne.Web.Models.CustomerPaymentContract CustomerPaymentContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/SaveDiscount", ReplyAction="http://tempuri.org/ICustomerMaster/SaveDiscountResponse")]
        Rac.VOne.Web.Models.CustomerDiscountResult SaveDiscount(string SessionKey, Rac.VOne.Web.Models.CustomerDiscount CustomerDiscount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/SaveDiscount", ReplyAction="http://tempuri.org/ICustomerMaster/SaveDiscountResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerDiscountResult> SaveDiscountAsync(string SessionKey, Rac.VOne.Web.Models.CustomerDiscount CustomerDiscount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/DeletePaymentContract", ReplyAction="http://tempuri.org/ICustomerMaster/DeletePaymentContractResponse")]
        Rac.VOne.Web.Models.CountResult DeletePaymentContract(string SessionKey, int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/DeletePaymentContract", ReplyAction="http://tempuri.org/ICustomerMaster/DeletePaymentContractResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeletePaymentContractAsync(string SessionKey, int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetPaymentContract", ReplyAction="http://tempuri.org/ICustomerMaster/GetPaymentContractResponse")]
        Rac.VOne.Web.Models.CustomerPaymentContractsResult GetPaymentContract(string SessionKey, int[] CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetPaymentContract", ReplyAction="http://tempuri.org/ICustomerMaster/GetPaymentContractResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerPaymentContractsResult> GetPaymentContractAsync(string SessionKey, int[] CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetDiscount", ReplyAction="http://tempuri.org/ICustomerMaster/GetDiscountResponse")]
        Rac.VOne.Web.Models.CustomerDiscountsResult GetDiscount(string SessionKey, int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetDiscount", ReplyAction="http://tempuri.org/ICustomerMaster/GetDiscountResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerDiscountsResult> GetDiscountAsync(string SessionKey, int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetParentItems", ReplyAction="http://tempuri.org/ICustomerMaster/GetParentItemsResponse")]
        Rac.VOne.Web.Models.CustomersResult GetParentItems(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetParentItems", ReplyAction="http://tempuri.org/ICustomerMaster/GetParentItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetParentItemsAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetCustomerDetailItems", ReplyAction="http://tempuri.org/ICustomerMaster/GetCustomerDetailItemsResponse")]
        Rac.VOne.Web.Models.CustomersResult GetCustomerDetailItems(int CompanyId, string Code, string Name, int ShareTransferFee, int ClosingDay, string SessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetCustomerDetailItems", ReplyAction="http://tempuri.org/ICustomerMaster/GetCustomerDetailItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetCustomerDetailItemsAsync(int CompanyId, string Code, string Name, int ShareTransferFee, int ClosingDay, string SessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetByCode", ReplyAction="http://tempuri.org/ICustomerMaster/GetByCodeResponse")]
        Rac.VOne.Web.Models.CustomersResult GetByCode(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetByCode", ReplyAction="http://tempuri.org/ICustomerMaster/GetByCodeResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetByCodeAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetItems", ReplyAction="http://tempuri.org/ICustomerMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.CustomersResult GetItems(string Sessionkey, int CompanyId, Rac.VOne.Web.Models.CustomerSearch CustomerSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetItems", ReplyAction="http://tempuri.org/ICustomerMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetItemsAsync(string Sessionkey, int CompanyId, Rac.VOne.Web.Models.CustomerSearch CustomerSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/Delete", ReplyAction="http://tempuri.org/ICustomerMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/Delete", ReplyAction="http://tempuri.org/ICustomerMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetByChildDetails", ReplyAction="http://tempuri.org/ICustomerMaster/GetByChildDetailsResponse")]
        Rac.VOne.Web.Models.CustomersResult GetByChildDetails(string SessionKey, int CompanyId, int ParentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetByChildDetails", ReplyAction="http://tempuri.org/ICustomerMaster/GetByChildDetailsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetByChildDetailsAsync(string SessionKey, int CompanyId, int ParentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/DeleteDiscount", ReplyAction="http://tempuri.org/ICustomerMaster/DeleteDiscountResponse")]
        Rac.VOne.Web.Models.CountResult DeleteDiscount(string SessionKey, int CustomerId, int Sequence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/DeleteDiscount", ReplyAction="http://tempuri.org/ICustomerMaster/DeleteDiscountResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteDiscountAsync(string SessionKey, int CustomerId, int Sequence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetDiscountItems", ReplyAction="http://tempuri.org/ICustomerMaster/GetDiscountItemsResponse")]
        Rac.VOne.Web.Models.CustomerDiscountsResult GetDiscountItems(string SessionKey, Rac.VOne.Web.Models.CustomerSearch CustomerSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetDiscountItems", ReplyAction="http://tempuri.org/ICustomerMaster/GetDiscountItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerDiscountsResult> GetDiscountItemsAsync(string SessionKey, Rac.VOne.Web.Models.CustomerSearch CustomerSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/ExistCategory", ReplyAction="http://tempuri.org/ICustomerMaster/ExistCategoryResponse")]
        Rac.VOne.Web.Models.ExistResult ExistCategory(string SessionKey, int CategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/ExistCategory", ReplyAction="http://tempuri.org/ICustomerMaster/ExistCategoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCategoryAsync(string SessionKey, int CategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/ExistStaff", ReplyAction="http://tempuri.org/ICustomerMaster/ExistStaffResponse")]
        Rac.VOne.Web.Models.ExistResult ExistStaff(string SessionKey, int StaffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/ExistStaff", ReplyAction="http://tempuri.org/ICustomerMaster/ExistStaffResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistStaffAsync(string SessionKey, int StaffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/ExistCompany", ReplyAction="http://tempuri.org/ICustomerMaster/ExistCompanyResponse")]
        Rac.VOne.Web.Models.ExistResult ExistCompany(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/ExistCompany", ReplyAction="http://tempuri.org/ICustomerMaster/ExistCompanyResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCompanyAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetCustomerGroup", ReplyAction="http://tempuri.org/ICustomerMaster/GetCustomerGroupResponse")]
        Rac.VOne.Web.Models.CustomersResult GetCustomerGroup(string SessionKey, int CompanyId, int ParentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetCustomerGroup", ReplyAction="http://tempuri.org/ICustomerMaster/GetCustomerGroupResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetCustomerGroupAsync(string SessionKey, int CompanyId, int ParentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetCustomerWithList", ReplyAction="http://tempuri.org/ICustomerMaster/GetCustomerWithListResponse")]
        Rac.VOne.Web.Models.CustomersResult GetCustomerWithList(string SessionKey, int CompanyId, int[] CusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetCustomerWithList", ReplyAction="http://tempuri.org/ICustomerMaster/GetCustomerWithListResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetCustomerWithListAsync(string SessionKey, int CompanyId, int[] CusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetTopCustomer", ReplyAction="http://tempuri.org/ICustomerMaster/GetTopCustomerResponse")]
        Rac.VOne.Web.Models.CustomerResult GetTopCustomer(string SessionKey, Rac.VOne.Web.Models.Customer Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetTopCustomer", ReplyAction="http://tempuri.org/ICustomerMaster/GetTopCustomerResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerResult> GetTopCustomerAsync(string SessionKey, Rac.VOne.Web.Models.Customer Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForCustomerGroupParent", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForCustomerGroupParentResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForCustomerGroupParent(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForCustomerGroupParent", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForCustomerGroupParentResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForCustomerGroupParentAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForCustomerGroupChild", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForCustomerGroupChildResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForCustomerGroupChild(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForCustomerGroupChild", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForCustomerGroupChildResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForCustomerGroupChildAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForKanaHistory", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForKanaHistoryResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForKanaHistory(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForKanaHistory", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForKanaHistoryResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForKanaHistoryAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForBilling", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForBillingResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForBilling(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForBilling", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForBillingResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForBillingAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForReceipt", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForReceiptResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForReceipt(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForReceipt", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForReceiptResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForReceiptAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForNetting", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForNettingResponse")]
        Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForNetting(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetImportItemsForNetting", ReplyAction="http://tempuri.org/ICustomerMaster/GetImportItemsForNettingResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForNettingAsync(string SessionKey, int CompanyId, string[] Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/Import", ReplyAction="http://tempuri.org/ICustomerMaster/ImportResponse")]
        Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.Customer[] InsertList, Rac.VOne.Web.Models.Customer[] UpdateList, Rac.VOne.Web.Models.Customer[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/Import", ReplyAction="http://tempuri.org/ICustomerMaster/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.Customer[] InsertList, Rac.VOne.Web.Models.Customer[] UpdateList, Rac.VOne.Web.Models.Customer[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetMinItems", ReplyAction="http://tempuri.org/ICustomerMaster/GetMinItemsResponse")]
        Rac.VOne.Web.Models.CustomerMinsResult GetMinItems(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMaster/GetMinItems", ReplyAction="http://tempuri.org/ICustomerMaster/GetMinItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerMinsResult> GetMinItemsAsync(string SessionKey, int CompanyId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerMasterChannel : Rac.VOne.Client.Screen.CustomerMasterService.ICustomerMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.CustomerMasterService.ICustomerMaster>, Rac.VOne.Client.Screen.CustomerMasterService.ICustomerMaster {
        
        public CustomerMasterClient() {
        }
        
        public CustomerMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.CustomerResult Save(string SessionKey, Rac.VOne.Web.Models.Customer Customer) {
            return base.Channel.Save(SessionKey, Customer);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.Customer Customer) {
            return base.Channel.SaveAsync(SessionKey, Customer);
        }
        
        public Rac.VOne.Web.Models.CustomersResult SaveItems(string SessionKey, Rac.VOne.Web.Models.Customer[] Customer) {
            return base.Channel.SaveItems(SessionKey, Customer);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> SaveItemsAsync(string SessionKey, Rac.VOne.Web.Models.Customer[] Customer) {
            return base.Channel.SaveItemsAsync(SessionKey, Customer);
        }
        
        public Rac.VOne.Web.Models.CustomersResult Get(string SessionKey, int[] Id) {
            return base.Channel.Get(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetAsync(string SessionKey, int[] Id) {
            return base.Channel.GetAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.CustomersResult GetItemsWith(int CompanyId, string SessionKey) {
            return base.Channel.GetItemsWith(CompanyId, SessionKey);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetItemsWithAsync(int CompanyId, string SessionKey) {
            return base.Channel.GetItemsWithAsync(CompanyId, SessionKey);
        }
        
        public Rac.VOne.Web.Models.CustomerPaymentContractResult SavePaymentContract(string SessionKey, Rac.VOne.Web.Models.CustomerPaymentContract CustomerPaymentContract) {
            return base.Channel.SavePaymentContract(SessionKey, CustomerPaymentContract);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerPaymentContractResult> SavePaymentContractAsync(string SessionKey, Rac.VOne.Web.Models.CustomerPaymentContract CustomerPaymentContract) {
            return base.Channel.SavePaymentContractAsync(SessionKey, CustomerPaymentContract);
        }
        
        public Rac.VOne.Web.Models.CustomerDiscountResult SaveDiscount(string SessionKey, Rac.VOne.Web.Models.CustomerDiscount CustomerDiscount) {
            return base.Channel.SaveDiscount(SessionKey, CustomerDiscount);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerDiscountResult> SaveDiscountAsync(string SessionKey, Rac.VOne.Web.Models.CustomerDiscount CustomerDiscount) {
            return base.Channel.SaveDiscountAsync(SessionKey, CustomerDiscount);
        }
        
        public Rac.VOne.Web.Models.CountResult DeletePaymentContract(string SessionKey, int CustomerId) {
            return base.Channel.DeletePaymentContract(SessionKey, CustomerId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeletePaymentContractAsync(string SessionKey, int CustomerId) {
            return base.Channel.DeletePaymentContractAsync(SessionKey, CustomerId);
        }
        
        public Rac.VOne.Web.Models.CustomerPaymentContractsResult GetPaymentContract(string SessionKey, int[] CustomerId) {
            return base.Channel.GetPaymentContract(SessionKey, CustomerId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerPaymentContractsResult> GetPaymentContractAsync(string SessionKey, int[] CustomerId) {
            return base.Channel.GetPaymentContractAsync(SessionKey, CustomerId);
        }
        
        public Rac.VOne.Web.Models.CustomerDiscountsResult GetDiscount(string SessionKey, int customerId) {
            return base.Channel.GetDiscount(SessionKey, customerId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerDiscountsResult> GetDiscountAsync(string SessionKey, int customerId) {
            return base.Channel.GetDiscountAsync(SessionKey, customerId);
        }
        
        public Rac.VOne.Web.Models.CustomersResult GetParentItems(string SessionKey, int CompanyId) {
            return base.Channel.GetParentItems(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetParentItemsAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetParentItemsAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.CustomersResult GetCustomerDetailItems(int CompanyId, string Code, string Name, int ShareTransferFee, int ClosingDay, string SessionKey) {
            return base.Channel.GetCustomerDetailItems(CompanyId, Code, Name, ShareTransferFee, ClosingDay, SessionKey);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetCustomerDetailItemsAsync(int CompanyId, string Code, string Name, int ShareTransferFee, int ClosingDay, string SessionKey) {
            return base.Channel.GetCustomerDetailItemsAsync(CompanyId, Code, Name, ShareTransferFee, ClosingDay, SessionKey);
        }
        
        public Rac.VOne.Web.Models.CustomersResult GetByCode(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetByCode(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetByCodeAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetByCodeAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.CustomersResult GetItems(string Sessionkey, int CompanyId, Rac.VOne.Web.Models.CustomerSearch CustomerSearch) {
            return base.Channel.GetItems(Sessionkey, CompanyId, CustomerSearch);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetItemsAsync(string Sessionkey, int CompanyId, Rac.VOne.Web.Models.CustomerSearch CustomerSearch) {
            return base.Channel.GetItemsAsync(Sessionkey, CompanyId, CustomerSearch);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CustomerId) {
            return base.Channel.Delete(SessionKey, CustomerId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CustomerId) {
            return base.Channel.DeleteAsync(SessionKey, CustomerId);
        }
        
        public Rac.VOne.Web.Models.CustomersResult GetByChildDetails(string SessionKey, int CompanyId, int ParentId) {
            return base.Channel.GetByChildDetails(SessionKey, CompanyId, ParentId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetByChildDetailsAsync(string SessionKey, int CompanyId, int ParentId) {
            return base.Channel.GetByChildDetailsAsync(SessionKey, CompanyId, ParentId);
        }
        
        public Rac.VOne.Web.Models.CountResult DeleteDiscount(string SessionKey, int CustomerId, int Sequence) {
            return base.Channel.DeleteDiscount(SessionKey, CustomerId, Sequence);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteDiscountAsync(string SessionKey, int CustomerId, int Sequence) {
            return base.Channel.DeleteDiscountAsync(SessionKey, CustomerId, Sequence);
        }
        
        public Rac.VOne.Web.Models.CustomerDiscountsResult GetDiscountItems(string SessionKey, Rac.VOne.Web.Models.CustomerSearch CustomerSearch) {
            return base.Channel.GetDiscountItems(SessionKey, CustomerSearch);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerDiscountsResult> GetDiscountItemsAsync(string SessionKey, Rac.VOne.Web.Models.CustomerSearch CustomerSearch) {
            return base.Channel.GetDiscountItemsAsync(SessionKey, CustomerSearch);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistCategory(string SessionKey, int CategoryId) {
            return base.Channel.ExistCategory(SessionKey, CategoryId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCategoryAsync(string SessionKey, int CategoryId) {
            return base.Channel.ExistCategoryAsync(SessionKey, CategoryId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistStaff(string SessionKey, int StaffId) {
            return base.Channel.ExistStaff(SessionKey, StaffId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistStaffAsync(string SessionKey, int StaffId) {
            return base.Channel.ExistStaffAsync(SessionKey, StaffId);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistCompany(string SessionKey, int CompanyId) {
            return base.Channel.ExistCompany(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCompanyAsync(string SessionKey, int CompanyId) {
            return base.Channel.ExistCompanyAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.CustomersResult GetCustomerGroup(string SessionKey, int CompanyId, int ParentId) {
            return base.Channel.GetCustomerGroup(SessionKey, CompanyId, ParentId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetCustomerGroupAsync(string SessionKey, int CompanyId, int ParentId) {
            return base.Channel.GetCustomerGroupAsync(SessionKey, CompanyId, ParentId);
        }
        
        public Rac.VOne.Web.Models.CustomersResult GetCustomerWithList(string SessionKey, int CompanyId, int[] CusId) {
            return base.Channel.GetCustomerWithList(SessionKey, CompanyId, CusId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomersResult> GetCustomerWithListAsync(string SessionKey, int CompanyId, int[] CusId) {
            return base.Channel.GetCustomerWithListAsync(SessionKey, CompanyId, CusId);
        }
        
        public Rac.VOne.Web.Models.CustomerResult GetTopCustomer(string SessionKey, Rac.VOne.Web.Models.Customer Customer) {
            return base.Channel.GetTopCustomer(SessionKey, Customer);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerResult> GetTopCustomerAsync(string SessionKey, Rac.VOne.Web.Models.Customer Customer) {
            return base.Channel.GetTopCustomerAsync(SessionKey, Customer);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForCustomerGroupParent(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForCustomerGroupParent(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForCustomerGroupParentAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForCustomerGroupParentAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForCustomerGroupChild(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForCustomerGroupChild(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForCustomerGroupChildAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForCustomerGroupChildAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForKanaHistory(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForKanaHistory(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForKanaHistoryAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForKanaHistoryAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForBilling(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForBilling(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForBillingAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForBillingAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForReceipt(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForReceipt(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForReceiptAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForReceiptAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.MasterDatasResult GetImportItemsForNetting(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForNetting(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.MasterDatasResult> GetImportItemsForNettingAsync(string SessionKey, int CompanyId, string[] Code) {
            return base.Channel.GetImportItemsForNettingAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.ImportResult Import(string SessionKey, Rac.VOne.Web.Models.Customer[] InsertList, Rac.VOne.Web.Models.Customer[] UpdateList, Rac.VOne.Web.Models.Customer[] DeleteList) {
            return base.Channel.Import(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResult> ImportAsync(string SessionKey, Rac.VOne.Web.Models.Customer[] InsertList, Rac.VOne.Web.Models.Customer[] UpdateList, Rac.VOne.Web.Models.Customer[] DeleteList) {
            return base.Channel.ImportAsync(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public Rac.VOne.Web.Models.CustomerMinsResult GetMinItems(string SessionKey, int CompanyId) {
            return base.Channel.GetMinItems(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerMinsResult> GetMinItemsAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetMinItemsAsync(SessionKey, CompanyId);
        }
    }
}
