//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.ReceiptMemoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReceiptMemoService.IReceiptMemoService")]
    public interface IReceiptMemoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiptMemoService/GetItems", ReplyAction="http://tempuri.org/IReceiptMemoService/GetItemsResponse")]
        Rac.VOne.Web.Models.ReceiptMemosResult GetItems(string SessionKey, long[] receiptIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiptMemoService/GetItems", ReplyAction="http://tempuri.org/IReceiptMemoService/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReceiptMemosResult> GetItemsAsync(string SessionKey, long[] receiptIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceiptMemoServiceChannel : Rac.VOne.Client.Screen.ReceiptMemoService.IReceiptMemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiptMemoServiceClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.ReceiptMemoService.IReceiptMemoService>, Rac.VOne.Client.Screen.ReceiptMemoService.IReceiptMemoService {
        
        public ReceiptMemoServiceClient() {
        }
        
        public ReceiptMemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiptMemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiptMemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiptMemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.ReceiptMemosResult GetItems(string SessionKey, long[] receiptIds) {
            return base.Channel.GetItems(SessionKey, receiptIds);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ReceiptMemosResult> GetItemsAsync(string SessionKey, long[] receiptIds) {
            return base.Channel.GetItemsAsync(SessionKey, receiptIds);
        }
    }
}
