//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.GridSettingMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GridSettingMasterService.IGridSettingMaster")]
    public interface IGridSettingMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGridSettingMaster/Save", ReplyAction="http://tempuri.org/IGridSettingMaster/SaveResponse")]
        Rac.VOne.Web.Models.GridSettingResult Save(string SessionKey, Rac.VOne.Web.Models.GridSetting[] GridSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGridSettingMaster/Save", ReplyAction="http://tempuri.org/IGridSettingMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.GridSettingResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.GridSetting[] GridSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGridSettingMaster/GetItems", ReplyAction="http://tempuri.org/IGridSettingMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.GridSettingsResult GetItems(string SessionKey, int CompanyId, int LoginUserId, System.Nullable<int> GridId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGridSettingMaster/GetItems", ReplyAction="http://tempuri.org/IGridSettingMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.GridSettingsResult> GetItemsAsync(string SessionKey, int CompanyId, int LoginUserId, System.Nullable<int> GridId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGridSettingMaster/GetDefaultItems", ReplyAction="http://tempuri.org/IGridSettingMaster/GetDefaultItemsResponse")]
        Rac.VOne.Web.Models.GridSettingsResult GetDefaultItems(string SessionKey, int CompanyId, int LoginUserId, System.Nullable<int> GridId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGridSettingMaster/GetDefaultItems", ReplyAction="http://tempuri.org/IGridSettingMaster/GetDefaultItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.GridSettingsResult> GetDefaultItemsAsync(string SessionKey, int CompanyId, int LoginUserId, System.Nullable<int> GridId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGridSettingMasterChannel : Rac.VOne.Client.Screen.GridSettingMasterService.IGridSettingMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GridSettingMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.GridSettingMasterService.IGridSettingMaster>, Rac.VOne.Client.Screen.GridSettingMasterService.IGridSettingMaster {
        
        public GridSettingMasterClient() {
        }
        
        public GridSettingMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GridSettingMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GridSettingMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GridSettingMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.GridSettingResult Save(string SessionKey, Rac.VOne.Web.Models.GridSetting[] GridSettings) {
            return base.Channel.Save(SessionKey, GridSettings);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.GridSettingResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.GridSetting[] GridSettings) {
            return base.Channel.SaveAsync(SessionKey, GridSettings);
        }
        
        public Rac.VOne.Web.Models.GridSettingsResult GetItems(string SessionKey, int CompanyId, int LoginUserId, System.Nullable<int> GridId) {
            return base.Channel.GetItems(SessionKey, CompanyId, LoginUserId, GridId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.GridSettingsResult> GetItemsAsync(string SessionKey, int CompanyId, int LoginUserId, System.Nullable<int> GridId) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId, LoginUserId, GridId);
        }
        
        public Rac.VOne.Web.Models.GridSettingsResult GetDefaultItems(string SessionKey, int CompanyId, int LoginUserId, System.Nullable<int> GridId) {
            return base.Channel.GetDefaultItems(SessionKey, CompanyId, LoginUserId, GridId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.GridSettingsResult> GetDefaultItemsAsync(string SessionKey, int CompanyId, int LoginUserId, System.Nullable<int> GridId) {
            return base.Channel.GetDefaultItemsAsync(SessionKey, CompanyId, LoginUserId, GridId);
        }
    }
}
