//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.TaskScheduleMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskScheduleMasterService.ITaskScheduleMaster")]
    public interface ITaskScheduleMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleMaster/Save", ReplyAction="http://tempuri.org/ITaskScheduleMaster/SaveResponse")]
        Rac.VOne.Web.Models.TaskScheduleResult Save(string SessionKey, Rac.VOne.Web.Models.TaskSchedule TaskSchedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleMaster/Save", ReplyAction="http://tempuri.org/ITaskScheduleMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.TaskScheduleResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.TaskSchedule TaskSchedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleMaster/Delete", ReplyAction="http://tempuri.org/ITaskScheduleMaster/DeleteResponse")]
        Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CompanyId, int ImportType, int ImportSubType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleMaster/Delete", ReplyAction="http://tempuri.org/ITaskScheduleMaster/DeleteResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CompanyId, int ImportType, int ImportSubType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleMaster/Get", ReplyAction="http://tempuri.org/ITaskScheduleMaster/GetResponse")]
        Rac.VOne.Web.Models.TaskScheduleResult Get(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleMaster/Get", ReplyAction="http://tempuri.org/ITaskScheduleMaster/GetResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.TaskScheduleResult> GetAsync(string SessionKey, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleMaster/GetItems", ReplyAction="http://tempuri.org/ITaskScheduleMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.TaskSchedulesResult GetItems(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleMaster/GetItems", ReplyAction="http://tempuri.org/ITaskScheduleMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.TaskSchedulesResult> GetItemsAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleMaster/Exists", ReplyAction="http://tempuri.org/ITaskScheduleMaster/ExistsResponse")]
        Rac.VOne.Web.Models.ExistResult Exists(string SessionKey, int CompanyId, int ImportType, int ImportSubType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskScheduleMaster/Exists", ReplyAction="http://tempuri.org/ITaskScheduleMaster/ExistsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistsAsync(string SessionKey, int CompanyId, int ImportType, int ImportSubType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskScheduleMasterChannel : Rac.VOne.Client.Screen.TaskScheduleMasterService.ITaskScheduleMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskScheduleMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.TaskScheduleMasterService.ITaskScheduleMaster>, Rac.VOne.Client.Screen.TaskScheduleMasterService.ITaskScheduleMaster {
        
        public TaskScheduleMasterClient() {
        }
        
        public TaskScheduleMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskScheduleMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskScheduleMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskScheduleMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.TaskScheduleResult Save(string SessionKey, Rac.VOne.Web.Models.TaskSchedule TaskSchedule) {
            return base.Channel.Save(SessionKey, TaskSchedule);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.TaskScheduleResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.TaskSchedule TaskSchedule) {
            return base.Channel.SaveAsync(SessionKey, TaskSchedule);
        }
        
        public Rac.VOne.Web.Models.CountResult Delete(string SessionKey, int CompanyId, int ImportType, int ImportSubType) {
            return base.Channel.Delete(SessionKey, CompanyId, ImportType, ImportSubType);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> DeleteAsync(string SessionKey, int CompanyId, int ImportType, int ImportSubType) {
            return base.Channel.DeleteAsync(SessionKey, CompanyId, ImportType, ImportSubType);
        }
        
        public Rac.VOne.Web.Models.TaskScheduleResult Get(string SessionKey, int Id) {
            return base.Channel.Get(SessionKey, Id);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.TaskScheduleResult> GetAsync(string SessionKey, int Id) {
            return base.Channel.GetAsync(SessionKey, Id);
        }
        
        public Rac.VOne.Web.Models.TaskSchedulesResult GetItems(string SessionKey, int CompanyId) {
            return base.Channel.GetItems(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.TaskSchedulesResult> GetItemsAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.ExistResult Exists(string SessionKey, int CompanyId, int ImportType, int ImportSubType) {
            return base.Channel.Exists(SessionKey, CompanyId, ImportType, ImportSubType);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistsAsync(string SessionKey, int CompanyId, int ImportType, int ImportSubType) {
            return base.Channel.ExistsAsync(SessionKey, CompanyId, ImportType, ImportSubType);
        }
    }
}
