//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rac.VOne.Client.Screen.CustomerGroupMasterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerGroupMasterService.ICustomerGroupMaster")]
    public interface ICustomerGroupMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetByParent", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetByParentResponse")]
        Rac.VOne.Web.Models.CustomerGroupsResult GetByParent(string SessionKey, int ParentCustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetByParent", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetByParentResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupsResult> GetByParentAsync(string SessionKey, int ParentCustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/Save", ReplyAction="http://tempuri.org/ICustomerGroupMaster/SaveResponse")]
        Rac.VOne.Web.Models.CustomerGroupResult Save(string SessionKey, Rac.VOne.Web.Models.CustomerGroup[] AddList, Rac.VOne.Web.Models.CustomerGroup[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/Save", ReplyAction="http://tempuri.org/ICustomerGroupMaster/SaveResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.CustomerGroup[] AddList, Rac.VOne.Web.Models.CustomerGroup[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/ExistCustomer", ReplyAction="http://tempuri.org/ICustomerGroupMaster/ExistCustomerResponse")]
        Rac.VOne.Web.Models.ExistResult ExistCustomer(string SessionKey, int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/ExistCustomer", ReplyAction="http://tempuri.org/ICustomerGroupMaster/ExistCustomerResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCustomerAsync(string SessionKey, int CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetItems", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetItemsResponse")]
        Rac.VOne.Web.Models.CustomerGroupsResult GetItems(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetItems", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetItemsResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupsResult> GetItemsAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/Import", ReplyAction="http://tempuri.org/ICustomerGroupMaster/ImportResponse")]
        Rac.VOne.Web.Models.ImportResultCustomerGroup Import(string SessionKey, Rac.VOne.Web.Models.CustomerGroup[] InsertList, Rac.VOne.Web.Models.CustomerGroup[] UpdateList, Rac.VOne.Web.Models.CustomerGroup[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/Import", ReplyAction="http://tempuri.org/ICustomerGroupMaster/ImportResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResultCustomerGroup> ImportAsync(string SessionKey, Rac.VOne.Web.Models.CustomerGroup[] InsertList, Rac.VOne.Web.Models.CustomerGroup[] UpdateList, Rac.VOne.Web.Models.CustomerGroup[] DeleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetByChildId", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetByChildIdResponse")]
        Rac.VOne.Web.Models.CustomerGroupsResult GetByChildId(string SessionKey, int[] ChildCustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetByChildId", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetByChildIdResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupsResult> GetByChildIdAsync(string SessionKey, int[] ChildCustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetPrintCustomerData", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetPrintCustomerDataResponse")]
        Rac.VOne.Web.Models.CustomerGroupsResult GetPrintCustomerData(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetPrintCustomerData", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetPrintCustomerDataResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupsResult> GetPrintCustomerDataAsync(string SessionKey, int CompanyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetCustomerForCustomerGroup", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetCustomerForCustomerGroupResponse")]
        Rac.VOne.Web.Models.CustomerGroupResult GetCustomerForCustomerGroup(string SessionKey, int CompanyId, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetCustomerForCustomerGroup", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetCustomerForCustomerGroupResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupResult> GetCustomerForCustomerGroupAsync(string SessionKey, int CompanyId, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/HasChild", ReplyAction="http://tempuri.org/ICustomerGroupMaster/HasChildResponse")]
        Rac.VOne.Web.Models.ExistResult HasChild(string SessionKey, int ParentCustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/HasChild", ReplyAction="http://tempuri.org/ICustomerGroupMaster/HasChildResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> HasChildAsync(string SessionKey, int ParentCustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetUniqueGroupCount", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetUniqueGroupCountResponse")]
        Rac.VOne.Web.Models.CountResult GetUniqueGroupCount(string SessionKey, int[] Ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerGroupMaster/GetUniqueGroupCount", ReplyAction="http://tempuri.org/ICustomerGroupMaster/GetUniqueGroupCountResponse")]
        System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> GetUniqueGroupCountAsync(string SessionKey, int[] Ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerGroupMasterChannel : Rac.VOne.Client.Screen.CustomerGroupMasterService.ICustomerGroupMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerGroupMasterClient : System.ServiceModel.ClientBase<Rac.VOne.Client.Screen.CustomerGroupMasterService.ICustomerGroupMaster>, Rac.VOne.Client.Screen.CustomerGroupMasterService.ICustomerGroupMaster {
        
        public CustomerGroupMasterClient() {
        }
        
        public CustomerGroupMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerGroupMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerGroupMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerGroupMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rac.VOne.Web.Models.CustomerGroupsResult GetByParent(string SessionKey, int ParentCustomerId) {
            return base.Channel.GetByParent(SessionKey, ParentCustomerId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupsResult> GetByParentAsync(string SessionKey, int ParentCustomerId) {
            return base.Channel.GetByParentAsync(SessionKey, ParentCustomerId);
        }
        
        public Rac.VOne.Web.Models.CustomerGroupResult Save(string SessionKey, Rac.VOne.Web.Models.CustomerGroup[] AddList, Rac.VOne.Web.Models.CustomerGroup[] DeleteList) {
            return base.Channel.Save(SessionKey, AddList, DeleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupResult> SaveAsync(string SessionKey, Rac.VOne.Web.Models.CustomerGroup[] AddList, Rac.VOne.Web.Models.CustomerGroup[] DeleteList) {
            return base.Channel.SaveAsync(SessionKey, AddList, DeleteList);
        }
        
        public Rac.VOne.Web.Models.ExistResult ExistCustomer(string SessionKey, int CustomerId) {
            return base.Channel.ExistCustomer(SessionKey, CustomerId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> ExistCustomerAsync(string SessionKey, int CustomerId) {
            return base.Channel.ExistCustomerAsync(SessionKey, CustomerId);
        }
        
        public Rac.VOne.Web.Models.CustomerGroupsResult GetItems(string SessionKey, int CompanyId) {
            return base.Channel.GetItems(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupsResult> GetItemsAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetItemsAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.ImportResultCustomerGroup Import(string SessionKey, Rac.VOne.Web.Models.CustomerGroup[] InsertList, Rac.VOne.Web.Models.CustomerGroup[] UpdateList, Rac.VOne.Web.Models.CustomerGroup[] DeleteList) {
            return base.Channel.Import(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ImportResultCustomerGroup> ImportAsync(string SessionKey, Rac.VOne.Web.Models.CustomerGroup[] InsertList, Rac.VOne.Web.Models.CustomerGroup[] UpdateList, Rac.VOne.Web.Models.CustomerGroup[] DeleteList) {
            return base.Channel.ImportAsync(SessionKey, InsertList, UpdateList, DeleteList);
        }
        
        public Rac.VOne.Web.Models.CustomerGroupsResult GetByChildId(string SessionKey, int[] ChildCustomerId) {
            return base.Channel.GetByChildId(SessionKey, ChildCustomerId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupsResult> GetByChildIdAsync(string SessionKey, int[] ChildCustomerId) {
            return base.Channel.GetByChildIdAsync(SessionKey, ChildCustomerId);
        }
        
        public Rac.VOne.Web.Models.CustomerGroupsResult GetPrintCustomerData(string SessionKey, int CompanyId) {
            return base.Channel.GetPrintCustomerData(SessionKey, CompanyId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupsResult> GetPrintCustomerDataAsync(string SessionKey, int CompanyId) {
            return base.Channel.GetPrintCustomerDataAsync(SessionKey, CompanyId);
        }
        
        public Rac.VOne.Web.Models.CustomerGroupResult GetCustomerForCustomerGroup(string SessionKey, int CompanyId, string Code) {
            return base.Channel.GetCustomerForCustomerGroup(SessionKey, CompanyId, Code);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CustomerGroupResult> GetCustomerForCustomerGroupAsync(string SessionKey, int CompanyId, string Code) {
            return base.Channel.GetCustomerForCustomerGroupAsync(SessionKey, CompanyId, Code);
        }
        
        public Rac.VOne.Web.Models.ExistResult HasChild(string SessionKey, int ParentCustomerId) {
            return base.Channel.HasChild(SessionKey, ParentCustomerId);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.ExistResult> HasChildAsync(string SessionKey, int ParentCustomerId) {
            return base.Channel.HasChildAsync(SessionKey, ParentCustomerId);
        }
        
        public Rac.VOne.Web.Models.CountResult GetUniqueGroupCount(string SessionKey, int[] Ids) {
            return base.Channel.GetUniqueGroupCount(SessionKey, Ids);
        }
        
        public System.Threading.Tasks.Task<Rac.VOne.Web.Models.CountResult> GetUniqueGroupCountAsync(string SessionKey, int[] Ids) {
            return base.Channel.GetUniqueGroupCountAsync(SessionKey, Ids);
        }
    }
}
